### ISSUE TITLE
Grade selection should not reset in PAT & SAT Map reports

### ISSUE THREAD

**Issue by SreenivasNimmagadda** [Sunbird-cQube/community#10]
**Purpose of the Feature**
The Grade drop down is resetting when the location is changed in PAT & SAT map reports. It is difficult to an user to select the grade every time by changing the location.

**Reference Screenshots**
![image](https://user-images.githubusercontent.com/61133774/136219230-fa192798-50c3-4c11-801e-14b5ec16034f.png)
![image](https://user-images.githubusercontent.com/61133774/136219254-96de5063-412c-4204-854b-cb2a8e03e6cd.png)

**Proposed Solutions*
Keep the Selected Grade as constant. It should not change even after selecting the Destrict/Block/cluster
If the location is not having the Grade, Show "No data found"

**Comment by dheeraj8008tiwari** [comment]
This task has been completed.
