### ISSUE TITLE
Re-organization code in the cQube_Edu Repository

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#111]
1. Create the following folders in cqube_edu_alpha repo
   -  cqube-devops
   - cqube-config
   - cqube-reference-visualization-app
   - cqube-processing
   - cqube-ingestion

2. Move all the respective code to respective folders which needs to be taken from the cQube_Base and cQube_Workflow repo's.

**Comment by padmanabha1234** [comment]
1. In cqube-processing we have created python folder which includes the config python files, updating the processor property value to nifi related files.
2. And created the nifi-utils folder which includes the nifi deployment python code

**Comment by JalajaTR** [comment]
1. Moved all the processing related code to cqube-processing directory under cQube-4.0 alpha repo.

**Comment by RNarmatha** [comment]
Completed
