### ISSUE TITLE
Regression Testing in cQube-4.0

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#112]
what is the Requirement?
where the new development is required? (whether it is Ingestion or processing or configuration or visualization app)
when can finish the requirement?

**Comment by devu1454** [comment]
1.Re-executing ui test cases to ensure that the product works fine with new functionality, bug fixes, or any change in the existing feature.

2.Regression requires at visualization.

3.Once the Functionality testing is completed.

**Comment by RNarmatha** [comment]
Completed
