### ISSUE TITLE
Refactor the NiFi deployment code ( python )

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#113]
Current state: NiFi deployment code has multiple python files. which are used by Ansible code to deploy NiFi.

**Current Functionalities**
1. Upload Nifi template and import the template into NiFi instance ( UI ) 
2. Create parameter context along with parameters 
3. Start/Stop/Enable/Disable the processor. 
4. Configurable Connections between Processor groups

**Proposed solution:**
Refactor  all the NiFi deployment python code into one single Python module / File as NiFi Utils.

**Comment by padmanabha1234** [comment]
what is the current reality, what is missing? --> currently we have multiple python files to deploy the nifi, 
why the enhancement required?--> For scalability
How to do the enhancement? --> Merging all the python codes as nifi_utility.py
when can finish the enhancement? --> Sep 8th

**Comment by padmanabha1234** [comment]
on Sept 6th i worked on generalising the function for all the functionalities.
on Sept 7th deveops team told me that from ansible is not able to call the function, so i worked on that which the ansible will call with the arguments and completed.

**Comment by RNarmatha** [comment]
Completed
