### ISSUE TITLE
Interactive drill-down using the legend

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#114]
Drilldown functionality to copy from cqube1 to cqube2.

1. Enhancing the default map legand look - completed
2.  Adding onclick filter functionality according to selected range- completed
3.  Add Functionality to change the color of marker according to selection range - pending

**Comment by FaizanMohammed326** [comment]
Invalid Since it is not included in cQube-4.0.

**Comment by RNarmatha** [comment]
Completed
