### ISSUE TITLE
Test Automation Script for Map report and Tooltip

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#116]
Develop the automation script for the map report and validate the tooltip information 
The Development is required for visualization app.
QA team will develop the requirement

**Comment by RNarmatha** [comment]
Completed

**Comment by RNarmatha** [comment]
Move all the test automation test scripts to the Test Repo -

**Comment by Inchara98** [comment]
Scripts are moved to Repo

**Comment by RNarmatha** [comment]
Completed
