### ISSUE TITLE
Upgrading all the test Scripts into New Framework

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#122]
Upgrading all the test scripts into the New frame work.

**Comment by chetandg123** [comment]
Completed converting PGI automation scripts to the new framework

**Comment by Inchara98** [comment]
1.Completed converting Udise, NCF, Microimprovements, PGI , Niphun bara, PM Poshan automation scripts to new framework are completed
2.Diksha, Nishtha, Dashboard, NAS, Quiz are in progress

**Comment by Inchara98** [comment]
Completed the conversion  of dashboard automation scripts to the new framework

**Comment by Inchara98** [comment]
Completed the conversion  of dashboard automation scripts to the new framework

**Comment by Inchara98** [comment]
Completed converting Diksha, NAS and quizz automation script to new framework

**Comment by Inchara98** [comment]
Completed converting all program test scripts in NVSK

**Comment by RNarmatha** [comment]
Completed converting all program test scripts in NVSK
