### ISSUE TITLE
Writing Test automation Scripts for tabs and dropdowns in Diksha, Udise+ Data sources

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#123]
Writing the  test script for Diksha and UDISE program
Development of test scripts for Vanity metrics and all the tabs are completed except the dropdown functionality.
1. Test scripts for Diksha Program: 
Learning session - dropdown functionality is pending
Learning session on potential users - completed
Implementation status - completed
ETB Coverage Status - completed
Content coverage on QR - completed
2. Test Scripts for UDISE
Completed Tabs:
     Vanity Metrics 
      Implementation  Status
     State wise Performance
     Correlation
In Progress
Dropdowns: State wise Performance and correlation

Test script for dropdown functionality will be completed by 12 Sep  2022

**Comment by Inchara98** [comment]
Correlation dropdowns completed
State wise performance - Dependent dropdowns are not able to validate because unable to get the exact xpath for markers

**Comment by Inchara98** [comment]
state wise performance tab - unable to automate the dropdowns which are there in district page because of xpath issue , we need to test it manually

**Comment by Inchara98** [comment]
State wise performance tab - completed automating the dropdowns which are present in district page

**Comment by RNarmatha** [comment]
Completed converting all program test scripts in NVSK
