### ISSUE TITLE
Writing test scripts for NCERT Quiz

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#125]
Writing the test scripts for NCERT Quiz

Test Scripts are Completed  for the following:
  Vanity Metrics- completed
  Implementation status- completed
  Participation Status- completed 
 Quizwise  Status -completed

This is completed on 9th sep 2022

**Comment by devu1454** [comment]
In Participation status, Select Quiz name dropdown automation is pending

**Comment by Inchara98** [comment]
Dependent dropdowns are completed

**Comment by RNarmatha** [comment]
Testscripts  are completed
