### ISSUE TITLE
Understand about the LibCloud and find the Gap analysis - Recommended by Santosh Vasabaktula.

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#126]
- Ingestion API code can be used for data emission into buckets
- Files can be downloaded from the buckets
- Can list the files from the buckets .

**Comment by RNarmatha** [comment]
@ananya-jain1 , Request to take a look

**Comment by ananya-jain1** [comment]
To be considered in the approach for cQube roadmap.

**Comment by RNarmatha** [comment]
To be considered in the approach for cQube roadmap.
