### ISSUE TITLE
Metrics and Dimension wise query creation with dependent and Independent filters [Data Processing]

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#130]
The static information like the geo locations information is hard coded which needs to be removed from the code

Note: As jalaja is on leave on 8th sep, moved this ticket to 9th sep

**Comment by Shoaib15khan** [comment]
Requirement is to dynamically create metrics by parsing the csv file .
creation of Output queries using python is completed with respect to the configuration file.
Today working on creating transaction to aggregation queries using python, generalizing for static datasource and for all geographical levels.

**Comment by RNarmatha** [comment]
Invalid ticket

**Comment by RNarmatha** [comment]
Invalid ticket
