### ISSUE TITLE
Enable DIKSHA data sources for Jharkhand

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#134]
To enable Diksha ETB and TPD For Jharkhand
Below are the required details :

  1. Diksha API URL
  2. API token
  3. TPD encryption key
  4. x_channel_id 
  5. TPD dataset name

**Comment by bommalla** [comment]
We have successfully enabled the Jharkhand Diksha data source.we need to emit the batch_ids to the emission directory

**Comment by bommalla** [comment]
Still Diksha URL is not accessible need to whitelisted

**Comment by RNarmatha** [comment]
Completed issue is fixed
