### ISSUE TITLE
Jharkhand people need to whitelist the DIKSHA API's

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#138]
What- what is the current reality, what is missing?
Currently, Jharkhand wants to enable the diksha data source .

Why- why the enhancement required?
Jharkhand state wants to see the diksha visualization reports on cQube dashboard

How - How to do the enhancement?
We need below mentioned details required to enable the diksha data source
1.Diksha api url
2.API token
3.TPD encryption key
4.x_channel_id 
5.TPD dataset name

Who - who will make the enhancement?
The diksha team will be responsible for this enhancement.

when - when can finish the enhancement?
Once diksha API"s got whitelist we can close the tickets as soon as possible

**Comment by bommalla** [comment]
Still I didn't get any update from Jharkhand regarding DIKSHA API's

**Comment by bommalla** [comment]
[

![Image](https://user-images.githubusercontent.com/86966482/189642015-3cf91369-8c21-4b32-b812-0a0b273154b6.png)

](url)

**Comment by TLSravani** [comment]
We are done from our side. Closing this ticket, as we are not getting any information from the Jharkhand people, Once will get the information, will re-open the ticket.

**Comment by surendrasinghs** [comment]
Why is this even created here? The ticket has nothing to do with cQube. Please create only cQube related tickets in this repo. Adopters of cQube can maintain their projects independently.
