### ISSUE TITLE
Enhance the Ingestion API code using Libcloud module

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#139]
what is the current reality, what is missing?
why the enhancement required?
How to do the enhancement?
when can finish the enhancement?

**Comment by surendrasinghs** [comment]
Dependency on the S3 bucket for ingestion (emission and input data store) needs to be removed and made cloud agnostic by using LibCloud.

**Comment by RNarmatha** [comment]
This is for understanding. Invalid further
