### ISSUE TITLE
Code re-organization functional testing

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#140]
cQube code re-organization installation which includes
1. Azure
2. S3 - pending
3. On-premise

**Comment by devu1454** [comment]
Completed the Azure installation.

**Comment by devu1454** [comment]
Below are the Azure installation defects 

1.Validation is not happening for below config elements in the config.yml file  **(Major)**

    read_only_db_user:                        
    read_only_db_password: 
    
    read_only_db_user: cqube1                        
    read_only_db_password: tibil@123  
    
    system_user_name: ubu
    
    storage_type: azur 
    
    local_ipv4_address: 172.31.28.228  
    
    session_timeout: 29M 
    
    auth_api: cqub

2.Comment message and Error message is not proper **(Minor)**
   access_type: cor

ie comment message :  # Please enter national or state or core 
    Error message : Error - Please enter either NVSK or VSK or cqube1 for access_type

3. Datasource name is not proper while installation **(Minor)**
   Validating the Datasource_config.yml file...

4.Tried to install the cQube without filling the azure_container_config.yml **(Minor)**
   Issue : Error message is not proper  

5.Validation is not happening for below config elements in the azure_container_config.yml file  **(Major)**
   azure_account_name: invalid acc_name
   azure_account_key: invalid acc_key

6.Order of displaying the error messages is not matching with config file **(Minor)**

  Validating the config file...
  Error - in system_user_name. Unable to get the value. Please check.
  Error - in access_type. Unable to get the value. Please check.
  Error - in storage_type. Unable to get the value. Please check.
  Error - in mode_of_installation. Unable to get the value. Please check.
  Error - in api_endpoint. Unable to get the value. Please check.
  Error - in local_ipv4_address. Unable to get the value. Please check.
  Error - in vpn_local_ipv4_address. Unable to get the value. Please check.
  Error - in proxy_host. Unable to get the value. Please check.
  Checking for Postgres ...
  Error - in db_password. Unable to get the value. Please check.
  Error - in keycloak_adm_passwd. Unable to get the value. Please check.
  Error - in keycloak_adm_user. Unable to get the value. Please check.
  Error - in static_datasource. Unable to get the value. Please check.
  Error - in management. Unable to get the value. Please check.
  Error - in theme. Unable to get the value. Please check.
  Error - in slab1. Unable to get the value. Please check.
  Error - in slab2. Unable to get the value. Please check.
  Error - in slab3. Unable to get the value. Please check.
  Error - in slab4. Unable to get the value. Please check.
  Error - in auth_api. Unable to get the value. Please check.

7.One step installation failed at TASK [angular_config : Configure the environment.ts]  **(Blocker)**

8.Invalid components in processor group **(Blocker)**
  1.cQube_data_storage = 63
  2.transaction_and_aggregation = 1

**Comment by devu1454** [comment]
Completed the Functional testing of On-premise installation.

**Below are the Azure installation defects**

1.Tried to install the cQube without filling the local_storage_config.yml **(Minor )**
    Issue : Error message is not proper.
    ex : Error - input_directory directory owner not matchiing.
           Error - output_directory directory owner not matchiing.
           Error - emission_directory directory owner not matchiing.

2.One step installation failed at TASK [angular_config : Configure the environment.ts] **(Blocker)**

3.Invalid components in processor group **(Blocker)**
   1.cQube_data_storage = 63
   2.transaction_and_aggregation = 1

**Comment by devu1454** [comment]
Completed the Functional testing of S3 installation.

**Below are the S3 installation defects**

1. Installation is failed at validation part **(Blocker)**
