### ISSUE TITLE
Integration Testing for Admin Dashboard

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#141]
Rounting the Admin dashboard without vpn. 
Currently in cQube 1 it is routing through vpn and admin user only able to access the admin dash. 

Development is required in the Visualization app side and Devops side

**Comment by asifbasha61** [comment]
Routing admin console without using VPN.
Configuring routing in angular side and changes in ansible code according to the UI script.
Changing the configuration of nginx to route admin page by disabling vpn and routing it through nginx.
Development is finished and code pushed to github.

**Comment by Sharathnaik38** [comment]
Invalid
