### ISSUE TITLE
Analyze the State Authentication API with open API

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#145]
Below are the analyzed points:

- Gone through the state and key cloak API flow on cQube architecture.
- Gone through the State Authentication API with open swagger documentation.

**Comment by bommalla** [comment]
1.I understood the state and keycloak API flow on cQube architecture.
2.I understood the State Authentication API with open swagger documentation.

**Comment by RNarmatha** [comment]
Completed
