### ISSUE TITLE
Develop the De-coupling Authentication with Key Cloak

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#146]
Authentication and Authorization adding to cQube 4
where the new development is required? (whether it is Ingestion or processing or configuration or visualization app)
Visualization app

**Comment by Sharathnaik38** [comment]
Added nodejs server for Authentication as decoupled.
Added swagger spec for Authentication.
Added Keycloak Node.js Adapter (keycloak-connect).
Added login functionality using keycloack admin api to generate token for the user.
Need to add login page and connect with login api

**Comment by Sharathnaik38** [comment]
Added login functionality using keycloack admin api to generate token for the user.
Added login page and connect with login api.
Need to do integration test

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
This is related to cQube v4.0 alpha
