### ISSUE TITLE
Preparation of functional testcases for Installation, Ingestion and processing configuration, Visualization, Authentication and Monitoring

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#148]
Writing the functional testcases for the Installation , Ingestion and Processing configuration, Visualization, Authentication and Monitoring for the Following areas.

Azure
AWS
On- Premise
These test cases for the requirements of cQube 4.0

**Comment by devu1454** [comment]
Preparation of functional test cases for installation.

**Comment by devu1454** [comment]
Completed the functional test cases for azure installation and sent for the review.

**Comment by devu1454** [comment]
Completed the functional test cases for On-premise and S3 installation and sent for the review

**Comment by RNarmatha** [comment]
Testcases are completed and it is repo
