### ISSUE TITLE
working on the backend config spec preparation

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#151]
CSV configuration file spec to be created for the Ingestion and processing. 

The file should contains the DB table details, Metrics and Dimensions.

**Comment by SreenivasNimmagadda** [comment]
The file is created and shared in the slack. 

Here is the link of the CSV file which is having the configurations. 
https://docs.google.com/spreadsheets/d/1d3qR656GbOAY98ZYPC86HDpZpXiuG1V13i5wsojTaq8/edit#gid=1725882301

**Comment by RNarmatha** [comment]
This is documentation preparation  and it is completed
