### ISSUE TITLE
Architecture change in the Ingestion

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#152]
Architecture has to be updated according to the below discussed points with Suren & Alok.

1. Any data from the external system to the the cQube to be happened through the Ingestion API. 
2. Diksha Connector information.

**Comment by SreenivasNimmagadda** [comment]
Architecture diagram was updated. Below is the updated image of the cqube 4.x architecture. 



![Image](https://user-images.githubusercontent.com/61133774/190074814-140e8771-0fa1-42dc-ab76-f788c603af7e.png)

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
cQube Architecture was changed. 

The points which is mentioned as description can be considered in the Road Map

**Comment by RNarmatha** [comment]
Currention Data ingestion happens through ingestion API
