### ISSUE TITLE
Prepare spec for visualization app configuration file

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#157]

**Comment by pandutibil** [comment]
Created sample configuration file and discussed same with the team. After discussion team identified gaps and more usecases in the configuration file. Still need more and more discussions with the team to finalize on the configuration file.

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and needs to be analysed.

**Comment by RNarmatha** [comment]
This is related to cQube v4.1 beta
