### ISSUE TITLE
Uninstall option for cQube application

### ISSUE THREAD

**Issue by SreenivasNimmagadda** [Sunbird-cQube/community#16]
**Purpose of the Feature**
As of now cQube is not having the uninstall option. If user wanted to uninstall the cQube then the use has to manually delete the cQube working folders and manually uninstall the software like python, java, PostgreSQL.. etc. 

It is good to have the uninstall option perform the above actions as automatic with one command

**Steps required while doing the uninstall**

- Delete the cQube installed folders
- Remove the cQube cloned code
- Drop the cQube tables from the data base Or Uninstall the PostgreSQL
- Uninstall Java, Python, Grafana
- Clear the NIFI templates

**Effected Code Areas**
Ansible code has to developed.

**Comment by RNarmatha** [comment]
@ananya-jain1 and @htvenkatesh , Please look into it

**Comment by RNarmatha** [comment]
This to be considered as a part of road map
