### ISSUE TITLE
Update Master file as per the UDISE data excel sheet in the Raw data folder

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#160]
The states and district codes are entered wrongly in the Master file which is the Raw data folder. So, updated the file with correct codes as received from Abhineet.

This file is required to visualize the reports.

**Comment by RNarmatha** [comment]
@ananya-jain1  Request to take a look

**Comment by RNarmatha** [comment]
This is related to cQube 3.7
