### ISSUE TITLE
Diksha ETB - Summary rollup data set to get for one day data [Day before yesterday's data from current date]

### ISSUE THREAD

**Issue by SreenivasNimmagadda** [Sunbird-cQube/community#17]
**Purpose of the Feature**
As of now cQube is getting 6 days of data from Disha in each API call. As API call will be triggered every day, Not required to get the past 6 data as it is duplicate data. 

So, the proposed changes is for ETB - Summary rollup data set API call should be happened for one day that should be Day before yesterday's data from current date.

**Described the solution**
Need to alter the API call and set to get the data for one day from NIFI processor.

**Effected code areas **
Nifi - Update attribute processor (From and To dates has to be changed)

**Comment by krishnakr6** [comment]
Updated the data flow.
