### ISSUE TITLE
Diksha ETB - Summary rollup data set to get for older date data

### ISSUE THREAD

**Issue by SreenivasNimmagadda** [Sunbird-cQube/community#18]
**Purpose of the Feature**
The current cQube is not having the facility to get the older days data from the API call. 
As an additional feature, This feature is proposed 

**Described Solution**
The admin should be provide an option to select the From date & To date
Add the selected date as parameter when the cQube is initiating the API.

**Effected code areas**
Nifi - Update Attribute processor - Pass the date as dynamic which is selected by Admin.
Python code - Develop the functionality to update the NIFI processor properties with the selected dates.
UI code - Have to add the date selection functionality

**Note: - **Have to check with the Diksha system the below points 
- How many max past days can be get through the API

**Comment by krishnakr6** [comment]
updated the NiFi data flow.
wrote python code to modify the nifi processor property based the user input [ summary rollup custom dates ]
