### ISSUE TITLE
Merge the cQube 1 Nodejs code base  to cQube-4

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#183]
Merging the cQube 1 Nodejs code base to cQube-4.

The desired result should be that the UI is able to read the api and display the charts.

**Comment by Sharathnaik38** [comment]
Merged cQube v1 nodejs code base to cQube v4. Now Able to connect the API with UI and render the Chart.

**Comment by RNarmatha** [comment]
Please mention who has to review this ticket

**Comment by RNarmatha** [comment]
Completed
