### ISSUE TITLE
Removing Highcharts dependency

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#191]

**Comment by pandutibil** [comment]
As Highcharts is not an open source chart library, need to replace the highcharts with chart.js using sunbird dashlet library which has already chart.js library and it is an open source library.

Replace the following chart reports with Dashlet across the application
- [ ] Bar Chart 
- [ ] Stacked Bar Chart
- [ ] Pie Chart
- [ ] Area Chart
- [ ] Line Chart
- [ ] Multi Bar Chart

**Comment by pandutibil** [comment]
Only heart chart implementation is pending other than that removed the highchart dependencies accross the app

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
This ticket was commented by Pandu
