### ISSUE TITLE
Ansible changes according to the UI changes. Nginx routes needs to be changed if required.

### ISSUE THREAD

**Issue by asifbasha61** [Sunbird-cQube/community#193]
1. Develop Ansible script to run Authentication API on the separate port.
2. Configuring the routs in nginx for authentication API.

**Comment by RNarmatha** [comment]
- [ ]Test

**Comment by asifbasha61** [comment]
-[ ] installation and up gradation flow discussion and working on changes if needs to be done.

**Comment by asifbasha61** [comment]
- [ ] Add the ansible script for authentication and core api processes

**Comment by asifbasha61** [comment]
- [ ] Add aggregated_data_processor_group flow in ansible. ( Nifi processor group deployment)

**Comment by asifbasha61** [comment]
Developed authentication and core api process configuration code in ansible and yet to be tested. ( Need UI developer help to review the environmental variables) 
Added aggregated_data_processor_group in the ansible flow. Yet to be tested.

**Comment by asifbasha61** [comment]
Environmental variables to be loaded in respective node process has been reviewed by sharath.
Code is yet to move to github.

**Comment by RNarmatha** [comment]
Development done
