### ISSUE TITLE
Testing requirement understanding for the cQube_4.0

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#195]
Requirement understanding for 
1.Installation
2.Ingestion & Input Data
3.Processing & Output Data
4.Visualization

**Comment by devu1454** [comment]
Completed the understanding of ingestion & input data, processing & output data and visualization

**Comment by devu1454** [comment]
Completed the requirement understanding for Installation

**Comment by RNarmatha** [comment]
Review is completed

**Comment by devu1454** [comment]
[Requirement's understanding for cQube_4.0 Document](https://docs.google.com/spreadsheets/d/1eSot7x7Y4ACOZ6G32jFKIRN0zvJFJQUFha6R5QEWnFk/edit#gid=689917785)
