### ISSUE TITLE
Functional Testcases for Installation,Ingestion & Input Data,Processing & Output Data

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#196]
1. Testcases for Installation

- [x] Azure 
- [x] s3
- [x] On-premise

2. Testcases for upgradation

- [x] From 3.7 to 4.0(s3)
- [x] From 3.7 to 4.0 (On-premise)

3. Ingestion & Input Data
- [x] Azure
- [x] s3
- [x] On-premise

4. Processing & Output Data 
- [x] Azure
- [x] s3
- [x] On-premise

**Comment by devu1454** [comment]
Completed the Azure, s3 and On-premise installation testcases and sent for the review.

**Comment by RNarmatha** [comment]
Reviewed . Need to add few more test cases

**Comment by RNarmatha** [comment]
Completed
