### ISSUE TITLE
Add Student Infrastructure datasource into a cQube 4 common dashboard along with cQube-2 dataSources.

### ISSUE THREAD

**Issue by Sharathnaik38** [Sunbird-cQube/community#197]
Test-1: To be able to see the student Infrastructure screen with  new styling.
Test-2: To integrate the node api’s from node which will be added by Sharath.

**Comment by FaizanMohammed326** [comment]
Infra Map completed as of yesterday, will take up the remaining 2 reports today.

**Comment by Sharathnaik38** [comment]
- [ ]  Infra map report

- [ ]  Infra composite report

- [ ]  Udise report

**Comment by RNarmatha** [comment]
Please mention who has to review
