### ISSUE TITLE
Replace the bar chart reports with dashlet and chart.js

### ISSUE THREAD

**Issue by pandutibil** [Sunbird-cQube/community#199]
Replace the bar chart reports with dashlet and chart.js across the app

**Comment by pandutibil** [comment]
While replacing the bar chart faced some challenges like setting height for the chart, various chart options. Finally, replaced the bar chart report with dashlet across cQube 2.0, but working on replacement of bar chart reports in cQube 1.0.

**Comment by RNarmatha** [comment]
Review with Sharath
