### ISSUE TITLE
GPS of learning- ETB

### ISSUE THREAD

**Issue by SreenivasNimmagadda** [Sunbird-cQube/community#20]
**Purpose of the Feature**
The dashboard provides details on the total content plays, total time spent and average time spent for Energized Textbooks (ETB) by location of all districts of the State.

**Described Solution**
It is a Map report which can describe the metrics with the dots pointed at the districts on the state map. Below are the required actions in the reports

- One dot should be represented one district on the map
- Dots should be represented in 5 green color gradient (From light green to Dark Green).
- Legend should be given at the right side of the Map with 5 dividend slots.
- Report should have a selection option of "total content plays", "total time spent" and "average time spent" 
- The metrics, Dot colors and the legend values should be changed according to the selection.
- Others (Out of expected users plays) should be represented at the right side of the Map, Below the legends.
- Footer should contain the state level metrics.

**Effected code areas**

1. New PostgreSQL Queries should be developed for "total content plays", "total time spent" and "average time spent" 
2. New NIFI processors to be created for the above queries execution
3. New Node API should be written to fetch the output files
4. Angular code should be developed for the Map representation for the created metrics.

**Comment by krishnakr6** [comment]
Updated the data flow and JOLT Transformation.

**Comment by JalajaTR** [comment]
Added the queries to calculate "total content plays", "total time spent" and "average time spent".
