### ISSUE TITLE
Development of Data Ingestion API

### ISSUE THREAD

**Issue by Shoaib15khan** [Sunbird-cQube/community#200]
Development of Python code to upload files to amazon s3 bucket and azure using libcloud and copy files to local directory .

**Comment by Shoaib15khan** [comment]
Libcloud is not having the functionality of presigned url for AWS and Azure  blob storage.
Libcloud is not applicable for local file transfer.
we are prefering to work on presigned url for azure  and on-premise without use of libcloud.

**Comment by RNarmatha** [comment]
Completed
