### ISSUE TITLE
Configurable names for specific dashboard and data source built-in cQube v4.0

### ISSUE THREAD

**Issue by surendrasinghs** [Sunbird-cQube/community#202]
cQube is a digital public good for diverse use cases across sectors. Towards that cQube should provide generalised capabilities and not have any specific sector/country/adopter terminology. Even the data sources and dashboards that are built-in and available out-of-the-box, they must be generalised for a wider usage.

Hence, Can the names of dashboards and data sources which are built-in v4.0 be generalised? Keeping in mind that the names will be configured by each adopter to suit their specific context.

These names need to be updated with specific proper nouns when an adopter is configuring and deploying to production. Please elaborate (through documentation) how an adopter can update these names.

- [ ] 1. Analyse if it can be configurable in v4.0
- [ ] 2. Propose Design for enabling configuration
- [ ] 3. Development as per the design

**Comment by satendrapalsingh** [comment]
<adding more context from the Backlog refinement discussions>

Any proper nouns (NISHTHA, DIKSHA, etc.) used in the code should be replaced with generic terminology across ingestion, processing, and visualization. When deployed specific terms to be given.

**Assumptions**:
- Node source code and angular we will make variables names generic ( not referring to proper nouns) but on the frontend screen proper nouns will be displayed.
- The proper nouns will be defined in config file, and source code should have generic names.

**Comment by RNarmatha** [comment]
This Issue will be taken up in cQube v5.0

**Comment by RNarmatha** [comment]
It is configurable but not implemented. Need to be discussed in detail

**Comment by RNarmatha** [comment]
Added into the Backlog
