### ISSUE TITLE
Preparation of test cases for Attendance and CRC Visits Dashboard Reports

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#203]
Prepare the test cases for Attendance and Education official Reports 
Education Official
Attendance 
- Student Attendance 
- Teacher Attendance

**Comment by chetandg123** [comment]
Preparation of test cases is completed for the below reports 
Attendance
-Student Attendance - Completed
-Teacher Attendance - Completed
CRC Visits - Completed 
and all those test cases are sent to review

**Comment by RNarmatha** [comment]
Test cases are under review

**Comment by RNarmatha** [comment]
There are some modifications that need to be taken care

**Comment by chetandg123** [comment]
Completed with modifications
