### ISSUE TITLE
Preparation of test cases for School Infrastructure and Student Performance

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#204]
Preparation of test cases for below reports
School Infrastructure
 - Infrastructure access by location
 - infrastructure composite report
 - Udise Report
Student Performance
 - SAT Map Report
 - SAT Heat Chart
 - PAT Map Report
 - PAT Heat Chart
 - PAT Lo Report

**Comment by manjulacg** [comment]
Completed the preparation of test cases for the below reports 
School Infrastructure - Completed 

Student Performance - 
SAT Map - Completed
SAT Heat chart - Completed 

PAT Map - In progress 
PAT HeatChart - In progress
PAT Lo table - In progress

**Comment by manjulacg** [comment]
Test cases under review.

**Comment by RNarmatha** [comment]
There are some modifications that need to be taken care

**Comment by manjulacg** [comment]
Modifications are completed
