### ISSUE TITLE
Test cases for cQube_4.0(Teacher training, Nutrition and health and School Registry)

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#205]
Modifying Test cases for cQube_4.0
--Teacher Training
    Implementation status
    Courses and medium status
    % against potential base
    District wise status
    Course wise status
--Nutrition and health
     Progress status
--school registry
    District wise performance
    Correlation

**Comment by TanushreeSG** [comment]
Completed modifying test cases for Login page,Teacher training,Nutrition and health and school registry program

**Comment by RNarmatha** [comment]
Modified test cases are under review

**Comment by RNarmatha** [comment]
There are some modifications that need to be taken care

**Comment by TanushreeSG** [comment]
Modifications are completed
