### ISSUE TITLE
Add Student Attendance datasource to cQube v4

### ISSUE THREAD

**Issue by Sharathnaik38** [Sunbird-cQube/community#207]

**Comment by FaizanMohammed326** [comment]
Merge the cQube v1 Attendance datasouce in to cQube v4 and change the look and feel according to cQube 4 Dashboard.

Expected outcome:-
To be able to see the Attendance screens with new styling

- [ ] Student Attendance
- [ ] Teacher Attendance
- [ ] Student Attendance Trends
