### ISSUE TITLE
Heartbeat of the Nation Learning

### ISSUE THREAD

**Issue by SreenivasNimmagadda** [Sunbird-cQube/community#21]
**Purpose of the Feature**
The dashboard provides a macro overview of the total content plays over the last two academic years for the state

**Described Solution**
It is a Wave Chart report which can describe the metrics with the X axis as Months of previous and current academic years & Y axis as Number of total content plays.

- One dot should be represented one month on the report with total content plays metric.
- Report should have a selection option of Districts.
- Download button should be created to download the aggregated metrics.

**Effected code areas**

1. New PostgreSQL Queries should be developed for "total content plays"
2. New NIFI processors to be created for the above queries execution
3. New Node API should be written to fetch the output files
4. Angular code should be developed for the wave chart representation for the created metrics.

**Comment by krishnakr6** [comment]
Updated the data flow and JOLT Transformation to support Heartbeat of the Nation Learning report.

**Comment by JalajaTR** [comment]
Added the queries to calculate the total content plays monthwise.
