### ISSUE TITLE
Functional Testing of Installation,Ingestion & Input Data,Processing & Output Data,Visualization

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#216]
1. Checking positive and negative scenario's for cQube_4.0 Installation(Manual Tc's)
- [x] Azure (Devaraja)
- [x] S3 (Inchara)
- [x]  On-premise (Chetan)

2. Checking positive and negative scenario's for Ingestion (Manual Tc's)
- [ ] Azure (Devaraja)
- [ ] S3 (Inchara)
- [ ]  On-premise (Chetan)

3.Checking positive and negative scenario's Data Processing(Manual Tc's)
- [ ] Azure (Devaraja)
- [ ] S3 (Inchara)
- [ ]  On-premise (Chetan)

4.Checking positive and negative scenario's Output data (Manual Tc's)
- [ ] Azure (Devaraja)
- [ ] S3 (Inchara)
- [ ]  On-premise (Chetan)

5.Checking the indepth(Positive & Negative) functionalities for visualization(Manual Tc's)
- [ ] Azure (Devaraja)
- [ ] S3 (Inchara)
- [ ]  On-premise (Chetan)

6.Upgradation From 3.7-to 4.0 (S3) (Manual Tc's)(Manjula)
- [ ] Installation of 3.7
- [ ] Upgradation to 4.0
- [ ] Ingestion & Processing of data
- [ ] Visualization

7.Upgradation From 3.7-to 4.0 (On-premise) (Manual Tc's)(Tanushree)
- [ ] Installation of 3.7
- [ ] Upgradation to 4.0
- [ ] Ingestion & Processing of data
- [ ] Visualization

**Comment by devu1454** [comment]
Functional testing of azure,s3 and on-premise is completed. Found the defects.
https://github.com/Sunbird-cQube/community/issues/289

**Comment by RNarmatha** [comment]
Duplicate
