### ISSUE TITLE
System Testing of Installation,Ingestion & Input Data,Processing & Output Data,Visualization

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#219]
1. Checking the end-to-end cQube_4.0 Installation(Manual Tc's)
- [ ] Azure (Devaraja)
- [ ] S3 (Inchara)
- [ ]  On-premise (Chetan)

2. Checking end-to-end for Ingestion (Manual Tc's)
- [ ] Azure (Devaraja)
- [ ] S3 (Inchara)
- [ ]  On-premise (Chetan)

3.Checking end-to-end Data Processing(Manual Tc's)
- [ ] Azure (Devaraja)
- [ ] S3 (Inchara)
- [ ]  On-premise (Chetan)

4.Checking end-to-end Output data (Manual Tc's)
- [ ] Azure (Devaraja)
- [ ] S3 (Inchara)
- [ ]  On-premise (Chetan)

5.Checking the all the functionalities for visualization(Manual Tc's)
- [ ] Azure (Devaraja)
- [ ] S3 (Inchara)
- [ ]  On-premise (Chetan)

6.Upgradation From 3.7-to 4.0 (S3) (Manual Tc's)(Manjula)
- [ ] Installation of 3.7
- [ ] Upgradation to 4.0
- [ ] Ingestion & Processing of data
- [ ] Visualization

7.Upgradation From 3.7-to 4.0 (On-premise) (Manual Tc's)(Tanushree)
- [ ] Installation of 3.7
- [ ] Upgradation to 4.0
- [ ] Ingestion & Processing of data
- [ ] Visualization

**Comment by RNarmatha** [comment]
The test case documentation is up in the repository.
