### ISSUE TITLE
User Onboarding Report

### ISSUE THREAD

**Issue by SreenivasNimmagadda** [Sunbird-cQube/community#22]
**Purpose of the Feature**
The dashboards provides insights on the user onboarding progress across various TPD courses for the state over time

**Described Solution**
It is a line chart report which can describe the metrics with the X axis as Dates between the start date and end date of program or Course & Y axis as number of enrollments 

- One dot should be represented one date between the start date and end date of Program or Course.
- X-Axis should represent 30 dots 
- If the courses are having 60 days span then the dates should be alternative, If the course is having 90 days duration then the dates should be skip of 3 days, If the course is having more then 90 days duration then the dates should be per week.
- Report should have a selection options of Program and Course
- After selecting the Program & Course the District, Block & Cluster select boxes should be enabled
- Download button should be created to download the aggregated metrics.

**Effected code areas**

1. New PostgreSQL Queries should be developed for Expected enrollments & Net enrollments over the start date and end date.
2. New NIFI processors to be created for the above queries execution
3. New Node API should be written to fetch the output files
4. Angular code should be developed for the line chart representation for the created metrics.

**Comment by krishnakr6** [comment]
Updated the data flow and JOLT Transformation which provides the output Json data for User on boarding report

**Comment by JalajaTR** [comment]
Added the queries for Expected enrollments & Net enrollments over the start date and end date day wise.
