### ISSUE TITLE
Preparation of test cases for Courses

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#221]
Modifying test cases for Courses
-Usage by course
-Usage by course content
-Course progress
-User progress
-GPS of learning courses
-User Engagement
-User Onboarding

**Comment by Inchara98** [comment]
Test cases completed for
--Usage by course
--Usage by course content
--Course Progress

**Comment by RNarmatha** [comment]
There are some modifications that need to be taken care

**Comment by Inchara98** [comment]
Modifications are done .
