### ISSUE TITLE
Preparation of test cases for Composite report across metrics and progress card

### ISSUE THREAD

**Issue by manjulacg** [Sunbird-cQube/community#222]
Preparation of test cases for below reports
- Composite report across metrics
- Progress card

**Comment by manjulacg** [comment]
Completed Preparing test cases for below reports

- [ ]  Composite report across metrics
- [ ] Progress card

**Comment by manjulacg** [comment]
Test cases under review

**Comment by RNarmatha** [comment]
There are some modifications that need to be taken care

**Comment by manjulacg** [comment]
Modifications are completed
