### ISSUE TITLE
Preparation of Test cases for DIAL Resource Usage

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#223]
Modifying Test cases for DIAL Resource Usage
 -Usage by Textbook
 -Usage by Textbook content
 -GPS of learning
 -Usage per capita
 -Heartbeat of the nation learning

**Comment by TanushreeSG** [comment]
Completed test case for below reports
-Usage by Textbook 
-Usage by Textbook content

**Comment by RNarmatha** [comment]
There are some modifications that need to be taken care

**Comment by TanushreeSG** [comment]
Modifications are completed
