### ISSUE TITLE
Preparation of test cases for Exception List Dashboard

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#225]
Prepare the functional test cases for the below exception list reports
- Periodic Assessment Test Exception
- Semester Assessment Test Exception
- Download Exception List
- Student Attendance Exception Report
- Teacher Attendance Exception Report

**Comment by chetandg123** [comment]
- [ ] Periodic Assessment Test Exception

- [ ] Semester Assessment Test Exception

- [ ] Download Exception List

**Comment by chetandg123** [comment]
Completed preparation of test cases for 

- [ ] Student Attendance Exception Report

**Comment by chetandg123** [comment]
@RNarmatha this task completed please review the test cases let me know if any changes are required

**Comment by RNarmatha** [comment]
There are some modifications that need to be taken care

**Comment by chetandg123** [comment]
Done with modifications
