### ISSUE TITLE
Program level - course progress Report

### ISSUE THREAD

**Issue by SreenivasNimmagadda** [Sunbird-cQube/community#23]
**Purpose of the Feature**
The dashboard provides insights on user onboarding, completion and certification across various TPD courses for the state.

**Described Solution**
It is a multi bar chart report which can describe the metrics with the 
For state level report, X axis as percentage of  Expected user enrollments, user onboarding, completion & Y axis as District names.
For the lower levels, X axis as Number of users onboarding, completion and Certificate & Y axis as next level location names.

- On the report loading all the districts information should be provided with 3 bars such as Expected user enrollments, user onboarding and completion
- Report should have a selection option of Time period, Program, Course and District
- If user selects the only Program, All the districts information should be provided with 3 bars such as Expected user enrollments, user onboarding and completion
- If user selects the only Course, All the districts information should be provided with 3 bars such as users onboarding, completion and certificates.
- Users may select Program & District, Course & District and same combination will be applicable for the lower levels also.
- Download button should be created to download the aggregated metrics.

**Effected code areas**

1. New PostgreSQL Queries should be developed for Expected user enrollments, user onboarding, completions and certificates.
2. New NIFI processors to be created for the above queries execution
3. New Node API should be written to fetch the output files
4. Angular code should be developed for the multi bar chart representation for the created metrics.

**Comment by krishnakr6** [comment]
Updated the data flow and JOLT Transformation.
