### ISSUE TITLE
Preparation Test Cases for Trend Charts ( Student Attendance & Semester ) and other digital learning metrics

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#231]
Preparation of Functional TestCases for the below reports
Other Digital Learning Metrics
Trend charts 
- Student attendance trends
- Semester trends

**Comment by chetandg123** [comment]
Completed preparation test cases for the below reports 
Other Digital Learning Metrics
Trend charts

- [ ] Other Digital Learning Metric

- [ ] Student attendance trends

- [ ] Semester trends

**Comment by RNarmatha** [comment]
Modifications are completed
