### ISSUE TITLE
Making an documentation for each datasource and each query type-Jolt spec

### ISSUE THREAD

**Issue by padmanabha1234** [Sunbird-cQube/community#232]
This documentation will be usefull for generalizing the json structure

**Comment by padmanabha1234** [comment]
Documentation is completed.
I have done Data_replay, infra, pat, sat, meta datasources json structure.

**Comment by murali003** [comment]
I have done Attendance, Composite, telemetry, crc, teacher attendance,udise and diksha datasources json structure.

**Comment by padmanabha1234** [comment]
krishna, sharath has to review the document.
