### ISSUE TITLE
Design for generalizing the data processing

### ISSUE THREAD

**Issue by padmanabha1234** [Sunbird-cQube/community#237]
Designing the generalised spec for all data sources.

**Comment by RNarmatha** [comment]
by monday we have first draft of this design

**Comment by krishnakr6** [comment]
Data processing configuration design draft

https://docs.google.com/document/d/1f1ejbOeZCmrur6Rb7ZmGpV4H9FJ1q91BgB0hktVnjMM/edit?usp=sharing

**Comment by RNarmatha** [comment]
Duplicate ticket
