### ISSUE TITLE
Create a heat map component in sunbird dashlet using apex-charts library

### ISSUE THREAD

**Issue by pandutibil** [Sunbird-cQube/community#239]
As there is no heat map chart available in sunbird dashlet today. Let's create a heat map component in sunbird dashlet using apex-charts library.

Here is the link to apex charts library: [https://apexcharts.com/docs/installation/#](https://apexcharts.com/docs/installation/#)

Here is the screen shot of sample report with heat map

![Image](https://user-images.githubusercontent.com/76088803/191920591-13cb1167-1070-43fa-9716-1e9766818e9b.png)

Note: Following branch contains latest code of dashlet

v14_Migration_Branch

**Comment by RNarmatha** [comment]
Santhosh's team has to take up this task

**Comment by RNarmatha** [comment]
Completed
