### ISSUE TITLE
User Engagement

### ISSUE THREAD

**Issue by SreenivasNimmagadda** [Sunbird-cQube/community#24]
**Purpose of the Feature**
The dashboard provides insights on user engagement for various TPD courses for the state.

**Described Solution**
It is a horizontal bar chart report which can describe the metrics with the X axis as Average time spent & Y axis as course names

- On the report loading all the courses state level information should be provided with a bar which represents an average time spent on the course.
- Report should have a selection option of Districts
- Download button should be created to download the aggregated metrics.

**Effected code areas**

1. New PostgreSQL Queries should be developed for average time spent on the course.
2. New NIFI processors to be created for the above queries execution
3. New Node API should be written to fetch the output files
4. Angular code should be developed for the horizontal bar chart representation for the created metrics.

**Comment by krishnakr6** [comment]
Updated the data flow and JOLT Transformation to support User Engagement report.

**Comment by JalajaTR** [comment]
Written and added the queries to calculate the average time spent on the course.
