### ISSUE TITLE
Create a gauge chart component in sunbird dashlet using chartjs-gauge library

### ISSUE THREAD

**Issue by pandutibil** [Sunbird-cQube/community#240]
As there is no gauge chart available in sunbird dashlet today. Let's create a gauge chart component in sunbird dashlet using apex-charts library.

Here is the link to chartjs-gauge library: [https://github.com/haiiaaa/chartjs-gauge](https://github.com/haiiaaa/chartjs-gauge)

Here is the screen shot of sample report with gauge chart

![Image](https://user-images.githubusercontent.com/76088803/191920827-9b710a85-7bd6-4701-a220-182694352398.png)

Note: Following branch contains latest code of dashlet

v14_Migration_Branch

**Comment by RNarmatha** [comment]
Completed
