### ISSUE TITLE
Testing of one step cQube_4.0 Installation(On-premise)

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#245]
Test the cQube-4.0 On-premise Installation

**Comment by chetandg123** [comment]
Got blocker defects while doing the installation and assigned to the Devops team 
Defect id - D011

**Comment by chetandg123** [comment]
While doing the installation of on-premise local got blocker defect at Task: Building at client-side 
Defect id - D014

**Comment by chetandg123** [comment]
Blocker defects of On-premise installation are resolved, completed the testing of the installation process and will doing main_metrics.csv data is not created JSON file in the output folder
