### ISSUE TITLE
Usage per capita

### ISSUE THREAD

**Issue by SreenivasNimmagadda** [Sunbird-cQube/community#25]
**Purpose of the Feature**
The dashboard provides the total content play metric over last academic year and current academic year across various districts for the state normalized using the total eligible population (Total number of students and teachers) for the respective district.

**Described Solution**
It is a Map report which can describe the metrics with the dots pointed at the districts on the state map. Below are the required actions in the reports

- One dot should be represented one district on the map
- Dots should be represented in 3 different colors  (Green, Blue and Red).
- Green for the Upper Quartile, Blue for the inter Quartile and red for the bottom Quartile.
- The capita formula should be applied to calculate the Per Capita.
![image](https://user-images.githubusercontent.com/61133774/147327356-34fe72c9-7b8d-4bb7-be56-281e3a4e4aaa.png)
- Legend should be given at the right side of the Map with 3 color slots.
- The metrics, Dot colors and the legend values should be represented based on the metrics
- Others (Out of expected users plays) should be represented at the right side of the Map, Below the legends.
- Footer should contain the state level metrics.

**Effected code areas**

1. New PostgreSQL Queries should be developed for the Quartiles
2. New NIFI processors to be created for the above queries execution
3. New Node API should be written to fetch the output files
4. Angular code should be developed for the Map representation for the created metrics.

**Comment by krishnakr6** [comment]
Updated the data flow and JOLT Transformation to support Usage per capita report.

**Comment by JalajaTR** [comment]
Written and added the queries to calculate the per capita and quartiles.
