### ISSUE TITLE
Add Telemetry datasource to cQube V4

### ISSUE THREAD

**Issue by FaizanMohammed326** [Sunbird-cQube/community#254]
Merge the cQube v1 Telemetrty datasouce in to cQube v4 and change the look and feel according to cQube 4 Dashboard.

Expected outcome:-
To be able to see the Telemetry Report screen with new styling.

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
This is related to cQube v4.1 beta
