### ISSUE TITLE
Upgradation from 3.7 to 4.0 (Smoke-Testing)(On-premise)

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#259]
Testing of upgradation from 3.7 to 4.0 and configuration of cQube_4.0

**Comment by manjulacg** [comment]
Upgradation of cQube 3.7 to cQube-4.0 is completed for onpremise

**Comment by manjulacg** [comment]
Completed with upgradtion from cqube 3.7 to Cqube 4.0

**Comment by manjulacg** [comment]
Completed the smoke testing of cQube 4.0 visualization reports from courses to Textbook distribution and got the defects and updated in the defect list.
[Defect List](https://docs.google.com/spreadsheets/d/1RyXRNQx0O6mlgx8RN6_c1WkJNwxSxra0yzcbg4B23Us/edit#gid=1375251216)

**Comment by RNarmatha** [comment]
This is completed and closed
