### ISSUE TITLE
Content Preference

### ISSUE THREAD

**Issue by SreenivasNimmagadda** [Sunbird-cQube/community#26]
**Purpose of the Feature**
The dashboard provides insights on user's preference (as measured by total content play) by content type across districts for the state

**Described Solution**
It is a Pie chart report which can describe the metrics of content usage of Object types such as content, text, video, TV..etc with the partitions in the pie charts.
- List of object types should be represented on the left side of the reports with the different color dots as legends.
- A selection option with "State view" & "State with Districts View" should be given.
- On page load state level view of Pie chart with partitions of object types with specified colors should be displayed on the report.
- On selection of State with Districts View of Pie chart the Districts selection box should be appear with multiple districts selection option.
-  On selection of State with Districts View, The State level Pie chart & Pie charts of all districts levels should be shown side by side.
- On selection of states, The State level Pie chart & Pie charts of selected districts levels should be shown side by side.

**Effected code areas**

1. New PostgreSQL Queries should be developed for Content pay percentage of all available Object types.
2. New NIFI processors to be created for the above queries execution
3. New Node API should be written to fetch the output files
4. Angular code should be developed for the Pie chart representation for the created metrics.

**Comment by krishnakr6** [comment]
Updated the data flow and JOLT Transformation to support content preference report.

**Comment by JalajaTR** [comment]
Written and added the queries to calculate the Content play percentage of all available Object types.
