### ISSUE TITLE
Upgradation from 3.7 to 4.0 (Smoke-Testing)(s3)

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#260]
Testing of upgradation from 3.7 to 4.0 and configuration of cQube_4.0

**Comment by TanushreeSG** [comment]
Upgradation of cQube 3.7 to cQube-4.0 is completed for s3.
-Login is not working with valid credentials(Critical)

**Comment by RNarmatha** [comment]
This issue is completed and closed
