### ISSUE TITLE
Create a gauge chart report using apex charts and replace it in the place of existing gauge chart

### ISSUE THREAD

**Issue by pandutibil** [Sunbird-cQube/community#262]
Create a gauge chart report using apex charts and replace it in the place of existing gauge chart which was developed in the highcharts because it is not a MIT version package.

**Comment by krishnakr6** [comment]
Pull request  number: [321](https://github.com/Sunbird-cQube/cQube_Edu/pull/321)  [368](https://github.com/Sunbird-cQube/cQube_Edu/pull/368)

**Comment by RNarmatha** [comment]
Completed
