### ISSUE TITLE
Smoke Testing Testcases for Installation,Ingestion & Input Data,Processing & Output Data

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#263]
1. Testcases for Installation

- [x] Azure 
- [x] s3
- [x] On-premise

2. Testcases for upgradation

- [x] From 3.7 to 4.0(s3)
- [x] From 3.7 to 4.0 (On-premise)

3. Ingestion & Input Data
- [x] Azure
- [x] s3
- [x] On-premise

4. Processing & Output Data 
- [x] Azure
- [x] s3
- [x] On-premise

**Comment by devu1454** [comment]
Completed the preparation of smoke testing test cases for Installation,Ingestion & Input Data,Processing & Output Data and Sent for the review

**Comment by devu1454** [comment]
[Azure_Testcase's](https://docs.google.com/spreadsheets/d/1c0LOCcNnbomK43iSESkrSMMHX4AHhYq4ng5o5Uxs0zs/edit#gid=2013957484)
[S3_Testcase's](https://docs.google.com/spreadsheets/d/1c0LOCcNnbomK43iSESkrSMMHX4AHhYq4ng5o5Uxs0zs/edit#gid=91439271)
[On-premise_Testcase's](https://docs.google.com/spreadsheets/d/1c0LOCcNnbomK43iSESkrSMMHX4AHhYq4ng5o5Uxs0zs/edit#gid=1742295599)
[S3_Upgradation_Testcase's](https://docs.google.com/spreadsheets/d/1c0LOCcNnbomK43iSESkrSMMHX4AHhYq4ng5o5Uxs0zs/edit#gid=1848731528)
[On-premise_Upgradation_Testcase's](https://docs.google.com/spreadsheets/d/1c0LOCcNnbomK43iSESkrSMMHX4AHhYq4ng5o5Uxs0zs/edit#gid=714444384)

**Comment by RNarmatha** [comment]
Reviewed.
