### ISSUE TITLE
Adding Resposiveness to existing cQube-1 reports

### ISSUE THREAD

**Issue by FaizanMohammed326** [Sunbird-cQube/community#264]
Adding Responsiveness to cQube-1 reports for mobile, tablet, small and large desktops.
DataSources To be completed:

- [x] School Infrastructure
- [ ] Student Performance
- [x] Attendance
- [ ] Courses
- [ ] Dial Resource Access
- [ ] Other Diksha Metrics
- [ ] Education Official
- [x] Composite Report
- [ ] Progress Card
- [x] Exception List
- [x] Telemetry

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and needs to be analysed.

**Comment by Shruti3004** [comment]
Hey @htvenkatesh - please add this in 5.1 plan
