### ISSUE TITLE
Installation stopped at TASK [reference-visualization : copying maps script]

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#272]
Azure, s3, Onpremise Installation stopped at 

TASK [reference-visualization : copying maps script] ***************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find or access '../../reference-visualization-app/maps/HR.json'\nSearched in:\n\t/home/ubuntu/cQube_Edu/devops/ansible/roles/reference-visualization/files/../../reference-visualization-app/maps/HR.json\n\t/home/ubuntu/cQube_Edu/devops/ansible/roles/reference-visualization/../../reference-visualization-app/maps/HR.json\n\t/home/ubuntu/cQube_Edu/devops/ansible/roles/reference-visualization/tasks/files/../../reference-visualization-app/maps/HR.json\n\t/home/ubuntu/cQube_Edu/devops/ansible/roles/reference-visualization/tasks/../../reference-visualization-app/maps/HR.json\n\t/home/ubuntu/cQube_Edu/devops/ansible/files/../../reference-visualization-app/maps/HR.json\n\t/home/ubuntu/cQube_Edu/devops/ansible/../../reference-visualization-app/maps/HR.json on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

**Comment by RNarmatha** [comment]
Closed
