### ISSUE TITLE
Devops and SecOps  discussions

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#277]

**Comment by satendrapalsingh** [comment]
Reviewing the [DevOps & SecOps video recording](https://us06web.zoom.us/rec/play/sMksPfh7Of_99mISlMmljoBaNM9utqE6wZMb3c37Ig-f7Sc5lGZHGqryGeut0_7jHucCxNW0dLroMQ0s.P3z0iKCscRpveMUR?continueMode=true&_x_zm_rtaid=nBCP55M0RLi1MkJFcpgdkA.1664782591154.8187595a77eef7b2c22a6e38985f884f&_x_zm_rhtaid=680)

**Comment by satendrapalsingh** [comment]
Completed review of recording, couple of items enhanced on the sheet (item row #114, item row #115)

**Comment by satendrapalsingh** [comment]
Closed from my end, @krishnakr6 can do a review of the recording if required.

**Comment by RNarmatha** [comment]
Closed
