### ISSUE TITLE
Issue in admin console page

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#280]
After completion of installation, admin console page is not loading(s3)
issue : This demo8cqube.tibilprojects.com page can’t be found

**Comment by asifbasha61** [comment]
Trouble shooting done from networking side where we couldn't find any issue.
Informed UI Team to trouble shoot and resolve the issue from their side.

**Comment by asifbasha61** [comment]
Routed admin console without vpn.
Respective ansible changes are made.

**Comment by Inchara98** [comment]
Admin console is working fine
