### ISSUE TITLE
Integrate new reports in NIPUN BHARAT & DIKSHA

### ISSUE THREAD

**Issue by pandutibil** [Sunbird-cQube/community#286]
Integrate new reports in NIPUN BHARAT & DIKSHA and prepare configuration files are required for data processing and report generation

**Comment by pandutibil** [comment]
New report added in the DIKSHA - ETB. Following is the screenshot of the report.


![Image](https://user-images.githubusercontent.com/76088803/192939251-aa698306-cfbc-43d4-9f74-68bef3bb55fe.png)

**Comment by RNarmatha** [comment]
Completed
