### ISSUE TITLE
Generalized Terminology

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#290]
Please change the program names according to proposed UI labels

![Image](https://user-images.githubusercontent.com/89445054/192754534-32c1cea8-2298-4073-97b2-c4583ca884d1.png)

![Image](https://user-images.githubusercontent.com/89445054/192754572-eb3e4d47-aebb-47ef-9772-a5f557bc0cbe.png)

**Comment by FaizanMohammed326** [comment]
As discussed with Narmatha old terminology to be used. Once the confirmation is given can change to new generalized terminologies.

**Comment by RNarmatha** [comment]
It is Duplicate ticket
