### ISSUE TITLE
On premise local installation - 34 disable components in nifi processors

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#298]
34 disabled components in the on-premise local installation 
aggregate and data processor group -2
data reply transformer 2
validate data source  2
telemetry  - 2
CRC transformer - 2
infra transformer - 2
pat -2
sat - 2
student attendance 2
teacher attendance - 2
static data - 2
udise - 2
diksha transformer - 8

**Comment by RNarmatha** [comment]
Fixed
