### ISSUE TITLE
No Data Found should be displayed after installation of cQube-4.0

### ISSUE THREAD

**Issue by manjulacg** [Sunbird-cQube/community#299]
After installation of cQube-4.0 Click on the 
- Education official
- Composite Report
- Progress card
- Exception List
- Telemetry
- Textbook Distribution
Menu button from the dashboard
Issue: loader is loading instead of showing no data found error message

**Comment by FaizanMohammed326** [comment]
As of now all datasources are working except textbook distribution, Because no data found for textbook distribution in the qa8 output bucket

**Comment by manjulacg** [comment]
![Screenshot from 2022-09-27 17-37-15](https://user-images.githubusercontent.com/100250278/194241094-51471c53-2525-4bd1-ab5b-20803d73cb5c.png)
