### ISSUE TITLE
Dial Resource Usage - Usage By Textbook Smoke Test Defects

### ISSUE THREAD

**Issue by manjulacg** [Sunbird-cQube/community#300]
- [x] After Report heading and about the dashboard information download report button should be displayed not in between

- [ ] Select time range as last 7 and last day  the no data found message not aligned properly

- [x] if last 7 days does not showing any thing on screen then click on time range drop down not able see options only overall is showing

- [x] Download Raw File link and Download Report button are not aligned properly

**Comment by pandutibil** [comment]
1. Issue is not valid. Designed to support multiple devices.

**Comment by manjulacg** [comment]
![Screenshot from 2022-10-06 13-05-18](https://user-images.githubusercontent.com/100250278/194245906-dbfc9f6c-8916-4319-ad7c-13f4d7b6a74a.png)

**Comment by RNarmatha** [comment]
Issue is Fixed
