### ISSUE TITLE
Tooltip issue in School Infrastructure

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#305]
Select
Allahabad district
Chaka block
Chak babura cluster
Mouse hover on the marker
**issue: Half of the tooltip is not visible**

![Image](https://user-images.githubusercontent.com/89445054/192817818-961e0c1e-b68d-4d71-8544-5f217f95d38d.png)

**Comment by pandutibil** [comment]
If the content of the tooltip is too long, then the user have to scroll down the page or zoom out of the map.
