### ISSUE TITLE
Double quote is displaying in the tooltip

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#309]
Select Toilet in x-axis
tap water in y-axis
Agra-District
Bah-Block
Bhadrauli-Cluster
Mouse hover on marker
Issue: Double quote is displaying in the tooltip

![Image](https://user-images.githubusercontent.com/89445054/192835358-76cb77de-8ce9-42fc-bbe3-acb5d2a01aaa.png)

**Comment by pandutibil** [comment]
In the data itself contains "(quote) character. So, need to correct the data by data processing team.

**Comment by RNarmatha** [comment]
Completed
