### ISSUE TITLE
Issue in Heart beat of nation tab

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#332]
Graph is displaying but no no data found message is showing
Tooltip is not displaying for graph

**Comment by manjulacg** [comment]
DIAL Resource Usage- Report on Heartbeat of the Nation Learning

**Comment by manjulacg** [comment]
Retested line chart is not showing tooltip information

**Comment by pandutibil** [comment]
@devu1454 files are missing from the storage container. Please verify it.
