### ISSUE TITLE
x-axis y-axis title is not displaying in bar graph

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#340]
In user progress bar graph x-axis and y-axis title is not displaying

**Comment by manjulacg** [comment]
Re-tested x axis and y axis title is not showing

**Comment by Inchara98** [comment]
Retested not fixed

**Comment by pandutibil** [comment]
@Inchara98 do you mean x-axis and y-axis labels?

**Comment by Inchara98** [comment]
@pandutibil yes lables

**Comment by pandutibil** [comment]
Ok

**Comment by RNarmatha** [comment]
@FaizanMohammed326 - Please update the ticket once it completed by11

**Comment by Inchara98** [comment]
@FaizanMohammed326 x-axis Y-axis tittle is not present in user unboarding (Courses) , Hear beat of nation (Dial resource), composite report

**Comment by FaizanMohammed326** [comment]
@Inchara98 added axis title in above reports as weel pls take a retest.

**Comment by Inchara98** [comment]
working as expected


![Image](https://user-images.githubusercontent.com/89445054/199882396-9fa16c05-74ae-41ea-a9ae-f5c5e2f3efcd.png)
