### ISSUE TITLE
Smoke test defect for DIAL Resource Usage- GPS of learning

### ISSUE THREAD

**Issue by manjulacg** [Sunbird-cQube/community#345]
When we click on legends the map is not in the center and it is moving up and down.

**Comment by FaizanMohammed326** [comment]
The implementation of map zoom is whenever we have less markers the map will auto focus on only those areas containing markers. so this can be considered as implementation of the same.

**Comment by manjulacg** [comment]
Re-tested map is not showing center of map layout

**Comment by TanushreeSG** [comment]
Invalid
