### ISSUE TITLE
diksha_etb_learning session file processing is failed

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#369]
diksha_etb_learning session.zip
18:03:51 IST
ERROR
5440143c-6748-35e3-5fcb-53cb366b5b08

ConvertRecord[id=5440143c-6748-35e3-5fcb-53cb366b5b08] Failed to process StandardFlowFileRecord[uuid=1f8cdb23-c7b2-40a9-b2b6-b49505b2f5f0,claim=StandardContentClaim [resourceClaim=StandardResourceClaim[id=1664541230473-14, container=default, section=14], offset=0, length=39214202],offset=0,name=diksha_etb_learning-session.csv,size=39214202]; will route to failure: Index for header 'State Code' is 10 but CSVRecord only has 10 values

**Comment by devu1454** [comment]
Issue is resolved, Working as expected

**Comment by RNarmatha** [comment]
Working as excepted
