### ISSUE TITLE
Telemetry Issues

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#373]
- [ ] Estimates by Monday 10th Oct @satendrapalsingh 
- [ ] Telemetry is not working for existing reports. Identify the cause for this and fix it.
- [ ] Extend telemetry support for all the new cQube reports

**Comment by htvenkatesh** [comment]
@Sharathnaik38 As discussed, Lets bring up the telemetry implementation for a single report from 3.7 to 4.0. You can estimate the time required for that(single report) and update here by EOD, based on the reports count will calculate overall estimated time required and who is available to add into other reports in 4.0.
Please make the telemetry as a component based, so it can be utilised for other reports quickly.
Will check and let you know where we can showcase the values in UI, meanwhile you can get the required things done from code level changes.
@vijayatgh @satendrapalsingh @krishnakr6  FYI

**Comment by htvenkatesh** [comment]
This needs the analysis before the implementation of the telemetry issues. Moving this to backlog as need a discussion and take it forward.
The analysis & design ticket is linked to this
[https://github.com/Sunbird-cQube/community/issues/575]

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
Taken in the Upcoming Sprint 11
