### ISSUE TITLE
Responsive font size, color coding, and tooltip related issues across the application

### ISSUE THREAD

**Issue by pandutibil** [Sunbird-cQube/community#382]
Responsive font size, color coding, and tooltip related issues across the application

**Comment by krishnakr6** [comment]
includes Pull Request  #389

**Comment by RNarmatha** [comment]
Please give some update on this ticket

**Comment by pandutibil** [comment]
Fixed all the responsive issues, color indexing and tooltips of reports related to dashlets and chart.js

**Comment by RNarmatha** [comment]
Completed
