### ISSUE TITLE
Issue in Courses report

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#384]
-Usage by course /Usage by course content
     if last 7 day and last day does not showing any thing on screen then click on time range dropdown not able see options only overall is showing
-Usage by course content

      "Select time range as last 7 days and last day chart is not showing if dont have data then we should display no data available error message on the screen or we should display map report"

      "Select time range as last day the chart is not showing 
Issue1: Choose district have dropdowm options and only one district name is displaying 
issue2: selected district map report is not displaying"

**Comment by RNarmatha** [comment]
Duplicate ticket
