### ISSUE TITLE
file is missing in the python directory

### ISSUE THREAD

**Issue by padmanabha1234** [Sunbird-cQube/community#389]

**Comment by devu1454** [comment]
Re-tested not fixed

**Comment by devu1454** [comment]
![Screenshot from 2022-10-06 15-00-51](https://user-images.githubusercontent.com/57621682/194278779-5e15ce48-2461-431f-87af-ad435ac5dd74.png)

**Comment by chetandg123** [comment]
deployed the latest code and tested the file processing of diksha enrolment we are getting above issue , and updated defect to @padmanabha1234

**Comment by chetandg123** [comment]
Re-tested Diksha TPD and ETB enrolment file processing are working as expected
