### ISSUE TITLE
NVSK Issues

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#391]
- Tooltip colour is merging with background colour of the map
UDISE+(Correlation)

![Image](https://user-images.githubusercontent.com/114054046/194044460-87e1cf9f-11fb-4742-b785-aeaab004ccee.png)

- Tooltip is displaying on the bar graph
Nipun Bharath(Learning session)
![Image](https://user-images.githubusercontent.com/114054046/194066412-c0da5b17-2958-41a4-a917-2542646fc9b9.png)

In select subject dropdown unknown value is displaying
Learning session((Nipun Bharath)

![Image](https://user-images.githubusercontent.com/114054046/194211628-f31586ff-3d92-405a-8f7b-99981e7b4497.png)

**Comment by pandutibil** [comment]
@TanushreeSG 
Issue 1: fixed

**Comment by TanushreeSG** [comment]
Issue 1: Resolved
Issue 2: Feature is as expected, if the bar is expanding to the end of the visible area then the toolip position will be adaptive state - Resolved
Issue 3: Datasource contains "Unknown" text so that's why Unknown option is showing - it is data issues - in data file having unknown  - Resolved
