### ISSUE TITLE
TextBook Distribution - " Choose date  data is not displaying"

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#398]
Textbook distrubution - "Choose a date data is not displaying"

**Comment by pandutibil** [comment]
@padmanabha1234 **date** column property is missing from **meta_tooltip.json** file. Please verify.

**Comment by pandutibil** [comment]
@JalajaTR please look into this issue.

**Comment by pandutibil** [comment]
As there is some outdated data in the storage location which is used in the testing, and retested with proper storage location details and it is working fine. @padmanabha1234 and @JalajaTR ensure that the issue won't repeat.

**Comment by TanushreeSG** [comment]
working as expected
