### ISSUE TITLE
Click on trends link is not displaying in single line

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#399]
Student Attendance(Attendance)
Click on trends link is not displaying in single line

**Comment by TanushreeSG** [comment]
![Image](https://user-images.githubusercontent.com/114054046/194246325-eeefc94f-42be-44a5-8ded-13a1b8ba5ae4.png)

**Comment by Inchara98** [comment]
Retested not fixed

**Comment by Inchara98** [comment]
working as expected 


![Image](https://user-images.githubusercontent.com/89445054/199475159-9a34ee88-8768-4dcd-be06-1422023949f7.png)
