### ISSUE TITLE
dropdown is having overall in district wise status but not in course wise status

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#400]
District wise status(Teacher Training)
 Course wise status(Teacher Training)

![Image](https://user-images.githubusercontent.com/114054046/194245045-1c9edc3b-d226-467c-a7b8-20cb13117d42.png)
![Image](https://user-images.githubusercontent.com/114054046/194245044-ec38eb77-e2e9-46ab-bbc2-f638d67bf93a.png)

**Comment by Inchara98** [comment]
Retested not fixed

**Comment by Inchara98** [comment]
@pandutibil Course wise status tab(Nishtha)
After selecting overall from dropdown -- Nishtha1 program data is displaying

**Comment by pandutibil** [comment]
@Inchara98 Different courses are there in the three Nishtha programs, that's why same values are coming for overall selection.

To check this please observe when you select overall option, all the course details will be displayed from all the programs.

**Comment by Inchara98** [comment]
working as expected


![Image](https://user-images.githubusercontent.com/89445054/199912143-02685e4f-d843-4f28-bf51-cb63856b18a4.png)
