### ISSUE TITLE
Guague chart allignment issue

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#402]
Guague chart allignment is not proper

![Image](https://user-images.githubusercontent.com/114054046/194051491-170e1d97-796b-49b2-a683-4396f4a92e2c.png)

**Comment by Inchara98** [comment]
Retested not fixed

**Comment by pandutibil** [comment]
@Inchara98 Please retest the issue

**Comment by TanushreeSG** [comment]
Working as expected

![Image](https://user-images.githubusercontent.com/114054046/199885244-971a6ca3-05b3-436c-96b9-7938426da04c.png)
