### ISSUE TITLE
Styling of the map is not clear

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#403]
Styling of the map is not clear

![Image](https://user-images.githubusercontent.com/114054046/194058734-776f1472-0e7c-4196-ab73-93706b224ab5.png)
![Image](https://user-images.githubusercontent.com/114054046/194058733-ca80de10-8e4a-4da3-9360-323e5fd1ec52.png)

**Comment by FaizanMohammed326** [comment]
As Inputs taken by Suren , Need to keep the cqube-2 reports as-is and update the tile of cQube-1/cQube-2(Marker reports) to the previous tile/background used in cQube-1.

**Comment by satendrapalsingh** [comment]
@FaizanMohammed326 Please share an update on this ticket. This was marked QA-Complete but I see from discussions it still needs some work.

**Comment by TanushreeSG** [comment]
@satendrapalsingh @FaizanMohammed326 please move it to QA

**Comment by satendrapalsingh** [comment]
@TanushreeSG Its moved to Ready for QA. Please take it up for testing and change the status to QA In Progress.
