### ISSUE TITLE
Admin_console application and admin logs are not displaying

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#405]
1.Click on admin console
   Click on logs
   Select application
   Issue : appication logs is not working, loader is loading

![Screenshot from 2022-10-06 11-42-40](https://user-images.githubusercontent.com/57621682/194228035-4d7ebb10-1bb1-4647-b2f0-62fc3c6ee66d.png)

2.Click on admin console
   Click on logs
   Select admin
   Issue : admin logs is not working, loader is loading

![Screenshot from 2022-10-06 11-45-28](https://user-images.githubusercontent.com/57621682/194228616-bdb766e8-b9f3-418e-bbd4-60fb1cb97647.png)

**Comment by htvenkatesh** [comment]
@Sharathnaik38 Please change the path names as discussed and check this issue.

**Comment by Inchara98** [comment]
Working as expected
