### ISSUE TITLE
Diksha api to emission and vice-versa conversion is not working

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#406]
1.Click on admin_console
   Click on configurations
   In Diksha TPD/ETB Data Input Method -> change api to emission
   Issue : Error found while initiating TPD method

![Screenshot from 2022-10-06 11-49-33](https://user-images.githubusercontent.com/57621682/194229223-cb77a7f8-6081-4a29-a995-89f0dd0b1725.png)

**Comment by Inchara98** [comment]
Retested working fine
