### ISSUE TITLE
Logout button is not working

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#407]
1.Click on admin_console
   Click on logout button
  Issue : routining to login page is not proper

![Screenshot from 2022-10-06 11-55-04](https://user-images.githubusercontent.com/57621682/194229650-69fa9462-c0c5-48a0-bd67-2ebb46aa5a5f.png)

**Comment by TanushreeSG** [comment]
Logout functionality is working fine but icon is not clearly
