### ISSUE TITLE
2-F authentiacation is not available

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#410]
Created the qa_admin and qa_report as new cqube users in the admin console -> add user page.
Tried to login with the users qa_admin and qa_report.
Issue : 2F authentication is not displaying
Note : while installation report_viewer config parameter is filled as true

**Comment by Sharathnaik38** [comment]
@JalajaTR  keycloak_users table is missing please check

**Comment by JalajaTR** [comment]
@Sharathnaik38   
The table is missing from the ansible side @ayesha-siddiq123 could you please check on this issue.

**Comment by ayesha-siddiq123** [comment]
modified task for keycloak user queries from SQL script

**Comment by chetandg123** [comment]
@Sharathnaik38 @ayesha-siddiq123 Retested the two-factor authentication part is not fixed 
- Created new admin user and log in with newly created admin user after clicking log in button it is showing a home screen without two-factor auth  
- Created new report viewwer user and log in with newly created admin user after clicking login button it is showing home screen without two factor auth

**Comment by chetandg123** [comment]
@Sharathnaik38 @htvenkatesh login is not working for default users saying invalid credentials 


![Image](https://user-images.githubusercontent.com/64146636/195319383-ef29bcd4-cd63-4aea-8e82-3da42e297fe9.png)

**Comment by htvenkatesh** [comment]
@Sharathnaik38 Please check on this as priority and close this asap

**Comment by Sharathnaik38** [comment]
@asifbasha61  can you please add DB details in auth-api .env which i shared you.

**Comment by krishnakr6** [comment]
Added PR #433

**Comment by chetandg123** [comment]
@Sharathnaik38 @htvenkatesh  Re-tested below issues -> 
- For default user also getting scanning screen - **Fail**

**Comment by htvenkatesh** [comment]
@Sharathnaik38 wts the status on this ticket, wt are the challenges we are facing?

**Comment by Sharathnaik38** [comment]
@asifbasha61 can you please add the keycloak_adm_user: '' in dashboard environment

**Comment by chetandg123** [comment]
@Sharathnaik38 @htvenkatesh  Two factor authentication is working as expected all the scenarios are passed
