### ISSUE TITLE
Session time out is not working

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#411]
Once login to the cQube, If we are not performing any action then session time out must be happen
Issue : session time out is not happening.
Note : while installation session_timeout config parameter is filled as 40M

**Comment by htvenkatesh** [comment]
Hi @surendrasinghs 
**Session timeout - do we need this feature?**
In VSK and NVSK UI (for visualisation consumer) there's no session timeout. In CQB3.7 UI there's timeout for visualisation consumer. 

We are proposing to make this as a backlog item, which can be prioritised post 4.0-beta release.

Please share your opinion.

**Comment by surendrasinghs** [comment]
Sounds good to me. Does this affect admin users also? If not, let's move this to backlog.

**Comment by htvenkatesh** [comment]
@surendrasinghs we don't have user authentication for admin users as well. We can move this to backlog

@Sharathnaik38 please confirm once

**Comment by satendrapalsingh** [comment]
@Sharathnaik38 Please confirm as requested by @htvenkatesh , and if we don't have auth for admin users right now (we don't because we were using VPN till now, right?) - then I'll move this ticket to the backlog.

**Comment by Sharathnaik38** [comment]
@htvenkatesh we don't have user authentication for admin users.

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and has to be analyzed

**Comment by Shruti3004** [comment]
@htvenkatesh - please make sure this is addressed in 5.0
