### ISSUE TITLE
Summary statistics for Inspection Report is not displaying

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#414]
After processing of inspection_master file. summary details are not displaying in te admin_console.
![Screenshot from 2022-10-07 08-25-53](https://user-images.githubusercontent.com/57621682/194458437-52f58f16-34e1-44d1-aefe-f29b109c8a5f.png)

**Comment by devu1454** [comment]
Re-tested working as expected

**Comment by satendrapalsingh** [comment]
Closing this defect as it has been test validated successfully
