### ISSUE TITLE
Diksha summary-rollup Periodic Selection is not working

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#415]
In admin console, Click on the configuration and select from date, To date and stopping hours in the Diksha summary-rollup Periodic Selection.
Issue : Error found while configuring diksha
![Screenshot from 2022-10-07 08-27-42](https://user-images.githubusercontent.com/57621682/194458806-d41eda0a-ebc4-49ec-be0e-c750e56f7dfd.png)

**Comment by padmanabha1234** [comment]
@Sharathnaik38 I updated the python files please re-test.

**Comment by satendrapalsingh** [comment]
Closing this defect as it has been test validated successfully
