### ISSUE TITLE
Dashboard Menu and card Names are mismatching

### ISSUE THREAD

**Issue by manjulacg** [Sunbird-cQube/community#418]
Other Diksha Metrcis Datasource name has to be change according to terminology
Actual Button Name - Other Diksha Metrcis
Expected Button Name - Other Digital Learning Metrics

![Image](https://user-images.githubusercontent.com/100250278/194211702-96f1886a-dae7-42f7-a9db-56b05252623d.png)

The dasboard name and tab names are same it has to change according to given terminologies

Actaul result: Composite Report
Expected result: Composite Dashboard

![Image](https://user-images.githubusercontent.com/100250278/194211997-41d9d497-b98e-4886-9269-7546bba5303d.png)

**Comment by Inchara98** [comment]
Retested not fixed

**Comment by Inchara98** [comment]
working as expected


![Image](https://user-images.githubusercontent.com/89445054/199960197-1bdbb442-7932-4e42-867f-10419c40311c.png)
