### ISSUE TITLE
In Dial Resource Usage-  Usage by Textbook, Usage by Textbook Tab

### ISSUE THREAD

**Issue by manjulacg** [Sunbird-cQube/community#419]
Download Raw File link is not aligned properly

![Image](https://user-images.githubusercontent.com/100250278/194211533-dee3057b-baab-4eea-ade9-90fe7e042c5d.png)
![Image](https://user-images.githubusercontent.com/100250278/194211534-af8fa6dd-2609-4928-b130-0b07c3ebcbb5.png)

**Comment by Inchara98** [comment]
working as expected

**Comment by Inchara98** [comment]
working as expected
