### ISSUE TITLE
In Dial Resource Usage-  GPS Of Learning tab

### ISSUE THREAD

**Issue by manjulacg** [Sunbird-cQube/community#420]
Select total content plays from dropdown and legend card and values on card not aligned properly value text over lapped 

![Image](https://user-images.githubusercontent.com/100250278/194211444-3e83927f-af6d-456e-b9af-ccddfc4bbbaa.png)

**Comment by TanushreeSG** [comment]
Legend value for all the colours are same

![Image](https://user-images.githubusercontent.com/114054046/195830687-f3ac9eec-d81e-40b7-bbb7-2fe9accd86dc.png)

**Comment by Inchara98** [comment]
working as expected
