### ISSUE TITLE
Legend card buttons and text over lapped

### ISSUE THREAD

**Issue by manjulacg** [Sunbird-cQube/community#421]
Dial Resource Usage - Usage per capita tab
 
issue1: Legend card buttons and text over lapped

![Image](https://user-images.githubusercontent.com/100250278/194211298-20a7b76a-d6aa-407e-a6d3-68684619bf45.png)

issue 2: About the dashboard: after this text space is required before start of information

![Image](https://user-images.githubusercontent.com/100250278/194211337-3a3a0fd7-d5dc-4770-939c-0649900f8656.png)

**Comment by TanushreeSG** [comment]
working as Expected
