### ISSUE TITLE
Alignment issue in Other Digital Learning Metrics

### ISSUE THREAD

**Issue by manjulacg** [Sunbird-cQube/community#422]
in Other Digital Learning Metrics - Content Preference tab

- Select state with Districts option from dropdown - dropdown structure is big alignment issues

![Image](https://user-images.githubusercontent.com/100250278/194211088-f9d8d75a-788c-4580-828a-84400b8fc229.png)

**Comment by Inchara98** [comment]
Retested not fixed

**Comment by FaizanMohammed326** [comment]
The first dropdown is a single select , where as the second dropdown is a multi select dropdown which can select upto 10 items. So the width of the second dropdown differs on selection, so this cant be considered as a bug.

**Comment by Inchara98** [comment]
fixed
