### ISSUE TITLE
Alignment issue in Exception list

### ISSUE THREAD

**Issue by manjulacg** [Sunbird-cQube/community#423]
In SAT and PAT tab

- Download Report button is not aligned properly
- Hyper link text is not aligned properly

![Image](https://user-images.githubusercontent.com/100250278/194210658-550cf730-fe60-4ee0-b96c-46d4c4605676.png)

SAR and TAR tab

- Download Report button is not aligned properly 

![Image](https://user-images.githubusercontent.com/100250278/194210731-a7a4249b-bdd5-43ac-b3d3-fd75a15f6563.png)

**Comment by Inchara98** [comment]
working as expected
