### ISSUE TITLE
Alignment issue in Courses

### ISSUE THREAD

**Issue by manjulacg** [Sunbird-cQube/community#424]
Courses - Usage by course tab 

Issue1 : Download Raw File link text is not aligned in to single line

![Image](https://user-images.githubusercontent.com/100250278/194210328-2a66ef56-d422-43f6-9c77-1ad3e5ab7531.png)

Issue 2: in Usage by Couse Content tab

- Download Report button is not aligned properly 

![Image](https://user-images.githubusercontent.com/100250278/194210449-5d232279-e51a-424a-83b1-b6b5274ac43c.png)

issue 3 : in Course Progress tab

- Heat chart and legend card button are not aligned properly  
- Choose a course , Choose time range , choose district/block/cluster dropdowns are not aligned properly 

![Image](https://user-images.githubusercontent.com/100250278/194210549-ba67fdca-f764-494d-8311-7dbe92e08368.png)

![Image](https://user-images.githubusercontent.com/100250278/194210558-2d7e89f9-bc47-4863-aabd-bd28c45b5131.png)

Issue 4 : In Usage by course tab
- In the tooltip value the percentage sign is missing as compared to cqube 3.7

![Image](https://user-images.githubusercontent.com/100250278/194504547-a0a1d718-d366-4cdc-a9d1-3e56bf66c335.png)

**Comment by Inchara98** [comment]
Issue2 - Fixed rest of the issues are not fixed

**Comment by TanushreeSG** [comment]
Issue 3- retested not fixed


![Image](https://user-images.githubusercontent.com/114054046/199470173-5035489a-b4e4-45a1-b939-637a5991244b.png)

**Comment by pandutibil** [comment]
@Inchara98 @TanushreeSG please retest the issues

**Comment by TanushreeSG** [comment]
Working as expected

![Image](https://user-images.githubusercontent.com/114054046/199647678-7dab77ae-797e-4c90-a53f-84dfc93bf0d9.png)
