### ISSUE TITLE
The header of the tab name is displaying incorrect  in Textbook distribution

### ISSUE THREAD

**Issue by manjulacg** [Sunbird-cQube/community#425]
in Textbook Distribution(Lo Table)

The header of the tab displaying incorrect
Actual result: Report On Textbook Distribution Access By Location For:
Expected result: Report On Textbook Distribution Access By Lo Table For:

![Image](https://user-images.githubusercontent.com/100250278/194210072-83a1e0cd-b71a-4755-b750-e18f2a03da7c.png)

**Comment by dhanush-2397** [comment]
@manjulacg Expected result: Report On Textbook Distribution Access By Lo Table For:
Do we need to replace "location" by "lo"?

**Comment by chetandg123** [comment]
@dhanush-2397 
**Actual:** Report On Textbook Distribution Access By Location For:
**Expected:** Report On Textbook Distribution Access By Lo Table For:
