### ISSUE TITLE
Download report is not aligned properly- Textbook Distribution

### ISSUE THREAD

**Issue by manjulacg** [Sunbird-cQube/community#426]
Download report is not aligned properly in Lo table and Map report

![Image](https://user-images.githubusercontent.com/100250278/194209995-0875cadd-f1cd-4698-be36-17b9266d347b.png)

![Image](https://user-images.githubusercontent.com/100250278/194210007-28ca3c06-6319-4fda-835e-cb240efeae0e.png)

**Comment by Inchara98** [comment]
working as expected
