### ISSUE TITLE
Bar Chart does not have X axis Title and Y axis Title in Courses and Dial resource usage

### ISSUE THREAD

**Issue by manjulacg** [Sunbird-cQube/community#427]
in Courses- Usage by course
- does not having x axis and y axis title
- total content plays value is not present in single line

![Image](https://user-images.githubusercontent.com/100250278/194214647-6de4e51e-ef26-4d61-8736-707acc44db9a.png)

![Image](https://user-images.githubusercontent.com/100250278/194214698-18f038f8-1b6d-4c4d-a43e-353fa47f34c1.png)

in Courses- User Progress
- does not having x axis and y axis title
- download report button is not alligned properly

![Image](https://user-images.githubusercontent.com/100250278/194215578-17d1fad1-c1b5-4ea8-92e2-8a5ca2de8354.png)
![Image](https://user-images.githubusercontent.com/100250278/194215577-cf69a726-bbe8-453a-a70b-59799daf0656.png)

in Dial resourse usage - Usage by Textbook
- does not having x axis and y axis title
- total content plays value is not present in single line
 

![Image](https://user-images.githubusercontent.com/100250278/194215173-0b837387-31c2-4252-b019-f47cef5516cc.png)
![Image](https://user-images.githubusercontent.com/100250278/194215172-da6c985b-9ccd-49ce-b43b-ccbbe7591181.png)

**Comment by Inchara98** [comment]
Retested not fixed

**Comment by Inchara98** [comment]
working as expected 


![Image](https://user-images.githubusercontent.com/89445054/199911807-676dee09-3da2-4049-b54d-b6adb10f38f8.png)
