### ISSUE TITLE
Dropdown issue in Textbook distribution (LO table)

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#429]
Block,cluster dropdown values are in Bold
Textbook Distribution(Lo report)

![Image](https://user-images.githubusercontent.com/114054046/194218882-4c313928-d896-42d0-bd10-6c0dbfdea47e.png)

**Comment by manjulacg** [comment]
issue: Mousehover on lo table cell tooltip showing <br/> html tag


![Image](https://user-images.githubusercontent.com/100250278/194369352-62a55712-83f3-4aeb-bdab-01b7e6dd5a97.png)

**Comment by Inchara98** [comment]
working as expected
