### ISSUE TITLE
Heat Map cell color disappears on hover

### ISSUE THREAD

**Issue by SreenivasNimmagadda** [Sunbird-cQube/community#43]
**Description of the bug**

When the heat map is having more than 100 columns and drag the Horizontal scroll bar 60% towards right losing the cell color on clicking of the particular cell.

**To Reproduce**
Steps to reproduce the behaviour:

1. this defect is occurred in the UP where the Utter Pradesh is having more than 100 clusters in the blocks. 
2. The Heat map should have 100+ locations as columns
3. Then Drag the Horizontal scroll bar 60% towards right
4. Hover on any cell
5. Observe the cell is losing it's color code. 

**Reference Screenshots**

**Expected behaviour**
The Cell color should be constant.
 
**Effected code areas**
Angular code: - Need to check with the High chart scroll bar functionality.

**Comment by Sharathnaik38** [comment]
Fixed updated highcharts to "highcharts": "^10.1.0",
