### ISSUE TITLE
Mismatch in Metrics calculation for PAT datasource

### ISSUE THREAD

**Issue by Shoaib15khan** [Sunbird-cQube/community#430]
There is a mismatch found in the "performance" column calculations in PAT Heatchart and PAT MApreport Gradewise reports.

**Comment by RNarmatha** [comment]
@PavitraIR Could you please the status of the ticket and target completion date

**Comment by PavitraIR** [comment]
we have found the root cause, I am fixing on it

**Comment by JalajaTR** [comment]
Assigning to @Shoaib15khan  for retesting

**Comment by RNarmatha** [comment]
Completed
