### ISSUE TITLE
Issue in Diksha-ETB (VSK)

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#431]
- Guage chart is not displaying in ETB coverage status and Content coverage on QR
- No options are displaying select medium dropdown (Learning session)
- undefined is displaying in bar graph (Learning session)

![Image](https://user-images.githubusercontent.com/89445054/194317005-7aaadb9e-0fd3-4bfb-a563-27ab2efd8f44.png)

![Image](https://user-images.githubusercontent.com/89445054/194317086-171b0a8a-257c-4968-bf25-17f7f01b991f.png)

![Image](https://user-images.githubusercontent.com/89445054/194317181-eac490fd-128f-43b4-a184-11a3b4c47710.png)

![Image](https://user-images.githubusercontent.com/89445054/194317344-116bda52-fa01-465c-ba83-e16655b93fd4.png)

**Comment by pandutibil** [comment]
Made some configuration changes for the bar chart report to fix the issue. Gauge chart reports are not loading because the datasource files are missing from the output storage. @devu1454 please upload the following files in to the storage container.
