### ISSUE TITLE
Taking longer time to process the sat file

### ISSUE THREAD

**Issue by padmanabha1234** [Sunbird-cQube/community#432]
Taking 3:15 hours to execute the mv queries.

**Comment by krishnakr6** [comment]
@padmanabha1234 @Shoaib15khan could you provide  specific details on this.
1. How many records / rows your input file contain?
2. What is the expected processing time.
3. What is the actual time it took to process the data.

**Comment by RNarmatha** [comment]
Issue is Fixed
