### ISSUE TITLE
Tooltip issue in courses

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#433]
In tooltip district name is in bold letters rest of them in normal

![Image](https://user-images.githubusercontent.com/114054046/194318071-53c8ea40-52c1-43b7-80a4-ec396e622562.png)

**Comment by Inchara98** [comment]
Retested not fixed

**Comment by dhanush-2397** [comment]
District Name keyword is removed and district name will appear in bold similar to other reports in courses(user progress).

**Comment by TanushreeSG** [comment]
Working as expected
