### ISSUE TITLE
No value is displaying for few indices in tooltip

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#435]
No value is displaying for few indices  in tooltip in Udise Report(School infrastructure)

![Image](https://user-images.githubusercontent.com/89445054/194320256-8e45f46e-5fbe-471c-8180-a277a5ef68a3.png)

**Comment by krishnakr6** [comment]
@Inchara98 could you also provide the specific details.
1. What is the expected outcome?
2. what are the files emitted / processed in school infrastructure data source.

**Comment by Inchara98** [comment]
Invalid defect (As they emitted 1 file values are not displaying in the tooltip)
