### ISSUE TITLE
Course progress- Heat Chart cells are not showing properly as per Cqube 3.7

### ISSUE THREAD

**Issue by manjulacg** [Sunbird-cQube/community#438]
Click on Course Progress tab heat chart is not showing properly (cells are overlapped).

![Image](https://user-images.githubusercontent.com/100250278/194361753-0da9ebba-191a-408b-ba26-acb789eb3379.png)

![Image](https://user-images.githubusercontent.com/100250278/194361815-b1db5653-da64-47a2-a5e7-be5352a1c0ed.png)

![Image](https://user-images.githubusercontent.com/100250278/194361882-1e2c915a-6afe-47f8-ab69-8bde1a8df59d.png)

**Comment by chetandg123** [comment]
Retested the defect - heat chart is showing properly in the all level of the chart

**Comment by satendrapalsingh** [comment]
Closing this defect as it has been test validated successfully
