### ISSUE TITLE
User Progress - choose any district, block,cluster (cluster drop down) name correction

### ISSUE THREAD

**Issue by manjulacg** [Sunbird-cQube/community#439]
navigate to course ,Click on user progress tab choose any district, block,cluster 
issue: cluster drop down name correction
actual result : choose_cluster    
expected result  : Choose a Cluster

![Image](https://user-images.githubusercontent.com/100250278/194363048-60cfcd92-44df-4460-9be3-407a097e9293.png)

**Comment by Inchara98** [comment]
Retested not fixed

**Comment by TanushreeSG** [comment]
Fixed
