### ISSUE TITLE
Other Digital Learning Metrics - Multiple selection and tooltip issue

### ISSUE THREAD

**Issue by manjulacg** [Sunbird-cQube/community#440]
Navigate to other digital learning metrics - 
**Issue 1**: select state with district option from dropdown and select more than 10 districts from district dropdown then alert message popup is not displaying when selecting the 11 th district

![Image](https://user-images.githubusercontent.com/100250278/194365231-1659c483-28b0-4f7d-8070-929fb460f700.png)
![Image](https://user-images.githubusercontent.com/100250278/194365230-d43c079e-988e-4844-a4ed-04d86c037f58.png)

**Issue 2**: Select state with district option from drop down mousehover on the district pie chart tootltip information is missing - Name,District, percentage, total content plays

![Image](https://user-images.githubusercontent.com/100250278/194366087-b72b933e-f693-45d6-b330-85887644f690.png)
![Image](https://user-images.githubusercontent.com/100250278/194366086-fb464ea1-7406-4400-bfe7-c956863ad053.png)

**Comment by satendrapalsingh** [comment]
@RNarmatha Can you please create a subtask in this ticket ([]) for : KT Activity for Admin Console
@FaizanMohammed326 While working on this defect please take KT from @Sharathnaik38 and involved other UI devs as needed for KT transfer

**Comment by satendrapalsingh** [comment]
Related KT task is #469

**Comment by FaizanMohammed326** [comment]
Issue 1 in this ticket has been fixed, yet to push the changes.
Today first half will look into the Issue 2 and resolve it.

**Comment by TanushreeSG** [comment]
Working as expected
