### ISSUE TITLE
Progress card - Blue Box information is not aligned properly

### ISSUE THREAD

**Issue by manjulacg** [Sunbird-cQube/community#441]
Navigate to Progress card - Blue Box information not aligned properly. 

![Image](https://user-images.githubusercontent.com/100250278/194367610-b700c07a-491e-4530-a471-1b9c1d38bf48.png)
![Image](https://user-images.githubusercontent.com/100250278/194367609-0ce9ce16-ca5a-4613-b818-1b6e16d233e5.png)

**Comment by Inchara98** [comment]
Retested not fixed

**Comment by Inchara98** [comment]
@FaizanMohammed326 Total students value is not dsplaying 


![Image](https://user-images.githubusercontent.com/89445054/200283490-b140406b-bc78-412e-a38c-b8d7e80d3a09.png)

**Comment by FaizanMohammed326** [comment]
the progress card data for total students itself from the file is returning null. progressCard/overall/state.json pls check this file @padmanabha1234 .

**Comment by padmanabha1234** [comment]
@PavitraIR Query is returning null please look into this.

**Comment by PavitraIR** [comment]
@Inchara98 Their is an Data issue, Please emit the proper data.

**Comment by RNarmatha** [comment]
@PavitraIR , could you please provide some input about the data issue

**Comment by PavitraIR** [comment]
@chetandg123 please emit latest static and  data files with current date.

**Comment by chetandg123** [comment]
@RNarmatha 
Navigate to Progress card - Blue Box information not aligned properly - **Resolved**

In Blue Box - Total Schools value is not displaying - **Not Fixed**

**Comment by PavitraIR** [comment]
@chetandg123 please emit the appropriate udise file, so that total_students value will be displayed.
