### ISSUE TITLE
Nishtha issue

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#442]
Y axis name is not in camel case
%Aganist potential base(Nishtha)

![Image](https://user-images.githubusercontent.com/114054046/194467661-754b710e-669d-46e0-a24b-887e94d852e8.png)

**Comment by Inchara98** [comment]
Retested not fixed

**Comment by pandutibil** [comment]
Raised a Pull request to dashlet library, once that is merged issue will get resolved.

**Comment by pandutibil** [comment]
@Inchara98 please test the issue
