### ISSUE TITLE
Nifi schedulers - After scheduling jobs from admin console -> Nifi processor are not running

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#448]
**Nifi schedulers - After scheduling jobs from the admin console -> all Nifi processors are not running**
**From UI Nifi Schedular screen - status showing as stopped** 
Please find the below schedular.json file is updating properly  
[
  {
    "groupId": "79699ef5-1a4e-303b-732b-e0891cf52479",
    "groupName": "infra_transformer",
    "state": "STOPPED",
    "day": "*",
    "date": "*",
    "month": "*",
    "mins": 33,
    "hours": 1,
    "timeToStop": 2,
    "scheduleUpdatedAt": "Fri Oct 07 2022 13:32:03 GMT+0530 (India Standard Time)"
  },
  {
    "groupId": "2960e927-f7be-30f8-fc35-5bafd345969a",
    "groupName": "pat_transformer",
    "state": "STOPPED",
    "day": "*",
    "date": "*",
    "month": "*",
    "mins": 33,
    "hours": 1,
    "timeToStop": 2,
    "scheduleUpdatedAt": "Fri Oct 07 2022 13:31:45 GMT+0530 (India Standard Time)"
  },
  {
    "groupId": "",
    "groupName": "textbook_distribution",
    "state": "STOPPED",
    "day": "*",
    "date": "*",
    "month": "*",
    "mins": 23,
    "hours": 13,
    "timeToStop": 14,
    "scheduleUpdatedAt": "Fri Oct 07 2022 13:22:57 GMT+0530 (India Standard Time)"
  },
  {
    "groupId": "6e4dae1c-ebee-392a-5841-21ed606d648f",
    "groupName": "data_replay_transformer",
    "state": "STOPPED",
    "day": "*",
    "date": "*",
    "month": "*",
    "mins": 33,
    "hours": 1,
    "timeToStop": 2,
    "scheduleUpdatedAt": "Fri Oct 07 2022 13:32:21 GMT+0530 (India Standard Time)"
  },
  {
    "groupId": "051966cb-5008-3180-454e-5a25206ef7fe",
    "groupName": "udise_transformer",
    "state": "STOPPED",
    "day": "*",
    "date": "*",
    "month": "*",
    "mins": 33,
    "hours": 1,
    "timeToStop": 2,
    "scheduleUpdatedAt": "Fri Oct 07 2022 13:32:37 GMT+0530 (India Standard Time)"
  },
  {
    "groupId": "093195b6-f31b-347b-5f47-fd3490aebb31",
    "groupName": "crc_transformer",
    "state": "STOPPED",
    "day": "*",
    "date": "*",
    "month": "*",
    "mins": 38,
    "hours": 1,
    "timeToStop": 2,
    "scheduleUpdatedAt": "Fri Oct 07 2022 13:37:27 GMT+0530 (India Standard Time)"
  }
]

**Comment by chetandg123** [comment]
Re-tested nifi schedular screen status and nifi processor job are working as expected

**Comment by satendrapalsingh** [comment]
Closing this defect as it has been test validated successfully
