### ISSUE TITLE
Emission word is not in camel case

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#449]
When we change the input data method from API to Emission in both TPD and ETB , emission word is not in camel case in pop up message

![Image](https://user-images.githubusercontent.com/89445054/194509947-c741af94-9c23-40ae-a96a-e7073239c1d1.png)

**Comment by htvenkatesh** [comment]
@Inchara98 made changes and merged the code, please retest this after deployment in demo6

**Comment by Inchara98** [comment]
Emission word is displaying in camel case
