### ISSUE TITLE
User Level Access of the cQube Reports

### ISSUE THREAD

**Issue by SreenivasNimmagadda** [Sunbird-cQube/community#45]
**Purpose of the Feature**
Implementing of the user level based accessing of the cQube reports

**Description of the Feature**
- cQube reports should be capable enough to access the reports as per the user levels. 
- On page load every user can be able to see all the high level summery of the state.
- The Blocks, Clusters and Schools buttons would be disabled for the all the users accept the state level users.
- A button would be provided as "Access Your location'. When the user clicks on the button then the user may able to see their particular location and the lower levels of their locations.
- The upper level select options will be disabled for the users. The user may get only the lower level location selection which are belongs to the user location.

The current Access levels we have in cQube are,
State level users,
District level users,
Block level users,
cluster level users,
school level users

For example, If the user belongs to a district then the user can be able to access only their district information as well as the lower levels of their districts.
If the user belongs to a Block level then the user may be able to see their block level information as well as the lower levels of their block.

**Effected Code Areas**
Python: Modify the API for the state to provide the User Level & User location along with the user credentials
Angular JS & Node JS: - has to get the input from the API as User Level & User location along with the user credentials
Provide the selection options according to the user levels

**Comment by Sharathnaik38** [comment]
Implimentation from Angular and node js is done
