### ISSUE TITLE
Admin Console - Dashboard Card , Hamburger menu button does not have icons

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#456]
**Admin Console** 
**Issue 1:** Admin dashboard cards do not have icons 
**Issue 2:** The logout button icon is not showing properly 
**Issue 3:** Click on hamburger menu -> menu options should display only Names 
**Actual Menu button Name** - Dashboard Create User 
**Expected  Menu button Name** - Create User 
For all menu button need to remove dashboard word 

![Image](https://user-images.githubusercontent.com/64146636/194520547-c15d0967-325e-4480-b300-44678b760bde.png)
![Image](https://user-images.githubusercontent.com/64146636/194520546-5949a11f-9318-4fab-bed5-790b06013654.png)

**Comment by chetandg123** [comment]
Re-tested the admin console card and menu button icons are showing and working expected

**Comment by satendrapalsingh** [comment]
Closing this defect as it has been test validated successfully
