### ISSUE TITLE
Admin console - User list is not showing users details

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#457]
Admin console 
Click on user list card and showing as **Something went wrong while fetching users**

![Image](https://user-images.githubusercontent.com/64146636/194522140-c245dfdd-b66c-4eff-8888-cbe36b02857a.png)

**Comment by chetandg123** [comment]
Re-tested the defect is resolved - now user list shows list of user name and user role

**Comment by satendrapalsingh** [comment]
Closing this defect as it has been test validated successfully
