### ISSUE TITLE
Admin console - Monitoring details screen is not working

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#458]
Click on the Monitoring details card and it opens in a new tab grafana login page is not showing 

![Image](https://user-images.githubusercontent.com/64146636/194523109-8fa35917-8ce4-4c9f-8627-919c5c81eb78.png)

**Comment by asifbasha61** [comment]
In previous version grafana routing is through local ip and vpn.
In cqube-v4.0-beta, Disabled vpn dependency and routing grafana through subdomain instead of local ip.

**Comment by htvenkatesh** [comment]
@asifbasha61 @chetandg123 please add the sub-domain here used for grafana.

**Comment by chetandg123** [comment]
@htvenkatesh @asifbasha61 retested now I am not able see the grafana login page instead of that screen showing like this 


![Image](https://user-images.githubusercontent.com/64146636/195006986-2afe879e-cb67-4a66-98a2-64d2846d96be.png)

**Comment by asifbasha61** [comment]
Modified nginx configuration.
Its working as expected now.
https://cqube.tibilprojects.com/grafana
username: admin
pswd: admin@123

![Image](https://user-images.githubusercontent.com/38652060/195042705-8304bd00-309a-4eb3-a254-8a06dbb96738.png)

**Comment by htvenkatesh** [comment]
@chetandg123 Pls check this and update

**Comment by chetandg123** [comment]
@htvenkatesh @asifbasha61  Re-tested now able to login to the grafana screen so it is working as expected


![Image](https://user-images.githubusercontent.com/64146636/195063963-d8917a69-e29c-4eb8-b863-d82d8b2382d5.png)
