### ISSUE TITLE
Migration of cQube from Intranet to Internet

### ISSUE THREAD

**Issue by SreenivasNimmagadda** [Sunbird-cQube/community#46]
**Purpose of the Feature**
Providing a single command to migrate the cQube from one environment to another environment

**Description of the Feature**
Current cQube is supporting the below environments, 
1. Laptop installation ( Single machine installation for demo)
2. Private Data center: cQube supports the single server, Two server and the Three server installations in PDC 
3. AWS: cQube supports the single server, Two server and the Three server installations in AWS
4. Azure: cQube supports the single server, Two server and the Three server installations in Azure but the current cQube is not able to support the Azure blob data storage. Have to configure the Server folder and user the folders as the data storage. 

Now, With this enhancement, cQube will get the capability of moving the whole cQube from one environment to another environment with the same state of running without re-installation and reprocessing of the data. 

For Example: If the cQube is installed in the laptop and now wanted to move the cQube same image to AWS, User just can move the whole cQube with the same state of running without re-installation and reprocessing of the data by executing a single command. 

**Effected Code Areas**
Ansible: Ansible code to be created with the file "migrate.sh"
The migrate.sh file should have the below tasks included
1. Should take the back up of the PostgreSQL Data into db backup files
2. Should take the back up of the NIFI Image
3. Install the cQube-base at destination system
4. Install the cQube-Workflow at the destination system
5. Restore the backup files at the appropriate positions.

**Comment by ayesha-siddiq123** [comment]
cQube migration 
on-premise to aws server
on-premise to on-premise
aws server to on-premise
aws  server to aws server

**Comment by devu1454** [comment]
**Functional testing for migration.**
On-premise to aws server (Completed. Working as expected)
On-premise to on-premise (Completed. Working as expected)
Aws server to aws server (Completed. Working as expected)

**Comment by devu1454** [comment]
**Functional testing for migration.**
Aws server to on-premise (Testing In-progress)

**Comment by ayesha-siddiq123** [comment]
cQube Azure Migration Scenarious
-  on-premise to Azure  migration
- Azure to Azure migration
- AWS to Azure migration
- Azure to AWS migration

**Comment by ayesha-siddiq123** [comment]
cQube Azure Migration Scenarious
-  on-premise to Azure  migration
- Azure to Azure migration
- AWS to Azure migration
- Azure to AWS migration

**Comment by ayesha-siddiq123** [comment]
Development Completed for Azure Migration
- on-premise to Azure
- Azure to Azure
- AWS to Azure

**Comment by devu1454** [comment]
Functional testing for azure is inprogress
