### ISSUE TITLE
Admin Console - Click on Hamburger configuration menu button -> loader is loading

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#465]
Scenario: Admin Console
- Click on the Configuration menu button from the hamburger menu 
**Issue1: ** - Configuration screen loader is loading 
**Issue2: ** - When selecting Diksha tpd and ETB dropdown as API to emission and clicking on submit button in the alert pop-up box - **EMISSION** <-> change required to **Emission** 

![Image](https://user-images.githubusercontent.com/64146636/194557092-4f3a0e0a-8031-4139-855c-a1bf6dca39ad.png)

**Comment by satendrapalsingh** [comment]
KT subtask #469

**Comment by dhanush-2397** [comment]
db table  "configurable_datasource_properties" is not present in demo 6 db. Please verify.

**Comment by htvenkatesh** [comment]
@JalajaTR wts the status on this?

**Comment by devu1454** [comment]
Re-tested ,Working as expected
