### ISSUE TITLE
Diksha tpd batch id file is not processing

### ISSUE THREAD

**Issue by murali003** [Sunbird-cQube/community#466]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by padmanabha1234** [comment]
assigned to @Sharathnaik38

**Comment by chetandg123** [comment]
Retested the defect - Diksha batch id is updated in the Diksha processor after processing the diksha_api_progress_exhaust_batch_ids file

**Comment by satendrapalsingh** [comment]
Closing this defect as it has been test validated successfully
