### ISSUE TITLE
Configuration of the NIFI & Visualizations for the new Data Sources

### ISSUE THREAD

**Issue by SreenivasNimmagadda** [Sunbird-cQube/community#47]
**Purpose of the Feature**
Making the configured NIFI Processors as generic according to the metric & The visualization to be made as Single instance based which are reusable for the new Data Sources configuration. 

**Description of the Feature**
The current cQube is following the NIFI Processor groups created as per the data sources. So, 
- Currently each visualization has multiple copies with the respective reports.
- Apache NIFI Data flow is having separate processor groups for each data source.
- Each data source has its specific. SQL file to create tables, functions, views etc.

**Proposal of new design**

- Create the common reusable templates for all UI reports.
- Create common filter components which can be reused across all the reports.
- For the reusable template of reports, existing reports codes have to be modified to support the reusable common components
-  User need to fill the required details in configuration file which contains Type of Data source[ ex. Student attendance ], new data source name, columns, data type of columns.
- Python code will read the config file and detect the key columns needed for validations, transaction and aggregation.
- Python code then creates the DDL, DML, DQL statements with the new columns mentioned.
- Create  the NIFI common template.
- Create  the NIFI parameters with the new columns mentioned.
- Create the NIFI report queries  with the new columns mentioned

**Effected Code Areas**
Ansible 
NIFI
PostgreSQL
Angular JS & Node JS

- [x] [ Map and Table report ](https://github.com/Sunbird-cQube/community/issues/50)
- [ ] [ Heat chart ](https://github.com/Sunbird-cQube/community/issues/52)
- [ ] [Bar chart](https://github.com/Sunbird-cQube/community/issues/52)
- [ ] [ Pie chart](https://github.com/Sunbird-cQube/community/issues/54)
- [ ] [ Line chart](https://github.com/Sunbird-cQube/community/issues/55)
- [ ] [ Scatter Plot ](https://github.com/Sunbird-cQube/community/issues/59)
- [x] [Ansible code change for new common NiFi templates](https://github.com/Sunbird-cQube/community/issues/53)

**Comment by krishnakr6** [comment]
List of completed items.
1. DDL ,DML statements generation using python.
2. NiFi Parameter values creation.

**Comment by krishnakr6** [comment]
completed items
1. Report queries generation
2. Visualization configuration
3. Common NiFi template

**Comment by krishnakr6** [comment]
List of Items in progress
1. Bar chart development
2. Percentage metric configuration

**Comment by krishnakr6** [comment]
since cQube 3.7 and cQube_Edu 1.5 are in merging process, hence this is not valid here.
