### ISSUE TITLE
cQube login screen is not displaying

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#470]
After installation tried to login 
Issue : login screen is not displaying

![Image](https://user-images.githubusercontent.com/57621682/194841399-d456e111-90fa-449d-8329-4f740f53326e.png)

**Comment by chetandg123** [comment]
@pandutibil  retested and is now able to see the login screen but when we provide user name and password and then click on the login button it is not able to navigate the dashboard 
so

**Comment by chetandg123** [comment]
@pandutibil   after login navigate to cQube Dashboard and click on the logout button it is navigates to the home screen ( which has cQube dashboard and admin console button ) 


![Image](https://user-images.githubusercontent.com/64146636/194996251-5fbb9242-d329-45bc-a635-a41b55fd5908.png)

**Comment by satendrapalsingh** [comment]
Closing this defect as it has been test validated successfully
