### ISSUE TITLE
Documentation for Upgrade process( Edu v1.5>=v4.0)

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#472]
Prepare the documentation for the Upgradation process for Eduv1.5=>v4.0 and publish in Microsite

**Comment by satendrapalsingh** [comment]
Publish on project microsite (GitBooks)

**Comment by ayesha-siddiq123** [comment]
@satendrapalsingh @htvenkatesh 
Documentation for Upgrade process( Edu v1.5>=v4.0)
#472
version (edu v1.5 ) is not there, please clear me the verison here for upgradation document.

**Comment by ayesha-siddiq123** [comment]
@surendrasinghs -As i discussed with @satendrapalsingh version (edu v1.5 ) doesnt exist, as it has been upgraded,last lower version available is version (release-3.7 ),please suggest me further.

**Comment by ayesha-siddiq123** [comment]
@htvenkatesh @RNarmatha  need to discuss with Suren.

**Comment by RNarmatha** [comment]
Task Completed
