### ISSUE TITLE
Design Documentation for Frontend Configuration

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#473]
Preparing the Design documentation for Frontend Configuration

**Comment by htvenkatesh** [comment]
@pandutibil have you completed the doc? shall we review it today? The completion time is today for this

**Comment by pandutibil** [comment]
@htvenkatesh document will be completed by evening today. We can review it once it is ready.

**Comment by htvenkatesh** [comment]
Having a discussion on initial draft version. Yet to have it consolidated

**Comment by pandutibil** [comment]
Initial draft of the configuration documented and here is the location of the file [https://docs.google.com/document/d/1j9EjxKQN7dTJ8VWjz3beLifVsYRJuiV8Bc-JhO3mI8s/edit](https://docs.google.com/document/d/1j9EjxKQN7dTJ8VWjz3beLifVsYRJuiV8Bc-JhO3mI8s/edit)

**Comment by satendrapalsingh** [comment]
@htvenkatesh - Please review
@pandutibil, @RNarmatha  FYI

**Comment by RNarmatha** [comment]
it is completed
