### ISSUE TITLE
UI Benchmark(Browsers, resloutions)

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#474]
Supporting  browsers (with version numbers) & display resolutions (4k, desktop, desktop-LG)

**Comment by satendrapalsingh** [comment]
UI Team to help @bommalla with inputs and KT

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
Currently we supported desktop and Desktop-LG . and Not supported in 4K

**Comment by RNarmatha** [comment]
Added into the Backlog
