### ISSUE TITLE
Benchmark for Ingestion and Processing

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#476]
Create a Benchmark Documentation by Ingestion/Processing team to benchmark ingestion load(file size, data size, no. of columns) and & other benchmarks supported by current cQube

**Comment by satendrapalsingh** [comment]
@Shoaib15khan to help @bommalla with this benchmarking

**Comment by satendrapalsingh** [comment]
@bommalla Please connect with @Shoaib15khan and create a sheet with benchmarking test case plan and share for review with @htvenkatesh , @krishnakr6 , @devu1454 , @RNarmatha .

Post that you can continue to actually record the benchmark performance.

**Comment by bommalla** [comment]
Test Driven Development steps:
1. Create a Benchmark Documentation by Ingestion/Processing ---- **Pass**
2. Process the Periodic Assessment data file through Ingestion API ------ Pass
- Periodic_exam_grade_details.zip
- Periodic_exam_subject_details.zip
- Periodic_exam_mst.zip
- Periodic_exam_qst_mst.zip
- Periodic_exam_result_trans.zip
3.Observing the file size ----- Pass
4.Observing the data size ----- Pass
5.Observing the no.of columns ------ Pass
6.Observing the loading time ---- pass
7. Test result --- Pass

**Comment by bommalla** [comment]
1. I'm done with cQube s3 installation and file processing through ingestion API
2. Need to check with Azure and on-premise

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
This is done
