### ISSUE TITLE
Automated daily backup of postgres DB

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#477]
**Assumption **

Backup is automatic and restore is manual.
1. Do we need to add this backup script during installation? It should be part of cQube source code.
2. Where to store the db backups? based on the storage type (aws s3 , azure blob storage, on-premise.
3. What should be backup frequency, archieval policy?
4. Backup and archieval should be storage agnostic. 
5. User should be able to configure the backup policy.( including no backup ) 
6. Document on the backups.

**Comment by satendrapalsingh** [comment]
<more context form the Backlog refinement sheet>

**Assumption**: Backup is automatic and restore is manual.
1. Do we need to add this backup script during installation? It should be part of cQube source code.
2. Where to store the db backups? based on the storage type (aws s3 , azure blob storage, on-premise.
3. What should be backup frequency, archieval policy?
4. Backup and archieval should be storage agnostic. 
5. User should be able to configure the backup policy.( including no backup ) 
6. Document on the backups.

**Comment by asifbasha61** [comment]
Code release for taking backup automatically and pushing it to respective container or s3 bucket as per the storage selection.
As of now editing the cronjob is manual. Working on the script to make setting of cronjob automated and validating the cron syntax

**Comment by asifbasha61** [comment]
With the automated script cronjob is getting scheduled in the root user and not able to trigger the script. Working on the script to trigger the cronjob in the non root user.

**Comment by devu1454** [comment]
Backup is automatic and restore is manual is working as expected

**Comment by asifbasha61** [comment]
1. User needs to fill a variable defining the cron syntax. - validation to check if syntax is correct
2. Ansible needs to pick the syntax and schedule a cronjob automatically. - check in crontab if job has been scheduled.
3. cronjob should run according to the defined period. - check if the backup is happening and being uploaded to respective storage
