### ISSUE TITLE
Make Visualization app's footer timestamp dynamic

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#478]
At the bottom of the Visualization app there is a "last updated on" timestamp.
As of today it is hard-coded, we need to make it dynamic - It should be updated as per the page being viewed.

*Note - Suren has requested that this issue be added to the 4.0 scope for October 23rd release.

**Comment by satendrapalsingh** [comment]
@htvenkatesh , @pandutibil , @krishnakr6 , @JalajaTR - We will need a discussion on this to figure out the design and then estimates.

**Comment by satendrapalsingh** [comment]
@htvenkatesh - Assigning this to you as a placeholder so that we can discuss and take this up on priority for Beta release.

**Comment by htvenkatesh** [comment]
@pandutibil This has to be dynamic, reading from json/csv file for 1.5 and 3.7

**Comment by htvenkatesh** [comment]
@pandutibil shall we connect and discuss on this for 3.7 reports how to implement this?

**Comment by pandutibil** [comment]
@devu1454 please start testing this issue

**Comment by chetandg123** [comment]
@htvenkatesh @pandutibil Tested the Visualization dynamic date stamp is working as expected 

**Note:** Tested for only cQube core-1 reports (VSK Programs) date is updated based on the latest file processing date 

cQube core-2 is not checked due to all reports show no data found 

**so, ticket status will be in-progress**

**Comment by chetandg123** [comment]
@htvenkatesh @pandutibil tested the dynamic date for cQube core -2 reports , done with file processing now in UI on each report dashboard
example:
Education Official - processed data on 21 Oct 2022 but in UI showing - 17 Oct 2022
and all other dashboards also

**Comment by htvenkatesh** [comment]
@pandutibil can u check this quickly if possible

**Comment by pandutibil** [comment]
Checking @htvenkatesh

**Comment by chetandg123** [comment]
@htvenkatesh  
connected with @pandutibil : updated that for dynamic date display on footer they are refering the school_management_category folder date stamp so , 
I have processed **school_management** file on 17th Oct 2022 

**Scanario:** 
Deleted the infra output files from output container and processed the infra_trans file after completion of processing output files are generated but 
school_management_category is showing as **17th Oct** 
rest of json files showing 21th Oct (today's date) 
so according to this situation it is not latest updated date 

Actual Result : if school_management file emitted on 17th then all report dashboard footer showing 17th Oct as date if we processed the files on 21th st 

Expected Result : if we processed on 21th Oct then footer should be displayed on screen

**Comment by htvenkatesh** [comment]
@devu1454 @chetandg123 @pandutibil wts the update on this ticket?

**Comment by RNarmatha** [comment]
@pandutibil , Please take this ticket as priority and update the status of this ticket

**Comment by pandutibil** [comment]
Hidden the date stamp in the application footer if there is no data available for the report

**Comment by pandutibil** [comment]
@chetandg123 please retest the scenario

**Comment by chetandg123** [comment]
@pandutibil after deployment of latest code we are not able to see the cQube core 2 reports please find the below console error for the reference 



![Image](https://user-images.githubusercontent.com/64146636/199388223-0c6c2090-fbe3-4b80-95c0-d47c52d35995.png)

**Comment by chetandg123** [comment]
@padmanabha1234   above issue i got updates from @pandutibil that output folder structure is not correct 
please refer the cqube-qa10-output having all data sources except diksha

**Comment by padmanabha1234** [comment]
@chetandg123 Please emit the correct data, school management category data should be included.

**Comment by chetandg123** [comment]
@padmanabha1234 do you mean school_management_master.zip this file?  if yes i have processed the file and db also having Govt as record

**Comment by murali003** [comment]
@PavitraIR in school_hierarchy_details table, school_management_type is not updating please look into it.

**Comment by RNarmatha** [comment]
@PavitraIR , Please look out all the comments and work accordingly .

**Comment by PavitraIR** [comment]
sure @RNarmatha

**Comment by devu1454** [comment]
@pandutibil dashboard footer dynamic timestamp is not updating.


![Image](https://user-images.githubusercontent.com/57621682/199708005-32c0afd6-70d7-4e88-ade4-75300bfb8857.png)

**Comment by chetandg123** [comment]
@htvenkatesh @pandutibil  
re-tested the defect - dynamic date showing on UI based on data sources is working as expected in Azur installed cQube 

For S3 @devu1454 could you please update once you are testing is done

**Comment by devu1454** [comment]
In s3 dynamic time stamp is working as expected
