### ISSUE TITLE
Tooltip issue

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#479]
- Values in the tooltip are not in camel case
- The space between two information is more in tooltip

**Comment by chetandg123** [comment]
@htvenkatesh few points/suggestions 
all place's tooltip information is not in the proper way 
suppose like 
- not present in camel cases 
- if key: value pairs then the key should in bold letters.

**Comment by Inchara98** [comment]
Retested not fixed

**Comment by pandutibil** [comment]
@Inchara98 changed the background color of tooltip to black and font color to white. If we apply the bold formatting for white text, it doesn't give any value.



![Image](https://user-images.githubusercontent.com/76088803/200295486-04a37cab-9157-4f23-b108-484be5012703.png)

**Comment by TanushreeSG** [comment]
Working as expected
