### ISSUE TITLE
Academic year configuration for cQube

### ISSUE THREAD

**Issue by SreenivasNimmagadda** [Sunbird-cQube/community#48]
**Purpose of the Feature**
As the Academic year is different from one place to another place, cQube should have the capability of acedemic year configuration. 

**Description of the Feature**
The Academic year is differ between the months according to the location. So, cQube should be capable to handle the data processing and the metrics visualizations and the selection components in the configured method. 

Below are the implementation points to obtain the academic year configuration,

- The admin should choose the academic year start - end months as a configuration while the cQube installation. 
- NIFI should consider the start month and the end month while generating the output folder structure
- The Data output file should be generated based in the From Month - To Month
- Visualization should consider the From Month - To Month metrics to show the results on the Reports.

**Effected Code Areas**
Ansible,
NIFI
Angular JS & Node JS

**Comment by RNarmatha** [comment]
Implemented not yet started .
