### ISSUE TITLE
Tooltip issue in dial resource usage

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#480]
In tooltip complete information is not displaying
Dial resource usage(Heartbeat of nation learning)

![Image](https://user-images.githubusercontent.com/114054046/195018660-345a4fa6-3000-4cd3-9867-a95fa34b3058.png)

![Image](https://user-images.githubusercontent.com/114054046/195018764-a169df89-cf98-4ff9-9fb2-026e481133cf.png)

**Comment by Inchara98** [comment]
Retested not fixed

**Comment by TanushreeSG** [comment]
Working as expected

![Image](https://user-images.githubusercontent.com/114054046/199472571-2552a868-cd62-40bd-abd9-631ccba50a3c.png)
