### ISSUE TITLE
cQube Dashboard - logout button is not working

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#481]
Navigate to the cQube Dashboard screen and click on the logout button it is navigating to the home screen instead of the login page 

![Image](https://user-images.githubusercontent.com/64146636/195019551-d3a4d6cb-90ff-4fa6-b36d-9d7d5a8d7a2e.png)

**Comment by FaizanMohammed326** [comment]
its already fixed. pls pull the latest code and retest it.

**Comment by chetandg123** [comment]
@FaizanMohammed326 @htvenkatesh Re-tested the defect it is working as expected.
