### ISSUE TITLE
GPS Learning - TPD and ETB Report showing No data found

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#483]
After File processing of Diksha tpd and ETB -> GPS of learning map report showing as no data found 

![Image](https://user-images.githubusercontent.com/64146636/195023730-a5b4e774-4554-4cd1-956d-13ec474db5fb.png)

**Comment by TanushreeSG** [comment]
Working as expected

**Comment by padmanabha1234** [comment]
diksha_map_etb_state query is not returning any data. assigned to @PavitraIR

**Comment by htvenkatesh** [comment]
@JalajaTR @PavitraIR wts the status on this?

**Comment by JalajaTR** [comment]
The tables are empty we are processing the data.Once done will update the status

**Comment by htvenkatesh** [comment]
@JalajaTR please add the estimation immediately before working

**Comment by JalajaTR** [comment]
This report shows the data for only the current academic year but the data emitted is all previous academic years

**Comment by htvenkatesh** [comment]
@JalajaTR who has to check on this as per your idea?

**Comment by JalajaTR** [comment]
@htvenkatesh I checked it 
This report shows the data for only the current academic year but the data emitted is all previous academic years.
So I want the testing team to check on it by emitting the proper data.

**Comment by htvenkatesh** [comment]
@JalajaTR ok. Reassigning this to chetan for testing. @chetandg123 pls test this and add the estimation time

**Comment by chetandg123** [comment]
@htvenkatesh @JalajaTR Processed the file having current academic year so defect is resolved and working as expected
