### ISSUE TITLE
Pre-aggregated files can be processed based on required sections filled

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#484]
Pre-aggregated files can be processed by filling in the required sections. 
Test and confirm (Jalaja/ Padmanabha) 
**Comment**
28/09/2022 testing is in progress - date col is needed
1. Change needed to support without date column (remove from python god script)
2. Current UI doesn't work with this change. More analysis is required to figure out the change.
3. Some modifications required from the UI.

**Comment by satendrapalsingh** [comment]
<more context from Backlog item sheet>
All sections are currently mandatory. Because of this, pre- aggregated files cannot be processed without filling in all the sections. This is cumbersome.

**Comment by RNarmatha** [comment]
Capability included in v5.0

**Comment by RNarmatha** [comment]
This is related to cQube v4.1 beta
