### ISSUE TITLE
Documentation -"How to Configure"

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#485]
Prepare the Clear documentation on "How-to" configure with its limitations, rules, sample data.
**Assumption**
 Create a doc on how to fill  valid configuration file.
Depends on config file validations

**Comment by RNarmatha** [comment]
Please provide the Comment

**Comment by padmanabha1234** [comment]
The documentation is verified by the krishna. need to verify by @htvenkatesh 


https://docs.google.com/document/d/1gSJSQCOLG0wsWeBDq8T2a8F3n_kCJORU8hsPuaaGG-c/edit

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.
