### ISSUE TITLE
Changes to Emission Data Storage folder names

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#486]
So, essentially Emission data storage = processing data store and Input data store = processed data storage.
Emission is like a temporary storage loaded only for data to be processed. 
Today these are two folders in the same container. => Suggestion: Change in vocabulary to processing folder and processed folder between the emission storage & Input storages

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and needs to be analysed.

**Comment by Shruti3004** [comment]
This is resolved in 5.0
