### ISSUE TITLE
Filters and Hierarchy Filters

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#487]
The filters and the hierarchy of filters are hard coded.
**Comments**

How can we meaningfully name these filter fields
filter1, filter2 ...? 

**sample configuration file**
https://github.com/Sunbird-cQube/community/blob/master/use/textbook_distribution.csv

**Assumption**: Master data flow remains as is.

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and it has to be analyzed

**Comment by Shruti3004** [comment]
@htvenkatesh can you please look into this.

**Comment by RNarmatha** [comment]
All the filters are configured
