### ISSUE TITLE
Tooltip issue in nishtha

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#489]
Nan is displaying in tooltip-%Against potential base(nishtha)

![Image](https://user-images.githubusercontent.com/114054046/195037049-dd60ed02-8f62-49ee-9543-fd8acdce6daf.png)

**Comment by TanushreeSG** [comment]
@htvenkatesh in minor issues it is a P1

**Comment by dhanush-2397** [comment]
**Test cases for number format** 
1) check if the data coming from backend contain NaN.
2) If the particular data is not available or it contains NaN write a function to format the data and present it in a proper format. Check if the function returns proper format.

**Comment by chetandg123** [comment]
@dhanush-2397 re-tested the defect , now In tool tip one information is missing **Target Achieved**  compare to above screen shot 



![Image](https://user-images.githubusercontent.com/64146636/199490896-da3e2445-3407-4893-a8ca-5435c7870950.png)

**Comment by TanushreeSG** [comment]
% Against potential base page report is not displaying

![Image](https://user-images.githubusercontent.com/114054046/199647294-e781268b-3324-48ef-9fbb-7f4a768d03e9.png)

**Comment by TanushreeSG** [comment]
working as expected

![Image](https://user-images.githubusercontent.com/114054046/199658217-0b7a8d4b-c17b-467e-a968-699c40279912.png)
