### ISSUE TITLE
All Map Reports - Selection based lower level information on clicking the Blocks, Clusters & Schools buttons

### ISSUE THREAD

**Issue by SreenivasNimmagadda** [Sunbird-cQube/community#49]
**Purpose of the Feature**
Selection based lower level metrics to be displayed on clicking the Blocks, Clusters & Schools buttons for all the map reports

**Description of the Feature**
The current Map reports are having the Blocks, Clusters & Schools buttons which displays the whole state information. Below are the proposed actions to be implemented for this feature

- If the user is not selected any location then Blocks, Clusters & Schools buttons should display the whole state data.
- If the user selected any location and clicks on the Blocks, Clusters & Schools buttons, Then the lower levels of the data should be displayed
For Example: If the user selected a District and click on the Blocks button, then the data should be displayed the blocks which are under the selected District 
If user selected a District and Click on the clusters button, then the data should be displayed the Clusters which are under the selected District.
If user selected a District and Click on the Schools button, then the data should be displayed the Schools which are under the selected District.

- The Same & higher level button should be disabled If the user selects the lower level location 
For Example: If the user selected a Block then the Blocks button should be disabled.
If the user selected cluster then the Clusters button & The blocks button should be disabled.
If the User selected a School, then all the buttons should be disabled. 
 

**Effected Code Areas**
Angular JS & Node JS

**Comment by krishnakr6** [comment]
Added the new feature as per the requirement. Existing output files are used.
