### ISSUE TITLE
Documentation - "How to Set up the Master Data"

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#490]
Clear documentation on "How to" set up master data for cQube since it assumes/requires School master and Student master
**Assumption**

List of files / tables included in master data setup

- master data is setup by emitting the schoolmaster, district master files etc.,. What other/manual steps need to be documented here?"

**Comment by murali003** [comment]
The documentation is completed, it is reviewed by @krishnakr6 

[https://docs.google.com/document/d/1sBAOUgTDiRgijWBm_qiD0uHOvJihgd0nbQa6ullCGj0/edit](url)

**Comment by RNarmatha** [comment]
This is completed and reviewed
