### ISSUE TITLE
values are not seperated by comma in download report

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#492]
values are not seperated by comma in download report

![Image](https://user-images.githubusercontent.com/114054046/195037903-9ac644e4-4d86-48c1-b198-926b596b279f.png)

**Comment by Inchara98** [comment]
Retested not fixed

**Comment by TanushreeSG** [comment]
Retested not fixed

![Image](https://user-images.githubusercontent.com/114054046/200312210-090b2a2c-98b0-4c22-97b0-3bf50ec9a9c2.png)

**Comment by FaizanMohammed326** [comment]
@TanushreeSG can u please mention which report this issue is occuring.?

**Comment by TanushreeSG** [comment]
@FaizanMohammed326 Nishtha (course wise status)

**Comment by FaizanMohammed326** [comment]
Please select the option 'Format quoted field as text' while opening the file and retest.

**Comment by TanushreeSG** [comment]
Working as expected

![Image](https://user-images.githubusercontent.com/114054046/200473562-ab9702d0-8fdd-476d-9863-2b6432ca6b53.png)
