### ISSUE TITLE
Process Master data and Link with Trans data

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#494]
The join from the raw data file to the master data( which contains the hierarchy information and location information for cluster, block, district) based on the school_id is hard coded to get the district , block, cluster and school information from the master data.

**Comments**
How to process master data and link with trans data.
If  current master data processing as is, then we can remove this hard coded school_id column and enable it through configuration

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0. and it has to be analyzed

**Comment by Shruti3004** [comment]
This is addressed in 5.0 by introduction of events and dimensions.
