### ISSUE TITLE
Data-sources need to get a user ID and password to use cQube Ingestion API

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#497]
Action: Update the microsite with this information. Data-sources need to get a user ID and password to use cQube Ingestion API. This is not secure. We should implement API access token (JWT) mechanism with proper policy for (daily) token refresh, etc. as done in other Sunbird building blocks.

**Comment by RNarmatha** [comment]
To be Analyzed and this is not covered in v5.0

**Comment by Shruti3004** [comment]
Hey @RNarmatha @htvenkatesh  - please update the current auth approach on microsite.

**Comment by RNarmatha** [comment]
Implemented
