### ISSUE TITLE
Start Using Graylog

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#498]
Start using the Graylog to remove complexity from data exploration, compliance audits, and threat hunting.

**Comment by RNarmatha** [comment]
This issue not covered in v5.0. To be analyzed

**Comment by Shruti3004** [comment]
@ChakshuGautam @vijayatgh @htvenkatesh - please add your thoughts here.

**Comment by RNarmatha** [comment]
Currently we are not using logs , we need to discuss on this

**Comment by RNarmatha** [comment]
Added to Backlog
