### ISSUE TITLE
Implement Archival Policy

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#500]
Current data flow is from emission data storage to input data storage. Input data storage has a 3 year archival policy. 

 Implement a configurable archival policy for input and output data storage.

**Comment by RNarmatha** [comment]
This issue not covered in v5.0. To be analyzed

**Comment by Shruti3004** [comment]
@ChakshuGautam @vijayatgh @htvenkatesh - we need archival policy for the datasets. Any thoughts on this?

**Comment by RNarmatha** [comment]
Currently we consider onyl 4 folder - Emission, Error, Process_input and combined input . we havent take archival
