### ISSUE TITLE
Decouple PostgreSQL from rest of the system

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#502]
Decouple the database (PostgreSQL) from the rest of the system so that we can support other (relational?) databases too.
Use something like Apache Calcite?

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and needs to be analysed.

**Comment by Shruti3004** [comment]
@ChakshuGautam @vijayatgh - please add your thoughts here.

**Comment by RNarmatha** [comment]
Currently we are using DB as Postgres. WE can take it is backlog and add it to the roadmap
