### ISSUE TITLE
Metrics test Mismatch in SAT data source 

### ISSUE THREAD

**Issue by Shoaib15khan** [Sunbird-cQube/community#505]
In SAT datasource Heat chart Indicator school level there is mismatch found in marks column.

**Comment by RNarmatha** [comment]
@PavitraIR Could you please the status of the ticket and target completion date

**Comment by PavitraIR** [comment]
sure i will update @RNarmatha

**Comment by RNarmatha** [comment]
@Shoaib15khan please do the retest and update the comment

**Comment by Shoaib15khan** [comment]
@murali003 sat mapreport overall files are not generated  please check .

**Comment by murali003** [comment]
@Shoaib15khan the queries is not updated in the sat_queries.json, so @PavitraIR  please look into this issue.

**Comment by PavitraIR** [comment]
Task :
    
     1.To processing sat_learning_p1_indicator_cluster query to calculate the school_id wise marks of students.
 
Expected Result:

     1. All students marks should be updated in the table and nifi queries as well.

**Comment by RNarmatha** [comment]
@PavitraIR , @murali003  and @Shoaib15khan , Please update the status of this ticket and mentioned the target completion date.

**Comment by PavitraIR** [comment]
Assigning to @Shoaib15khan for retesting.

**Comment by RNarmatha** [comment]
Need to discuss with Jalaja - Shoaib

**Comment by Shoaib15khan** [comment]
Issue with the sat marks column has been resolved

**Comment by RNarmatha** [comment]
Completed
