### ISSUE TITLE
Configuration of the NIFI,DB & Visualization for the new Data Sources - Heat chart

### ISSUE THREAD

**Issue by krishnakr6** [Sunbird-cQube/community#51]
- [ ] Development
- [ ] Integration Test
- [ ] https://github.com/Sunbird-cQube/community/issues/63

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and needs to be analysed.

**Comment by RNarmatha** [comment]
Configuration was taken up in the current versions
