### ISSUE TITLE
Operational metrics for Ingestion API and Emission Data Storage

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#510]
cQube Ingestion API and Emission Data Storage must implement operational metrics such as
- number of files
- storage used
- files transferred
- infrastructure utilisation
- etc.

Also, use instrument events to enable monitoring.
And use METRIC event specification in Sunbird Telemetry (https://telemetry.sunbird.org/learn/v3_event_details#metrics)

**Comment by RNarmatha** [comment]
Telemetry is addressed in the upcoming Sprint
