### ISSUE TITLE
Remove hard-coded names from config input filters

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#511]
The filters and the hierarchy of filters are hard coded. Make these names generic.

**Question**: How can we meaninfully name these filter fields: filter1, filter2 ...? 
**Assumption**: Master data flow remains as is.

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
These are configurable in the current version
