### ISSUE TITLE
Document details of currently implemented logging

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#512]
Share details of the currently implemented logging. Use Grafana  and Prometheus for Infrastructure metrics and Graylog for Functional metrics.

**Questions**
Please confirm 
1. We will share the currently implemented Grafana and Promethus details to Santhos G and Santhosh V.
2.  Grafana/Promethuues already implemented in admin console. Do we need to move this to someother place?
3. Graylog need to implemented for functional metrics.? What are metrics required?

**Comment by RNarmatha** [comment]
@ananya-jain1 and @htvenkatesh , Please look into this

**Comment by ananya-jain1** [comment]
Approach being finalised as part of the cQube roadmap.

**Comment by RNarmatha** [comment]
To be considered in the Road Map
