### ISSUE TITLE
Implement configuration lifecycle management

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#515]
Implement configuration lifecycle management.
Create, List, Read, Update, Delete, etc for configurations.

Note
- Initial solution can be a github repo based approach

**Comment by RNarmatha** [comment]
@ananya-jain1 and @htvenkatesh , Please look into this ticket

**Comment by ananya-jain1** [comment]
Approach being finalised for cQube roadmap.

**Comment by RNarmatha** [comment]
Invalid
