### ISSUE TITLE
Review backlog video meeting - DevOps, SecOps

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#517]
Review the DevOps & SecOps discussion meeting video and add/refine items to the backlog.

_Note - Refer [cQube Internal Notes](https://docs.google.com/document/d/1mz5LjZfrswWpvQHl9IFjjyipMcrjJ4tK0JKPU87gaM4/edit#) document page-1 for video meeting link and passcode_

**Comment by RNarmatha** [comment]
Meetings videos
