### ISSUE TITLE
Review backlog video meeting - Architecture Discussion, Architecture Review

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#518]
Review the Architecture discussion & Architecture Review discussion meeting videos and add/refine items to the backlog.

_Note - Refer [cQube Internal Notes](https://docs.google.com/document/d/1mz5LjZfrswWpvQHl9IFjjyipMcrjJ4tK0JKPU87gaM4/edit#) document page-1 for video meetings links and passcodes_

**Comment by RNarmatha** [comment]
Reviewing purpose
