### ISSUE TITLE
Configuration of the NIFI,DB & Visualization for the new Data Sources - Bar chart

### ISSUE THREAD

**Issue by krishnakr6** [Sunbird-cQube/community#52]
- [ ] Development
- [ ] Integration Test
- [ ] https://github.com/Sunbird-cQube/community/issues/61

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and needs to be analysed.

**Comment by RNarmatha** [comment]
Configuration changes are taken up in the current version
