### ISSUE TITLE
Code refactoring for Emission Data Storage

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#524]
- [ ] **01. Code Structure**
The code structure is not consistent with sunbird standards.
I expected a basic organisation of the code into ingestion, processing, storage, metrics, query etc folders. 
Please review this in detail with Anand P.

_Update_
Folder sructure is organised. Require inputs and then review.
https://github.com/Sunbird-cQube/cQube_Edu/tree/cqube-4.0-alpha

- [ ] **02. Code Readability**
With respect to code, I see function names becoming the file names themselves. for ex: update_nifi_params.py etc. Readability of the code is poor and this would have a significant impact on maintainability and contribution. Code needs to be refactored as well, please plan for it post review with Anand P

_Additional Info_
- Python script https://github.com/Sunbird-cQube/cQube_Workflow/blob/release-3.7/development/datasource/python/views.py
- The Diskha data extraction mechanism is implemented through the NIFI processor.

_Update_
Code refactor is partially done, Require input and then review
https://github.com/Sunbird-cQube/cQube_Edu/tree/cqube-4.0-alpha/utils/nifi-utils

**Comment by RNarmatha** [comment]
It is completed
