### ISSUE TITLE
Abstract out the Ingestion API from S3

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#525]
The ingestion API is fully hard coded with S3.
Are we only supporting AWS? If not, can you abstract out the cloud integration?
Please use libraries like libcloud.

_Analysis & Update_
cQube 4.0 will support On-Premise, AWS S3, and Azure blob storage.
Since we are sending the pre signed URL as response.
After analysis of libcloud library, currently it doesn't have  pre signed URL generation functionality.

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and needs to be analysed.

**Comment by ananya-jain1** [comment]
@ChakshuGautam @vijayatgh @htvenkatesh - please mention your inputs on how this can be included in future cQube roadmaps.

**Comment by ananya-jain1** [comment]
Tracked here #753
