### ISSUE TITLE
Fix the GitHub folder structure and code organisation

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#527]
- [ ] 01. Refactor the folder Structure in GitHub -_Update: Review is pending_
- [ ] 02. Review code organisation with Anand P. Code review can happen only after some basic organisation. - _Update: Review is pending_
- [ ] 03. Create the separate repositories for each layer (Decoupling of the layers). New repositories already created. Update read-me for each repository. Utilities and properties related stuff could be moved to the util directory. This will enable us to deploy each of the components independently (microservice architecture). Today it is a monolith with everything being deployed at once - there is no choice to the adopter. - _Update: Required inputs on when to do_
- [ ] 04. Any method should not be more than 5-10 lines. Current code is 1500 lines. That’s so difficult to maintain and contribute to. (See https://github.com/Sunbird-cQube/cQube_Workflow/blob/release-3.7/development/datasource/python/config_create_table_params.py) - _Update: Refactoring is partially done._
- [ ] 05. Keep the cQube 3.7 repository until the bugs are fixed. Later on make a note in the Readme.txt file with the new repository. Lock old repositories and start using new ones.
- [ ] 06. Add comments to the code. - _Update: Is there sunbird specific standard we need to follow or how do you suggest_
- [ ] 07. **Question:** How can we change the orchestration engine (say, NiFi with Airflow), database (say, Mongo instead of Postgres), and cloud service provider (Azure instead of AWS)?

**Comment by RNarmatha** [comment]
@ananya-jain1 Please look into this ticket

**Comment by ananya-jain1** [comment]
@htvenkatesh - please consider these practices as part of the cQube roadmap. Let's incorporate in the next 2 sprint plans.
