### ISSUE TITLE
Questions on Ingestion to Processing Architecture Review

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#528]
- [x] #755
- [x] #756
- [x] #757
- [x] #758
- [x] #759

**Comment by RNarmatha** [comment]
@ananya-jain1 , Please look into this ticket

**Comment by ananya-jain1** [comment]
To be considered as part of cQube roadmap.

**Comment by RNarmatha** [comment]
All the sub tickets are closed
