### ISSUE TITLE
Implement VPN-based-access alternative

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#529]
VPN-based access is currently not working for Admin Console (current approach is via user-id/password).
Need to fix this or drop VPN by moving to another secure alternative

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and needs to be analysed.

**Comment by ananya-jain1** [comment]
@ChakshuGautam @vijayatgh @htvenkatesh - please mention your inputs to incorporate this in the future cQube roadmap.

**Comment by ChakshuGautam** [comment]
@satendrapalsingh We are moving away from trust being managed by cQube to trust managed by an external authentication service. cQube 5.1 will allow for external IDPs to be added to ensure services are authenticated at an API Gateway.

VPN should be added a plugin to cQube and not part of the installation. The Admin UI ports can be configured to not be exposed at all or can be done through a firewqall/VPN depending on state requirements. cQube is not opinionated on this front.

**Comment by ananya-jain1** [comment]
@htvenkatesh - let's consider this in the design for authentication.

**Comment by RNarmatha** [comment]
Upcoming Sprint we are considering this
