### ISSUE TITLE
Address visualization discrepancy - Area representation in Map Reports

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#531]
**Type of discrepancy**
Area Representation in map reports.

**In cQube-2**
District is represented as color-filled bounded areas on the map

**In cQube-4.0-alpha**
District is represented as a marker on the map

**Change agreed upon**
Go back to the original representation of districts (and blocks, clusters, schools, etc.) as color-filled bounded areas instead of markers on the map. Caveat - need discussion around shortlisting appropriate colors for blocks/ clusters/ schools as this is new implementation (these levels were not present in cQube-2).

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
This was fixed in the last Sprint
