### ISSUE TITLE
Address visualization discrepancy - Progress card/button placement

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#533]
**Type of discrepancy**
Access the Progress card/button.

**In cQube-2**
It is included as a dashboard item which includes needed progress cards across the application

**In cQube-4.0-alpha**
Currently no need for an extra link as all the progress cards can be accessed under a separate single page (from left-hand navigation menu)

**Change agreed upon**
Consider providing the Progress card/button again (as it was in cQube-2)

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
Progress card level of report is not taken up in the current version
