### ISSUE TITLE
Address visualization discrepancy - Report descriptions

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#534]
**Type of discrepancy**
Description for each report.

**In cQube-2**
Present in cQube-1 reports

**In cQube-4.0-alpha**
Not present in cQube-2 reports

**Change agreed upon**
Descriptions should be added to all cQube-2 reports (VSK, nVSK). Requirement - need description data (text) for all cQube-2 reports

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
This is addressed in the current version
