### ISSUE TITLE
Multinode system and  Microservices architecture model

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#536]
Multinode system & Microservices architecture model instead of maintaining single server deployment

**Comments**
https://docs.google.com/document/d/1mz5LjZfrswWpvQHl9IFjjyipMcrjJ4tK0JKPU87gaM4/edit#

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0

**Comment by ananya-jain1** [comment]
@RNarmatha - please attach the correct URL of the sheet.

**Comment by RNarmatha** [comment]
Currently we are following microservices
