### ISSUE TITLE
Implementation of Auto scaling

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#537]
Auto scaling should be implemented to reduce the usage and cost

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0

**Comment by ananya-jain1** [comment]
@ChakshuGautam @vijayatgh @htvenkatesh - please add your inputs to add this to further releases of cQube.

**Comment by RNarmatha** [comment]
This is implemented in the current version
