### ISSUE TITLE
Configuration of the NIFI,DB & Visualization for the new Data Sources - Pie chart

### ISSUE THREAD

**Issue by krishnakr6** [Sunbird-cQube/community#54]
- [ ] Development
- [ ] Integration Test
- [ ] https://github.com/Sunbird-cQube/community/issues/65

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and needs to be analysed.

**Comment by RNarmatha** [comment]
Pie chart is not included in the current version
