### ISSUE TITLE
Implement Graylog data logs

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#541]
1. Implement graylog for data logs and logs should not be inside admin console
2. Log paths should be dynamic instead of being hard-coded

**Comment by RNarmatha** [comment]
To be analysed

**Comment by ananya-jain1** [comment]
@htvenkatesh - please plan to add this in the sprints for February for roadmap v5.0.

**Comment by RNarmatha** [comment]
Currently not taken up . To be considered for the road map

**Comment by RNarmatha** [comment]
Added in the Roadmap
