### ISSUE TITLE
Plan and implement branching strategy

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#544]
Maintain tags for each release branch and/or hotfix branches.
Consider “X” as a major, “Y” as a minor and “Z” as a Hotfix.

**Comments**
https://docs.google.com/document/d/1mz5LjZfrswWpvQHl9IFjjyipMcrjJ4tK0JKPU87gaM4/edit#

**Comment by ananya-jain1** [comment]
This is addressed. @htvenkatesh - please add the relevant PPT link which has the nomenclature, based on previous discussions.

**Comment by RNarmatha** [comment]
This is addressed in the current version
