### ISSUE TITLE
Maintain the logs

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#548]
Maintain the logs to count the number of API requests coming to Nginx.

**Comment by RNarmatha** [comment]
To be analyzed: Issues that don't get covered in v5.0.

**Comment by ananya-jain1** [comment]
@htvenkatesh @RNarmatha - please plan to add this in the sprints in February as part of the v5.0 roadmap.

**Comment by RNarmatha** [comment]
This is not considered in the current version
