### ISSUE TITLE
Make changes to cQube data sources emission and processing frequency

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#552]
Currently cQube allows data sources to emit data (CSV files archived as ZIP) any number of times in a day.
cQube processes them for each data-source in a sequence starting with the oldest file and picking next files for the day, de-duplicating, and merging all files for a day.

_Update_
1. cQube3.7 Ingestion API sends s3 presinged url as response with 1 hour expiry time,
2. JWT token is passed in header to Ingestion API and JWT is validated by KONG API Gateway.
3. What other features are required?

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
Implemented in current version
