### ISSUE TITLE
Explore cQube multi-tenant architecture option

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#554]
Currently cQube is designed to be deployed for each State/adopter.
It is not a multi-tenant system. So, data isolation is already in place.

_Update_
What is the expectation? Should we explore multi-tenant architecture for cQube?

**Comment by RNarmatha** [comment]
@ananya-jain1 , Please review this issue

**Comment by ananya-jain1** [comment]
To be considered as part of the cQube roadmap.

**Comment by RNarmatha** [comment]
This is commented already. Need to discuss on this

**Comment by RNarmatha** [comment]
Added in the Backlog item
