### ISSUE TITLE
Lo table report is not displaying in textbook_distribution

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#559]
In configuration file We included only lo_table  report and tried to process it. 
Configuration file is successfully processed and data processing also successfully processed.
Issue : Ui report is not showing lo table

**Comment by devu1454** [comment]
While processing of the configuration file, Found below error
ExecuteSQLRecord[id=94c0402e-7d16-3300-9fcf-ef66272d7a35] Unable to execute SQL select query select distinct report_name,report_type,description from configurable_datasource_properties

 for StandardFlowFileRecord[uuid=25d0db75-8356-4853-8423-c53c76fd2f15,claim=StandardContentClaim [resourceClaim=StandardResourceClaim[id=1665669856060-15, container=default, section=15], offset=64500, length=25],offset=0,name=textbook_distribution.csv,size=25] due to ERROR: relation "configurable_datasource_properties" does not exist
  Position: 58; routing to failure: org.postgresql.util.PSQLException: ERROR: relation "configurable_datasource_properties" does not exist
  Position: 58

**Comment by htvenkatesh** [comment]
@JalajaTR have u completed this? the estimated time was yesterday?

**Comment by JalajaTR** [comment]
@htvenkatesh It was raised yesterday night Am checking on it now

**Comment by htvenkatesh** [comment]
@JalajaTR this we discussed in 4.30 call and that time only we have estimated this timeline, not raised night

**Comment by JalajaTR** [comment]
@devu1454 could you confirm

**Comment by JalajaTR** [comment]
@devu1454 and @htvenkatesh The issue is fixed and the code is available in github
Assigning it to @devu1454 for retesting

**Comment by devu1454** [comment]
Started the re-testing of the defect

**Comment by devu1454** [comment]
Data processing is working as expected

**Comment by devu1454** [comment]
Data processing is working as expected

**Comment by devu1454** [comment]
Instead of showing Lo_table, Map is showing in the textbook_distribution

**Comment by devu1454** [comment]
Instead of showing Lo_table, Map is showing in the textbook_distribution

**Comment by devu1454** [comment]
Instead of showing Lo_table, Map is showing in the textbook_distribution

**Comment by htvenkatesh** [comment]
@devu1454 if its still a issue, please reassign this ticket to developer

**Comment by devu1454** [comment]
@htvenkatesh This ticket is assigned to @FaizanMohammed326

**Comment by htvenkatesh** [comment]
@FaizanMohammed326 wts the update on this?

**Comment by FaizanMohammed326** [comment]
Fixed @htvenkatesh

**Comment by devu1454** [comment]
Textbook_distribution tabs are working as expected

**Comment by devu1454** [comment]
1.<br> tags are displaying on the cells.
![Screenshot from 2022-10-18 15-12-42](https://user-images.githubusercontent.com/57621682/196396302-ef800be3-6e96-4967-95b0-d54ef4874744.png)

**Comment by devu1454** [comment]
above defect is re-tested, working as expected
