### ISSUE TITLE
Configuration of the metric for the new Data Sources - Average

### ISSUE THREAD

**Issue by krishnakr6** [Sunbird-cQube/community#56]
Python logic is written to create queries to calculate the average for the specified column from the configuration file.

The columns in the configuration file should be filled as below to get the average in the metric

The **metric_type** should be specified as **average**.
The column need to be considered for calculating average should be mentioned under **ref_columns**.
The result metric column will be named as the name mentioned under **result metric**

**Comment by JalajaTR** [comment]
Completed the development for calculating average from the configuration file.

**Comment by devu1454** [comment]
Completed the Funtional testing of cumulative metrics. Working as expected
