### ISSUE TITLE
Other Diksha metrics legend issue

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#560]
There is no space between two words
Other Diksha metrics(Content preference)

![Image](https://user-images.githubusercontent.com/114054046/195505287-cf7f082b-5568-45de-a865-aed1cf599e8a.png)

**Comment by Inchara98** [comment]
Retested not fixed

**Comment by dhanush-2397** [comment]
Had a call with pavitra regarding this issue as the data is coming from data base it involves few changes.

**Comment by PavitraIR** [comment]
Need to discuss with Jalaja.

**Comment by PavitraIR** [comment]
The values displayed in legend for other diksha metrics  is as per the contents of the column object_type  in the table diksha_total_content. Those values cannot be modified



![Image](https://user-images.githubusercontent.com/111955354/199930555-a2b98d4a-d822-4696-86b3-49c0991db881.png)



![Image](https://user-images.githubusercontent.com/111955354/199930633-916b2dcf-1a59-479a-b8e0-2744236490a7.png)

**Comment by RNarmatha** [comment]
Issue is Fixed .
