### ISSUE TITLE
Azure Installation - Admin console screen is not working

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#564]
Installed the Azure cQube 
- Click on the Admin console button showing the below errors 

![Image](https://user-images.githubusercontent.com/64146636/195545023-d504c0c7-8140-432a-9265-6833b66a4bab.png)

**Comment by htvenkatesh** [comment]
@Sharathnaik38 what are the required changes on this ticket?

**Comment by Sharathnaik38** [comment]
@htvenkatesh  i will connect with @asifbasha61 and let you know the changes.

**Comment by Sharathnaik38** [comment]
@htvenkatesh i debuged the code their is a error with azure connection iam working on it takes some time will test on monday 1st half.

**Comment by Sharathnaik38** [comment]
@htvenkatesh and @chetandg123  admin console is now routing please check

![Image](https://user-images.githubusercontent.com/90701833/195859939-1854d7d2-e52f-4f0b-83db-f3578cf9f5b1.png)

**Comment by chetandg123** [comment]
@htvenkatesh @Sharathnaik38 Re-tested AZUR admin console after clicking admin console button not able to navigate to admin console dashboard


![Image](https://user-images.githubusercontent.com/64146636/196092921-6dea76f6-6115-443e-b526-35e8cec5ec73.png)

**Comment by htvenkatesh** [comment]
@Sharathnaik38 wts the issue over here? have u checked this? if not can u pls check it asap if u r available?

**Comment by Sharathnaik38** [comment]
@htvenkatesh i checked it and explained to @FaizanMohammed326 what to do.issue is Azure connection string is wrong i asked faized to check with @asifbasha61.

**Comment by FaizanMohammed326** [comment]
@htvenkatesh Working as expected

**Comment by htvenkatesh** [comment]
@FaizanMohammed326  please reassign the tickets back to respective QA person once the development is completed

**Comment by chetandg123** [comment]
@htvenkatesh @FaizanMohammed326 I have done re-testing the azure admin console is not working 
please find the screenshot for reference

After installation, if we do sudo pm2 status -> dashboard - API status shows errored 


![Image](https://user-images.githubusercontent.com/64146636/196334812-d6fc368c-fe71-41c4-81b2-e138a36f3419.png)



![Image](https://user-images.githubusercontent.com/64146636/196334755-42df55ba-5d9c-45cd-b39d-187a872b519d.png)

**Comment by chetandg123** [comment]
@htvenkatesh @FaizanMohammed326 re-tested Azure admin console defect is resolved now able to navigate to admin console dashboard

**Comment by RNarmatha** [comment]
Fixed issue
