### ISSUE TITLE
Azure - while processing main_metrics file getting error

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#565]
processing the main_metrics.zip file to azure (cqube-state-emission) -> aggregate data processor group throwing error 
**Issue:** Azure Credentials are not updated

![Image](https://user-images.githubusercontent.com/64146636/195548188-2f94d00e-3014-4522-a7bf-c6af755359a9.png)

**Comment by htvenkatesh** [comment]
@padmanabha1234 have u checked this? and then changed the status to ready for QA?

**Comment by htvenkatesh** [comment]
@padmanabha1234 is it ready for testing then?

**Comment by htvenkatesh** [comment]
@chetandg123 please take a retest on this and update

**Comment by padmanabha1234** [comment]
Yes @htvenkatesh

**Comment by chetandg123** [comment]
Tested the file processing of the main_metrics.zip, main_metrics.json file is generated in the output folder

**Comment by htvenkatesh** [comment]
@chetandg123 is it working as expected? if so please close this

**Comment by chetandg123** [comment]
@htvenkatesh @padmanabha1234 defect is resolved and it is working as expected
