### ISSUE TITLE
Midday meal issues(Major)

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#566]
Go to textbook distribution report 
-Click on midday meal program present in the  left side menu 
**_Issue :_** Navigation from textbook distribution page to midday meal report is not happening, but in url it is showing as midday meal

![Image](https://user-images.githubusercontent.com/89445054/195556078-181969a8-4847-4049-99ac-ae83ad893567.png)

**_ISSUE 2_:** Legend issue
                     Same number is displaying for all colour legend

![Image](https://user-images.githubusercontent.com/89445054/195562256-f5f91bc7-ca64-4e3b-9604-c802a5aa7219.png)

**Comment by htvenkatesh** [comment]
@devu1454 can u add the estimated completion time for this before call

**Comment by htvenkatesh** [comment]
@devu1454 in ur absence today  I am re assigning this to Inchara to check this.
@Inchara98 FYI, please test this and update the estimated time

**Comment by Inchara98** [comment]
Navigation from textbook to midday meals is happening
