### ISSUE TITLE
Midday meal issue

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#567]
-  Mouse hover on lo table 
issue: Tooltip showing html tag

- Download button allignment issue

![Image](https://user-images.githubusercontent.com/114054046/195557099-6a6060d8-6908-4013-a1c0-2953e0a0e4f1.png)

- Both the tabs names are same 

![Image](https://user-images.githubusercontent.com/114054046/195558321-d1bba31c-4907-42fd-8929-ce0f44f5008d.png)

- Blocks and clusters in the dropdown are in bold letters

![Image](https://user-images.githubusercontent.com/114054046/195562371-5570fedc-caf0-40fe-8705-110f73fedc65.png)

**Comment by RNarmatha** [comment]
@pandutibil , Please update the status of this ticket

**Comment by dhanush-2397** [comment]
@RNarmatha We will take this later as we do not have data source in dev.

**Comment by TanushreeSG** [comment]
Issue 1: Undefined is displaying in tooltip 


![Image](https://user-images.githubusercontent.com/114054046/200269067-e50a9427-cd6e-4779-8ef0-1cef7e8103de.png)


Issue 2: Resolved
Issue 3: Resolved

**Comment by padmanabha1234** [comment]
@TanushreeSG @chetandg123
For midday meal data_source their won't be any subject details.

@htvenkatesh FYI

**Comment by dhanush-2397** [comment]
@chetandg123 Instead of undefined , No data text will be shown for subject column when the data is not present.
Please take a re-test.

**Comment by chetandg123** [comment]
@TanushreeSG can u re-deploy the latest ui code in demo6 machine and take re-test on this defect

**Comment by TanushreeSG** [comment]
Working as expected

![Image](https://user-images.githubusercontent.com/114054046/200472596-ca2b6d32-b3a1-41ea-a556-35bbfa13f8b3.png)
