### ISSUE TITLE
Tab names are same in the textbook distribution

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#568]

**Comment by RNarmatha** [comment]
@chetandg123 , could you please provide proper description for this ticket

**Comment by chetandg123** [comment]
@htvenkatesh For Textbook distribution 
- In main_metrics.json file ->
"Sr. No.": null,
      "Sequence Number":18,
      "Index Number":1,
      "Program":"Textbook Distribution",
      "Program ID":"textbook-distribution",
      "Program Information":"Textbook Distribution",
      "Metric Type":"Key Metric",
      "Metric Name":null,
      "Metric Value":null,
      "Metric Information":null,
      "Navigation URL":"\/textbook-distribution",
      "Image URL":"cQube_logo.jpg",
      **"Menu Name":"Textbook Distribution"**
@Sharathnaik38 is saying that he is taking 
**hamburger menu button name referring - Menu Name value 
For Tabs also referring same - Menu Name value** 

That's why both tab names are the same.

**Comment by chetandg123** [comment]
@dhanush-2397 please check with @pandutibil or @Sharathnaik38 and give update here

**Comment by dhanush-2397** [comment]
@pandutibil Can you please look into this issue.

**Comment by pandutibil** [comment]
@chetandg123 please review the tab names given in the database table from which we are retrieving the tab information for the configurable data sources

**Comment by chetandg123** [comment]
@pandutibil re-tested this defect is resolved , working as expected
