### ISSUE TITLE
2 Factor Auth - at scanning page scroll bar is required

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#569]
**Issues:** When a user enters to 2F auth scanning page not able to see the OTP input box and submit button 

Please find the screen - the scroll bar is required for earlier release we have that feature 
**if the user is 100% of resolution he can't able come down to the OTP input box** 

![Image](https://user-images.githubusercontent.com/64146636/195753463-0959e1aa-e9dd-465b-8f18-c67dfccfc398.png)

**if the user reduces his screen resolution to 80% then he can able see the input and submit buttons **

![Image](https://user-images.githubusercontent.com/64146636/195753635-ebc53c3b-cabc-4964-9f58-43da5c018b19.png)

**Comment by htvenkatesh** [comment]
@chetandg123 can u change the ticket status and reassign to respective developer
And who ever is working, please add the target completion before taking up

**Comment by htvenkatesh** [comment]
@chetandg123 u raised this ticket 20mins before, but the target completion is set on Oct13th hw is this possible?

**Comment by htvenkatesh** [comment]
@chetandg123 can u take a retest this today? If not please add the estimate and change the date

**Comment by chetandg123** [comment]
@htvenkatesh @FaizanMohammed326 re-tested the defect it is resolved in the scanning screen we are able to scroll down the screen (scrolling functionality implemented ) 



![Image](https://user-images.githubusercontent.com/64146636/196094012-2eeba244-9d9f-47cc-b655-e7097d254f62.png)
