### ISSUE TITLE
Configuration of the metric for the new Data Sources - Percentage

### ISSUE THREAD

**Issue by krishnakr6** [Sunbird-cQube/community#57]
Python logic is written to create queries to calculate the percentage for the specified columns from the configuration file.

The columns in the configuration file should be filled as below to get the percentage in the metric

The **metric type** should be specified as **percentage**.
The columns need to be considered for percentage should be mentioned under **ref_columns** in that the first column will be considered as nominator and the second column will be considered as denominator.
The result metric column will be named as the name mentioned under **result metric**.

**Comment by JalajaTR** [comment]
Completed the development for calculating percentage from the configuration file.

**Comment by devu1454** [comment]
Completed the Funtional testing of percentage metrics. Working as expected
