### ISSUE TITLE
Azure - Dashboard is not showing menu options and cards

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#572]
Azur - processed main_metrics file and in output having main_metrics.json file but UI dashboard showing empty 

![Image](https://user-images.githubusercontent.com/64146636/195793125-7bb5a51b-b21c-4685-8e16-ed1c3b8e5540.png)

**Comment by FaizanMohammed326** [comment]
Its related to Azure storage , need some time to analyze , will look into it first thing monday morning.

**Comment by htvenkatesh** [comment]
@pandutibil any update on this?

**Comment by htvenkatesh** [comment]
@chetandg123 @pandutibil @asifbasha61 is it fixed or not yet? wts the issue?

**Comment by chetandg123** [comment]
@htvenkatesh back to back getting issues please inform development team to do the proper unit test and release to testing 


@asifbasha61 again we getting error 


![Image](https://user-images.githubusercontent.com/64146636/196399509-8f8e5ad6-9015-4bf8-8591-33be4a8fd502.png)

**Comment by asifbasha61** [comment]
@htvenkatesh This issue is dependent on #624.

**Comment by asifbasha61** [comment]
@htvenkatesh Changed the dependent variables as either true or false and pushed the code.
@ayesha-siddiq123 Please do a unit testing and update to @chetandg123 if the bug is resolved.

**Comment by htvenkatesh** [comment]
@chetandg123 is this retested?

**Comment by ayesha-siddiq123** [comment]
@htvenkatesh am doing the complete flow of unit testing, will update to @chetandg123
