### ISSUE TITLE
No data is displaying in user engagement tab

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#573]
No data is displaying in user engagement tab (Courses)

![Image](https://user-images.githubusercontent.com/114054046/195827369-5fefc9f6-84d5-480b-9311-d3c8eed95f6e.png)

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and needs to be analysed.

**Comment by ananya-jain1** [comment]
@htvenkatesh - request you to address this issue.

**Comment by RNarmatha** [comment]
Course program we haven't taken up for the current version
