### ISSUE TITLE
Login - on enter OTP screen -> refresh without entering - directly navigating to home

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#574]
login with a newly created admin user or report viewer by scanning 2 factor 
- again login with the user when the OTP screen shows - refresh the screen 
Actual Screen - Home screen showing 
Expected Screen - OTP screen should be displayed

**Comment by htvenkatesh** [comment]
@FaizanMohammed326 @Sharathnaik38 while you taking up this please add the target completion date

**Comment by FaizanMohammed326** [comment]
May be something in routing to be changed. will take a look on monday.

**Comment by htvenkatesh** [comment]
@FaizanMohammed326 is it completed?

**Comment by chetandg123** [comment]
@htvenkatesh @FaizanMohammed326 
I have done re-testing of the defect, and it is not resolved, and again new defect occurred 
**New Issue:** After creation of new users (admin and report viewer) try to login with credentials
- enter the user name and password then click on login button 
**- Scanning screen is not showing instead of showing OTP screen** 


![Image](https://user-images.githubusercontent.com/64146636/196168978-0ec16a1f-b524-42fc-9ec2-11a4e28be3b3.png)

**Comment by htvenkatesh** [comment]
@FaizanMohammed326 have u checked this issue?

**Comment by FaizanMohammed326** [comment]
yes @htvenkatesh need to push the code.

**Comment by chetandg123** [comment]
@htvenkatesh @FaizanMohammed326 Re-tested the defect is not fixed, when on the OTP screen do the refresh 
Actual result: Login Screen displayed
Expected result: OTP Screen display

**Comment by chetandg123** [comment]
@FaizanMohammed326 retested the defect is **Resolved** 

@htvenkatesh for one point here that 
- **when the user is on the scanning page/OTP page if he does the refresh then he will navigate to the login screen please add this point in the release document**

**Comment by RNarmatha** [comment]
Issue is fixed
