### ISSUE TITLE
Admin Console not yet supported on Azure

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#576]
Azure storge is not supported on Admin Console yet. Functionality needs to be implemented.

As of now the understanding is this will need
- Work on the node server side: implementing the storage abstraction module already developed for nVSK and glueing it in into v3.7 app server side
- Work on the NiFi processing side: development already completed, unit tests pending

**Comment by satendrapalsingh** [comment]
@devu1454 , @Inchara98, @chetandg123 - Please confirm everything else (except Admin Console) works with Azure storage and the number of pending Azure test cases/scenarios (test cases yet to be executed).

@htvenkatesh , @krishnakr6 , @asifbasha61 , @padmanabha1234 , @JalajaTR - FYI

**Comment by satendrapalsingh** [comment]
@devu1454 Please test the Azure flow test cases and raise the defects for the development team to work on.

@htvenkatesh - FYI

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and needs to be analysed.

**Comment by ananya-jain1** [comment]
@htvenkatesh @ChakshuGautam - request you to mention your inputs here.

**Comment by Shruti3004** [comment]
Tracked in #753
