### ISSUE TITLE
move files generated through configuration( data processing config file) to  AWS S3 or on-premise or AZURE blob storage instead of storing in cQube installed instance/machine. 

### ISSUE THREAD

**Issue by krishnakr6** [Sunbird-cQube/community#578]
**Current design** : Files are generated through data processing configuration are stored in the instance/machine where cQube is installed.
**Proposed design**: move  all files generated by data processing configuration to AWS S3 or on-premise or AZURE blob storage instead of storing in cQube installed instance/machine.

**Comment by krishnakr6** [comment]
@htvenkatesh @satendrapalsingh @RNarmatha @vijayatgh FYI

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and needs to be analysed.

**Comment by ananya-jain1** [comment]
This is covered as part of the v5.0 roadmap for cQube. Here is the [link](https://project-sunbird.atlassian.net/jira/software/c/projects/CQ/boards/117/roadmap) to the roadmap.
