### ISSUE TITLE
Configuration of the metric for the new Data Sources - cumulative 

### ISSUE THREAD

**Issue by krishnakr6** [Sunbird-cQube/community#58]
Python logic is written to create queries to calculate the cumulative sum for the specified column from the configuration file.

The columns in the configuration file should be filled as below to get the cumulative sum in the metric

- The metric type should be specified as **cumulative**.
- The column need to be considered for cumulative sum should be mentioned under **ref_columns**.
- The result metric column will be named as the name mentioned under **result metric**

**Comment by devu1454** [comment]
Completed the Funtional testing of cumulative metrics. Working as expected

**Comment by JalajaTR** [comment]
Completed the development to calculate the cumulative sum by reading the configuration file
