### ISSUE TITLE
state name variable is missing in config file

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#580]
Aws,Onpremise,Azure config file

state_name variable is missing
state_code: HR
state_name: UP
if we do not give state_name in the config file then we are getting an error at TASK [reference-visualization: copying maps script] as HR.json error
note:- state_name - is missing from config.yml

**Comment by htvenkatesh** [comment]
@FaizanMohammed326 have u completed this?

**Comment by htvenkatesh** [comment]
@TanushreeSG please take a retest on this and update the ticket

**Comment by TanushreeSG** [comment]
working as expected
