### ISSUE TITLE
Configurability enhancements - Aggregation section

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#581]
Add validations to the Aggregation section data to support more robust configurability.

The following tickets are part of this main ticket:
- [x] #586 
- [x] #587 
- [x] #589 
- [x] #590 
- [x] #591

**Comment by RNarmatha** [comment]
This issue will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
This is related to cQube v4.1 beta
