### ISSUE TITLE
Dashboard build issue when doing onpremise installation

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#583]
Getting this error while doing onpremise installation 

![Image](https://user-images.githubusercontent.com/114054046/196106134-924e4ef4-bf09-484a-b256-e1db06bb9986.png)

**Comment by asifbasha61** [comment]
A variable in the config file has been repeated twice due to which angular failed build the code.
Modified the ansible env file and pushed the code to repo.

**Comment by htvenkatesh** [comment]
@asifbasha61 thanks, @TanushreeSG please recheck this issue and update it asap, as its a blocker

**Comment by TanushreeSG** [comment]
Retested again getting same error

![Image](https://user-images.githubusercontent.com/114054046/196159679-9da1a5d4-b3ec-4ad1-bf38-6714cfb41410.png)

**Comment by htvenkatesh** [comment]
@asifbasha61 pls check this wts the issue

**Comment by TanushreeSG** [comment]
@htvenkatesh @asifbasha61 It was a pull issue. I have retested again, now its working as expected.
