### ISSUE TITLE
Configurability enhancements - table_1_trans section

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#584]
Add validations to the table_1_trans section data to support more robust configurability.

The following tickets are part of this main ticket:
- [x] #594 
- [x] #595 
- [x] #596 
- [x] #597 
- [x] #598 
- [x] #599 
- [x] #600 
- [x] #601 
- [x] #602 
- [x] #603 
- [x] #604 
- [x] #605

**Comment by RNarmatha** [comment]
This issue will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
This is related to cQube v4.1 beta
