### ISSUE TITLE
Configurability enhancements - type_of_data section

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#585]
Add validations to the type_of_data section data to support more robust configurability.

The following tickets are part of this main ticket:
- [x] #606 
- [ ] #607 
- [ ] #608 
- [ ] #609 
- [ ] #610
- [ ] #611 
- [ ] #612

**Comment by RNarmatha** [comment]
This issue will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
These are addressed in the current version
