### ISSUE TITLE
Configuration of the NIFI,DB & Visualization for the new Data Sources - scatter plot

### ISSUE THREAD

**Issue by krishnakr6** [Sunbird-cQube/community#59]
- [ ] Development
- [ ] Integration Test
- [ ] https://github.com/Sunbird-cQube/community/issues/64

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and needs to be analysed.

**Comment by RNarmatha** [comment]
Scatter Plot not included in the current version
