### ISSUE TITLE
Aggregation - validate select_columns & group_by_columns

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#590]
Verify the select_column and  group_by_columns columns in the aggregation section by providing the different values
Ex : select_column = school_id
group_by_columns = school_id , textbook_name,grade,subject,academic_year,distribution_date,month in the aggregation section.

_Note - Main ticket #581_

**Comment by RNarmatha** [comment]
This issue will be addressed in cQube v5.0.
