### ISSUE TITLE
Report - validate table_1_trans, type_of_data, etc.

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#593]
Fill table_1_trans,  type_of_data, aggregation, report and invalid (Lo table) report type in the visualization section
Ex : Lo table

_Note - Main ticket #582_

**Comment by RNarmatha** [comment]
This issue will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
This is related to cQube v4.1 beta
