### ISSUE TITLE
type_of_data - verify the nifi_select_columns column

### ISSUE THREAD

**Issue by satendrapalsingh** [Sunbird-cQube/community#611]
Verify the nifi_select_columns column in the type_of_data section by providing the invalid value.
Ex : nifi_select_columns  = dummy_nifi_column

_Note - Main ticket #585_

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
This was addressed bu introducing the plugins but in the current version Plugins are not used
