### ISSUE TITLE
create cqube 4.0-beta Release notes

### ISSUE THREAD

**Issue by krishnakr6** [Sunbird-cQube/community#613]
cQube 4.0-beta Release Notes Document should contain the below list of items

- [x] Overview about cQube 4.0-beta.
- [x] Installation and Upgradation features
- [x] New Features 
- [x] Bug fix details

**Comment by krishnakr6** [comment]
v4.0-alpha release notes - draft
https://docs.google.com/document/d/1NtCcX9C17ZrvEr9gH8VcHMe1HfixKr1em2LRC2OpNKM/edit?usp=sharing

**Comment by krishnakr6** [comment]
# cQube - Release V 4.0-beta - draft ( in progress )

#### Document Release Version

|Project    |Release Date    |Release Version|
|---------|----------------|------------------|
|cQube    |  Oct 2022 |V 4.0-beta    |

## Overview

cQube v4.0-beta  has improved features and bug fixes.

## Upgradation Features from cqube-4.0-alpha

[Upgrade process](https://github.com/Sunbird-cQube/cQube_Edu/blob/cqube-v4.0-beta/README.md)

## New Features Included

**1. Database backup**

User can configure the DB backup during Installation.
Based on the configuration, the database(Postgre DB) will be backed up and stored in input storage.

For more details on Database backup refer this.

[Database backup setup document](<@asif to share the gdoc link>)

**2. Download Report option is added for the below data sources**

    1. Nishtha
    2. Diksha-ETB
    3. Micro-Improvements
    4. PM Poshan
    5. NAS
    6. UDISE+
    7. PGI
    8. Nipun Bharat
    9. NCERT Quiz
    10. NCF


**3. Full screen option is added for the below data sources**

    1. School Infrastructure
    2. Student Performance
    3. Attendance
    4. Courses
    5. Energised Textbook Usage
    6. Other Diksha Metrics
    7. CRC Visit
    8. Composite reports across metrics
    9. Progress card
    10. Exception List
    11. Telemetry 


## Data processing config file validator service

Data processing configuration can be  validated and users can get the success and error messages in the log file.
which ensures a valid data processing configuration file.

**4. Newly added  Summary statistics for the below Data sources**

    1. diksha_etb_etb-coverage
    2. diksha_etb_learning-session
    3. diksha_etb_plays-per-capita
    4. diksha_etb_program-started
    5. diksha_etb_qr-coverage
    6. diksha_nishtha_consumption-by-course
    7. diksha_nishtha_consumption-by-district
    8. diksha_nishtha_percentage-enrollment-certification
    9. diksha_nishtha_program-started
    10. diksha_nishtha_tot-courses-medium
    11. diksha_quiz-started-plan
    12. diksha_quiz_program-started
    13. diksha_quiz_state-participation
    14. main_metrics
    15. micro-improvement_all-dashboard
    16. micro-improvement_district
    17. nas_all-dashboard
    18. nas_program-started
    19. ncf_all-dashboard
    20. nipunbharat_content-consumption
    21. nipunbharat_lo-covered-by-textbook
    22. pgi_all-dashboard
    23. pgi_program-started
    24. pgi_state-wise-performance
    25. pm-poshan_access-across-india
    26. pm-poshan_state-onboarded
    27. udise-all-dashboard
    28. udise_program-started
 
## Bug Fixes

[Bug fixes](https://github.com/orgs/Sunbird-cQube/projects/5/views/3?filterQuery=label%3A%22From-v4.0-Alpha%22+status%3A%22QA+Complete+%F0%9F%91%8C%F0%9F%8F%BD%22)





@htvenkatesh @RNarmatha @satendrapalsingh @vijayatgh FYI

**Comment by htvenkatesh** [comment]
@surendrasinghs Please look into the release document and provide the comments if any on this. Based on that to be shared to Sukpreeth tomorrow

**Comment by surendrasinghs** [comment]
@krishnakr6 @htvenkatesh the release notes should cover
1. All the capabilities offered - broadly. For example, builtin dashboards and configurability.
2. Details of capabilities, For example, for builtin dashboards, 
   1. Specify the data format in which data needs to be sent/emitted
   2. Configuration to enable/disable any dashboard
3. Similarly, for example, for configurability
   1. Available processing steps through configurability
   2. Limitations
   3. Some working examples

I believe many of the existing documents can be leveraged to communicate these (sharing them separately). It's important for people to know what is it and what is it not.

**Comment by krishnakr6** [comment]
Update with release notes and added to gitbook
https://cqube.sunbird.org/release-notes/cqube-release-notes-v4.0-beta

**Comment by satendrapalsingh** [comment]
@htvenkatesh - Please review
@krishnakr6 , @RNarmatha FYI

**Comment by RNarmatha** [comment]
It is Live
