### ISSUE TITLE
Access progress card link is not present in the reports

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#619]
To access progress card from each report there is no access progress card link 
Please provide link

**Comment by Inchara98** [comment]
Retested not fixed

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and needs to be analysed.

**Comment by ananya-jain1** [comment]
@htvenkatesh @pandutibil - request you to address this bug with next steps.

**Comment by RNarmatha** [comment]
This program is not considered in the current version
