### ISSUE TITLE
Two factor auth - after scanning and re login with admin and report user is not working

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#620]
Created admin and report viewer user 
- login with newly created user by scanning the QR code first time it works fine again login with user then if we give proper OTP number in the input box and click on submit it is not navigating to next screen

**Comment by htvenkatesh** [comment]
@FaizanMohammed326 have u looked into this ticket?

**Comment by FaizanMohammed326** [comment]
@chetandg123 Code merged pls retest taking the latest code.

**Comment by chetandg123** [comment]
@htvenkatesh @FaizanMohammed326 defect is re-tested working as expected

**Comment by RNarmatha** [comment]
Issue is fixed
