### ISSUE TITLE
Add Tooltip to menu and Autohide the menu on click of item

### ISSUE THREAD

**Issue by htvenkatesh** [Sunbird-cQube/community#622]
Add the tooltip to the side menu bar when it is in collapsible state.
Hide the side menu when user clicks on the menu item 
Use the existing material/ngx-bootstrap library for tooltip implementation.

**Comment by dhanush-2397** [comment]
@htvenkatesh Completed the task and its ready for QA.

**Comment by TanushreeSG** [comment]
Working as expected
