### ISSUE TITLE
FLN Reports to be added and give proper name

### ISSUE THREAD

**Issue by htvenkatesh** [Sunbird-cQube/community#623]
Hi Suren,
This ticket with respect to FLN items discussed.
Please let us know what are the required tab/report names to be used respectively and location of the reports in which module it is part of.

**Comment by surendrasinghs** [comment]
Both the reports need to be put under the FLN dashboard. I am proposing their names as "Module-wide status" and "Detailed status". These two will be placed before the existing reports already present in FLN dashboard. @htvenkatesh @pandutibil

**Comment by htvenkatesh** [comment]
Thanks @surendrasinghs 
@pandutibil Please note this and make required changes

**Comment by pandutibil** [comment]
@htvenkatesh working on it

**Comment by htvenkatesh** [comment]
@pandutibil if its done pls move for QA

**Comment by pandutibil** [comment]
@devu1454 please test this issue

**Comment by devu1454** [comment]
Module-wide status and Detailed status reports are displaying in the Nipun bharath


![Image](https://user-images.githubusercontent.com/57621682/197136000-b3b9087b-8450-4085-ab82-6fd455d65f14.png)
