### ISSUE TITLE
Azure National Installation Failed at TASK [reference-visualization : Building reference visualization dashboard script]

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#624]
When doing azur national installation -> stopped at TASK [reference-visualization: Building reference visualization dashboard script] 

![Image](https://user-images.githubusercontent.com/64146636/196368822-93ccdc71-f269-4c33-9086-4158df1e2a9e.png)

![Image](https://user-images.githubusercontent.com/64146636/196368644-7c45b89b-16e8-4de6-851b-9c57170da0be.png)

**Comment by asifbasha61** [comment]
Added the required parameters to the env files for both local and public installation.

**Comment by chetandg123** [comment]
@htvenkatesh @asifbasha61 pulled latest code and again getting failed at TASK [reference-visualization : Configure the environment.ts] ******************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'NA' is undefined"}


![Image](https://user-images.githubusercontent.com/64146636/196393503-8fc5a5f4-2d2c-4716-aaeb-0a78ae90154e.png)

**Comment by htvenkatesh** [comment]
@asifbasha61 wts happening on this? why are we not able to close?

**Comment by asifbasha61** [comment]
@htvenkatesh diksha columns were configured earlier with true or false, But now for national we are using 'NA' so need @Sharathnaik38 to check this issue further.

**Comment by htvenkatesh** [comment]
@asifbasha61 @Sharathnaik38 lets have a call and discuss this after huddle

**Comment by asifbasha61** [comment]
@htvenkatesh  Changed the dependent variables as either true or false and pushed the code.
@ayesha-siddiq123 Please do a unit testing and update to @chetandg123 if the bug is resolved.

**Comment by ayesha-siddiq123** [comment]
@htvenkatesh doing the complete flow of unit test. will update to @chetandg123

**Comment by ayesha-siddiq123** [comment]
@chetandg123  @asifbasha61 unit test is done and the bug is resolved. please take the retest.

**Comment by ayesha-siddiq123** [comment]
@chetandg123 unit test is done. please take the retest.

**Comment by chetandg123** [comment]
@htvenkatesh @ayesha-siddiq123 defect is retested , it is resolved
