### ISSUE TITLE
change AZURE_STORAGE_CONNECTION_STRING to AZURE_STORAGE_CONN_STR in node api side

### ISSUE THREAD

**Issue by asifbasha61** [Sunbird-cQube/community#625]
.env file will be reading azure_storage_connection_string as AZURE_STORAGE_CONN_STR
change AZURE_STORAGE_CONNECTION_STRING to AZURE_STORAGE_CONN_STR in node api core/config file

**Comment by FaizanMohammed326** [comment]
@htvenkatesh I'm working on this

**Comment by htvenkatesh** [comment]
@chetandg123 is this tested?

**Comment by chetandg123** [comment]
@htvenkatesh @FaizanMohammed326 @asifbasha61  defect is retested now it is working fine after installation all the services are online without showing error 


![Image](https://user-images.githubusercontent.com/64146636/196859411-81dd657f-dd5b-4cd3-b065-fda1c79571e2.png)

**Comment by RNarmatha** [comment]
Fixed
