### ISSUE TITLE
Issues in admin console (onpremise)

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#630]
- After changing the password page is not redirecting to login page 
- Data replay is not working 
- Diksha summary rollup periodic selection is not working

**Comment by Sharathnaik38** [comment]
@htvenkatesh and @asifbasha61 for keyclock host missing the port please provide port localhost:8080 for onprime

![Image](https://user-images.githubusercontent.com/90701833/196610667-9b3ce2bf-4f94-4313-981d-46e6306c11fb.png)

**Comment by htvenkatesh** [comment]
@asifbasha61 please check this

**Comment by asifbasha61** [comment]
updated keycloak host variable in the env files in core api and admin api and pushed the code.

**Comment by Inchara98** [comment]
-After changing the password page is not redirecting to login page - This issue resolved

**Comment by htvenkatesh** [comment]
@Inchara98 @asifbasha61 wts the update on this ticket?

**Comment by Inchara98** [comment]
@Sharathnaik38 @htvenkatesh Diksha summary rollup periodic selection is not working rest two are working as expected

**Comment by TanushreeSG** [comment]
After changing the password page is not redirecting to login page -  **Resolved**
Data replay is not working - **Resolved**
Diksha summary rollup periodic selection is not working - **Retested not fixed**
Issue-  After clicking submit button alert box showing as a diksha summary periodic selection is succesfully submitted then click on ok button again we are getting error alert

**Comment by padmanabha1234** [comment]
@Sharathnaik38 python code is working please check

**Comment by Sharathnaik38** [comment]
@TanushreeSG please retest Diksha summary rollup

**Comment by TanushreeSG** [comment]
@Sharathnaik38 Retested not fixed

![Image](https://user-images.githubusercontent.com/114054046/197111262-59ea12a6-3b7c-4047-8eea-7665dba192f6.png)

**Comment by padmanabha1234** [comment]
@FaizanMohammed326  python code is working fine. Please check into this issue

**Comment by htvenkatesh** [comment]
@FaizanMohammed326 @padmanabha1234 wts the update on this ticket?

**Comment by devu1454** [comment]
Still disksha summary-rollup error message is displaying


![Image](https://user-images.githubusercontent.com/57621682/197692856-a6849691-7a90-4e89-8e00-5960caa2ab23.png)

**Comment by devu1454** [comment]
1.After changing the password page is not redirecting to login page (Working as expected)
Data replay is not working (Checked for infra and teacher attendance working as expected)
Diksha summary rollup periodic selection is not working (still error message is showing)


![Image](https://user-images.githubusercontent.com/57621682/197714910-25a8224c-3ec0-49f4-8d9d-d7b83d036a5c.png)

**Comment by FaizanMohammed326** [comment]
earlier due to missing exit code from pythion script, the node api was being held in pending state, due to which this issue was raised. So need to discuss with @Sharathnaik38 and find a work around to fix the issue.

**Comment by devu1454** [comment]
@FaizanMohammed326 @dhanush-2397 Re-deployed the latest code and tried to access the admin console.
Issue : admin console page is not working.


![Image](https://user-images.githubusercontent.com/57621682/198528815-18d6f1ed-93e7-46cd-bb3e-efcfe6905b92.png)

**Comment by RNarmatha** [comment]
@FaizanMohammed326 , Please work on this ticket and post  the comment

**Comment by Inchara98** [comment]
@FaizanMohammed326  retested not fixed

**Comment by FaizanMohammed326** [comment]
@Inchara98 Pls retest it. Its working now.

**Comment by Inchara98** [comment]
@FaizanMohammed326 It is not working 


![Image](https://user-images.githubusercontent.com/89445054/199680324-834508f0-346e-4b88-b2a0-bcf7a1c563e3.png)

**Comment by RNarmatha** [comment]
@FaizanMohammed326  Please look into this ticket as priority

**Comment by FaizanMohammed326** [comment]
@RNarmatha  the above issue is solved, but once we use diksha summary rollup not able to perform other actions in admin console. I have found the root cause, need to discuss with @htvenkatesh for a proper solution.

**Comment by Inchara98** [comment]
Admin console is working need to retest diksha summary rollup

**Comment by Inchara98** [comment]
retested working as expected
