### ISSUE TITLE
Azur - Textbook distribution configuration is not processing

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#631]
Textbook distribution.zip is not processed in the configure data source processor 

File is emitted to -> configure_datasource

**Comment by htvenkatesh** [comment]
@padmanabha1234 did u take a look on this?

**Comment by padmanabha1234** [comment]
@htvenkatesh 
chetan is re - testing on this.

**Comment by chetandg123** [comment]
@htvenkatesh @padmanabha1234 
re-tested the defect is not fixed 
after emission of textbook_distribution.zip to configure_source folder is not processed and 
in the **/opt/cqube/emission_app/python/ not having postgress folder** 


![Image](https://user-images.githubusercontent.com/64146636/196860283-012963d9-4f5c-4847-8f85-71c365a7ba9c.png)

**Comment by devu1454** [comment]
@chetandg123 Please take a re-test

**Comment by chetandg123** [comment]
@htvenkatesh @devu1454 @padmanabha1234 re-tested the textbook distribution is not fixed after emission of textbook_distribution_data.zip to textbook_distribution/ , we are getting error in validate_datasource please find the below screen shot for your reference 


![Image](https://user-images.githubusercontent.com/64146636/196928200-08e7ed18-6a9b-426e-9d7e-4b3114fecd84.png)

**Comment by chetandg123** [comment]
@htvenkatesh @padmanabha1234 retested the defect it is resolved , textbookdata.zip is processed without any issues , checked with db and output files also generated for the textbook distribution report

**Comment by RNarmatha** [comment]
Issue is fixed
