### ISSUE TITLE
pre signed url is not generating in on premise

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#635]
Ingestion api - onpremise
url is not generating in postman

**Comment by htvenkatesh** [comment]
@Shoaib15khan is this done?

**Comment by Shoaib15khan** [comment]
yes @htvenkatesh

**Comment by htvenkatesh** [comment]
@Shoaib15khan can u reassign this ticket for testing?

**Comment by Inchara98** [comment]
@Shoaib15khan  Retested not fixed
curl: (7) Failed to connect to localhost port 80: Connection refused

**Comment by htvenkatesh** [comment]
@Shoaib15khan wts the update on this?

**Comment by Inchara98** [comment]
url is generating and working as expected
