### ISSUE TITLE
Tooltip issue in student performance

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#636]
html tag present in tooltip 
Student performance(Periodic Assesment Test LO-Table)

![Image](https://user-images.githubusercontent.com/114054046/196664363-a90a118c-84e8-47b0-bde7-8ced483172ee.png)

**Comment by devu1454** [comment]
@dhanush-2397 still i can see that tooltip information is showing in a single line.


![Image](https://user-images.githubusercontent.com/57621682/198248095-ea1837c6-a6e7-4626-b1d1-31d26435fbeb.png)

**Comment by dhanush-2397** [comment]
@devu1454 Please take a re-test for the above ticket

**Comment by chetandg123** [comment]
TDD
1. After installation of cQube Application , process the statics files (district , block , cluster , school master , management , subject details , grade details data files ) to the static data processor and check whether db also updated with respective the table with information - **Pass/Fail** 
2. Process the Periodic Assessment data file - **Pass/Fail** 

- [ ] Periodic Assessment exam master file 

- [ ] Periodic Assessment question master file 

- [ ] Periodic Assessment Trans file 
3. Check whether after processing each files 
- Postgress - verify periodic_assessment_exam_mst , periodic_assessment_qst_mst and periodic_assessment_result_trans tables are updated with records or not - **Pass/Fail** 
4. Check whether output files are generated or not in side the pat folder in the output bucket - **Pass/Fail**
5. Login to the cQube application with admin or report viewer user - **Pass/Fail**
6. Click on the cQube Dashboard -> Click on School Performance menu button from dashboard - **Pass/Fail**

**Comment by chetandg123** [comment]
@htvenkatesh @dhanush-2397  Re-tested the tooltip information alignment issues is resolved please find the below screen shot for the reference 



![Image](https://user-images.githubusercontent.com/64146636/198927279-89eae1bc-54c6-493d-9247-a8695a6c9dd7.jpg)

**Comment by RNarmatha** [comment]
This issue is completed and closed by QA Team
