### ISSUE TITLE
System Testing

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#638]
1. Azure installation(State) (Chetan)
- [x] Installation
- [x] Ingestion_api
- [x] Data processing 
- [x] Visualization

2. Azure installation(National) (Chetan)
- [x] Installation
- [x] Data processing 
- [x] Visualization

3. S3 installation(State) (Devaraja)
- [x] Installation
- [x] Ingestion_api
- [x] Data processing 
- [x] Visualization

4. S3 installation(National) (Devaraja)
- [x] Installation
- [x] Data processing 
- [x] Visualization

5. On-premise installation(State) (Inchara)
- [x] Installation
- [x] Ingestion_api
- [x] Data processing 
- [x] Visualization

6. On-premise installation(National) (Inchara)
- [x] Installation
- [x] Data processing 
- [x] Visualization

**Comment by chetandg123** [comment]
System testing is completed

**Comment by RNarmatha** [comment]
Completed
