### ISSUE TITLE
Regression Testing

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#639]
Regression Testing (Inchara & Tanushree)

1.Azure 
- [x] Visualization(National)
- [x] Visualization(State)

2.S3 
- [x] Visualization(National)
- [x] Visualization(State)

3.On-premise
- [x] Visualization(National)
- [x] Visualization(State)

**Comment by chetandg123** [comment]
Regression testing - completed the all ui reports end to end functionalities test

**Comment by RNarmatha** [comment]
Completed
