### ISSUE TITLE
Azure - district master file processing is not working - through ingection api

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#640]
Using Ingection api -> emitted the district master file to the azur emission container 
- File is present in emission container and input container and after starting the static data transformer processor then getting error in cQube data storage 

![Image](https://user-images.githubusercontent.com/64146636/196857719-4c3967b5-1a17-4cde-9c5f-4870aeaae9df.png)

**Comment by padmanabha1234** [comment]
@Shoaib15khan their is an error while unzipping a file from emission bucket through ingestion API. Please look into this

@chetandg123 @htvenkatesh @krishnakr6 FYI

**Comment by chetandg123** [comment]
@htvenkatesh this defect is going to archive because @Shoaib15khan said that which he given code to test the api ingestion presigned url not for processing

**Comment by RNarmatha** [comment]
Issue is fixed
