### ISSUE TITLE
cqube-qa8-output displaying in string format and input files are showing

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#641]
1.Click on admin console
2.Click on Download s3 files
3. Choose cqube-qa8-output bucket from dropdown list

Issue : output bucket name is displaying quotes

![Image](https://user-images.githubusercontent.com/57621682/196866286-7491089f-0062-4fc7-88cb-2287be03c4b0.png)

**Comment by htvenkatesh** [comment]
@devu1454 is it for s3 or azure storage test?

**Comment by devu1454** [comment]
Working as expected
