### ISSUE TITLE
Diksha summary-rollup Periodic Selection is not working(s3)

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#642]
1. Select from date
2. Select to date
3. select time selection as 1 hour
4. click on submit
Issue : not working 

![Image](https://user-images.githubusercontent.com/57621682/196867575-255f6f92-9e0b-4019-89fe-8a53aba3faf1.png)

**Comment by Sharathnaik38** [comment]
@devu1454 this is issue with NIFI for all storage type in informed to padmanaba to check this

**Comment by htvenkatesh** [comment]
@padmanabha1234 have u checked this?

**Comment by padmanabha1234** [comment]
@Sharathnaik38 python code is working please check

**Comment by devu1454** [comment]
Diksha_transformer_custom is working working but still the error message is showing

**Comment by htvenkatesh** [comment]
@dhanush-2397 can u look into this?

**Comment by htvenkatesh** [comment]
@padmanabha1234 wts the update on this ticket?

**Comment by padmanabha1234** [comment]
@htvenkatesh I am working on the python code

**Comment by FaizanMohammed326** [comment]
earlier due to missing exit code from pythion script, the node api was being held in pending state, due to which this issue was raised. So need to discuss with @Sharathnaik38 and find a work around to fix the issue.

**Comment by devu1454** [comment]
TDD for diksha summary rollup

1.cQube Installation with storage_type as s3. **(Pass)**
   Exp Outcome : cQube must be installed successfully without errors and successful message should be shown on the console
 
2.Diksha_transformer_custom data source should be configured **(Pass)**
    Exp Outcome : diksha_tansformer_custom process status  is stopped and invalid components is 0

3.Static_files should be process in the nifi.**(Pass)**
   Exp Outcome : district_mst, block_mst, cluster_mst, school_master, school_management and diksha_enrolment files must be processed in the nifi and records must be stored in the db.

4.Diksha files should be process in the nifi. **(Pass)**
   Exp Outcome : diksha_tpd_mapping file must be processed in the nifi and data should be stored in the db.

5.Diksha_data_summary file should be emitted to emission data storage.**(Pass)**
    Exp Outcome : diksha_data_summary file must be present in the emission data storage.

6.Select From date, To date and stopping hour as 1 hour and click on submit in the configuration( ie : Login to cQube -> Click on admin_console ->Click on configurations) **Fail**
  Exp Outcome : 
                           1.Diksha summary roll-up successfully initiated alert message should be shown,
                           2. Diksha_transfomer_custom processor should be in running state
                           3. Nifi should pick the file from emission data storage and make a raw copy in the input data storage.
                           4. Nifi should process the file and records should be inserted into the db
                           5. Nifi should generate the output files.
                           6. Data must be displayed on DIksha UI reports.

**Comment by devu1454** [comment]
Admin console is not working after deployment of latest code.


![Image](https://user-images.githubusercontent.com/57621682/198564191-6611fd21-949f-44ce-9549-daf2e869210f.png)

**Comment by chetandg123** [comment]
Task is paused due to dependency of issue #688

**Comment by chetandg123** [comment]
Deployment of latest code is failing at 


![Image](https://user-images.githubusercontent.com/64146636/199436097-459e122b-24e6-46cb-ab3e-05cbcca2449b.png)

**Comment by chetandg123** [comment]
@pandutibil @FaizanMohammed326 in s3 not able to go inside the admin console screen we are getting errors in console , refer the screen shot for the reference 



![Image](https://user-images.githubusercontent.com/64146636/199463291-500f4299-f1ba-4c52-ab7b-212a1fbe9cdf.png)

**Comment by devu1454** [comment]
Re-deploying the latest code and testing the issue.

**Comment by devu1454** [comment]
stopped the re-testing of this issue. Due to the issue in diksha_enrolment file processing.

**Comment by devu1454** [comment]
After deployment of latest code. Admin console is not working 


![Image](https://user-images.githubusercontent.com/57621682/199916883-a395bf8f-996a-417f-afab-17c7b222dc3b.png)

**Comment by devu1454** [comment]
@padmanabha1234 Nifi is not feching the diksha_data_summary file.

**Comment by devu1454** [comment]
Working as expected
