### ISSUE TITLE
Tooltip is not showing for VSK maps

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#643]
Tooltip value is not showing for vsk maps

![Image](https://user-images.githubusercontent.com/57621682/196874801-405fb88e-a369-4d25-9e8c-00ecbafabad8.png)

**Comment by pandutibil** [comment]
@devu1454 Issue fixed please retest

**Comment by devu1454** [comment]
Working as expected

**Comment by devu1454** [comment]
Re-tested not fixed

**Comment by htvenkatesh** [comment]
@pandutibil wts the update on this?

**Comment by pandutibil** [comment]
@htvenkatesh @devu1454 

It's loading correctly now



![Image](https://user-images.githubusercontent.com/76088803/197681567-49383011-8a90-43f3-83f0-6b117d4364f8.png)

**Comment by htvenkatesh** [comment]
@pandutibil can u move for QA

@devu1454 can u verify this and close if its working

**Comment by devu1454** [comment]
working as expected
