### ISSUE TITLE
Issue in National(onpremise)

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#644]
1.Bar graph is displaying only after selecting state from the dropdown

![Image](https://user-images.githubusercontent.com/89445054/196912439-9ee26630-b175-4dc7-b2d4-7b6382373343.png)

![Image](https://user-images.githubusercontent.com/89445054/196912579-3548c9d1-b3de-41ef-9b89-9d81c694b56f.png)

2.Diksha image icon is displaying for Microimprovements and quiz program in side menu

3.Guage charts are not displaying in Diksha reports

![Image](https://user-images.githubusercontent.com/89445054/196993871-6289aa97-1060-4017-a0fb-5d3c27957fab.png)

**Comment by htvenkatesh** [comment]
@pandutibil wts the update on this ticket?

**Comment by pandutibil** [comment]
@Inchara98 
1. Actually there is no state filter for the VSK installation. If you're checking in your local, then you need to set the installation type as state. I've checked in the demo 1 instance an the report is loading fine. Please let me know if you're still facing the same issue.
2. We just need to update the main metrics configuration file with proper image URLs.
3. As the datasource files are missing for gauge chart reports, the reports are not loading. @devu1454 uploaded the missing files. You can check in the demo 1 instance and now the reports are loading fine.

**Comment by Inchara98** [comment]
Working as expected
