### ISSUE TITLE
Validation error while installation

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#648]
1. If access type as national,  Valdiation is not happening for management 
2. if access type as state, Valdiation is not happening for below config elements
  2.1  slab1: 33 
         slab2: 30-65 
         slab3: 60-75
         slab4: 70
         Issue : error message is not proper

**Comment by ayesha-siddiq123** [comment]
@devu1454 updated the slab validations. resolved the bug, please pull the latest code and test.

**Comment by devu1454** [comment]
slab error message is properly displaying
