### ISSUE TITLE
core reports are not loading (onpremise)

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#650]
After processing of data, reports are not loading

**Comment by dhanush-2397** [comment]
@Inchara98 code is merged. Please re-test

**Comment by Inchara98** [comment]
@htvenkatesh  @Sharathnaik38 retested not fixed


![Image](https://user-images.githubusercontent.com/89445054/197133388-d0ec14b5-f032-452f-9639-40c2b7b262ca.png)

**Comment by devu1454** [comment]
core reports are working as expected
