### ISSUE TITLE
Login is not happening(s3)

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#651]
Provided the valid username and password and tried to login to cqube
Issue  Login is not happening

![Image](https://user-images.githubusercontent.com/57621682/197105698-591a6490-9e58-41a7-ac72-bca484335024.png)

**Comment by pandutibil** [comment]
@devu1454 API end point is configured in a wrong way in config.yml. Please correct it and deploy the changes.

**Comment by devu1454** [comment]
Working as expected
