### ISSUE TITLE
Azur - After latest code deployment - all cQube core -2 reports showing no data found

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#652]
before deployment all report showing data , after latest code deployment by Oct 20 time- 10pm done with latest deployment , 
**Issue** - all cQube core -2 reports -> showing no data found 

Note: output folder having all data sources files

**Comment by pandutibil** [comment]
@chetandg123 please test the issue

**Comment by chetandg123** [comment]
@pandutibil tested the dynamic date for cQube core -2 reports , done with file processing now in UI on each report dashboard 
example: 
Education Official - processed data on 21 Oct 2022 but in UI showing - 17 Oct 2022 
and all other dashboards also .

**Comment by chetandg123** [comment]
All report are showing data
