### ISSUE TITLE
Azur - admin console -> conversion of diksha tpd and etb api to emission is not working

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#654]
Tring to change diksha tpd and etb from api to emission 
Issue: alert is showing error 

![Image](https://user-images.githubusercontent.com/64146636/197131003-1fa02494-97ee-433d-a946-bf30513e2955.png)

**Comment by chetandg123** [comment]
Defect is working now due to admin console api issue is not worked earlier 



![Image](https://user-images.githubusercontent.com/64146636/197149336-1a418d8b-2c96-4c01-8fe1-839e1deec411.png)

**Comment by RNarmatha** [comment]
Issue is fixed
