### ISSUE TITLE
Issues in tab name and downloaded reports(NVSK)

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#655]
Nipun bharath
- Tabs name and downloaded report name are not same

![Image](https://user-images.githubusercontent.com/114054046/197140582-29b40249-aada-4278-8d12-f41536c7c74e.png)

- Download report and data in the map are not same

PGI(State wise performance and district wise performance)
- In download report all metric data is displaying instead of displaying only selected metric value

![Image](https://user-images.githubusercontent.com/114054046/197142783-797b8ac8-f548-4bb3-83d4-946aa5dc124c.png)

PGI -> District wise performance -> download report does not contains district names in the download file

![Image](https://user-images.githubusercontent.com/114054046/197148876-8bbbc460-ae1e-4ceb-beca-a4fa43607280.png)

Diksha->Learning session 
Tooltip name and downloaded report name are not matching

![Image](https://user-images.githubusercontent.com/114054046/197151174-48740eb6-1bf2-4440-b848-c229c8482a79.png)

 Udise
- Tabs name and downloaded report name are not matching
- In download report all metric data is displaying instead of displaying only selected metric value

PM poshan (progress status)
- Data of selected metric is not displaying in the downloaded report 

- state name is not present in downloaded report

![Image](https://user-images.githubusercontent.com/114054046/201669312-8f5c1a47-08fb-4b70-975a-bcfb386071e9.png)

**Comment by htvenkatesh** [comment]
@TanushreeSG lets move this to minor and take it in next sprint

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and needs to be analysed.

**Comment by ananya-jain1** [comment]
Hey @htvenkatesh @pandutibil - request you to have a look at this issue and include in sprints to be taken up in February.

**Comment by RNarmatha** [comment]
NVSK programs  is in the Road Map we haven't start the development. Once it is started we will be evaluating.

**Comment by RNarmatha** [comment]
NVSK programs is in the Road Map we haven't start the development. Once it is started we will be evaluating.
