### ISSUE TITLE
Azur - Diksha_data_summary file processing is not happening

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#656]
Emitted the diksha tpd enrolment file to diksha_enrolment folder , file is not processing in static data processor

**Comment by krishnakr6** [comment]
Azure support  is not implemented in the below code.
https://github.com/Sunbird-cQube/cQube_Edu/blob/cqube-v4.0-beta/processing/datasource/python/diksha_enrolment_file_split.py

@Shoaib15khan add the azure support here.

**Comment by chetandg123** [comment]
@htvenkatesh @padmanabha1234 @Shoaib15khan emitted the diksha_data_summary_UP_76dis.zip file to Diksha folder , nifi processing is not happening

**Comment by htvenkatesh** [comment]
@padmanabha1234 @Shoaib15khan wts the update on this ticket?

**Comment by devu1454** [comment]
@htvenkatesh re-tested this issue, still nifi is not picking the file from emission data storage

**Comment by devu1454** [comment]
Re-tested this issue, Still nifi is not picking the diksha_data_summary adn diksha_tpd file

**Comment by murali003** [comment]
@devu1454 you have checked older version can you please take latest updated code and re-test.

**Comment by devu1454** [comment]
@murali003 Installed the updated code and checked the data processing of diksha files. Still i am unable to process the diksha_data_summary.zip file

**Comment by murali003** [comment]
Task:
1. Emit the diksha_data_summary enrolment file to diksha_enrolment folder
azure: diksha_data_summary file should be pick from emission bucket
2. once it's pick the file all validation should be happen

Expected Result:
1. Data should be updated in database table
2. In log_summary folder, log_summary_diksha.json file to be generated

**Comment by RNarmatha** [comment]
@chetandg123  Please do the retest.

**Comment by chetandg123** [comment]
Task is paused due to dependency of issue #688

**Comment by chetandg123** [comment]
@padmanabha1234 diksha tpd enrolment file processing is not working 


![Image](https://user-images.githubusercontent.com/64146636/199432876-55d4ae83-6e81-4c2f-8cd7-44b90438304c.png)

**Comment by Shoaib15khan** [comment]
@chetandg123  issue is resolved . please take a retest on it. @RNarmatha FYI.

**Comment by chetandg123** [comment]
@htvenkatesh Diksha all files are processed and we are able to see the ui report with data
