### ISSUE TITLE
Download report issues

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#658]
**Nishtha** 
- Table name in downloaded report is different (In report it is program name and in downloaded report it is program)**Implementation status** 

![Image](https://user-images.githubusercontent.com/89445054/197465717-ae31177b-2db9-4069-a771-82bcfecf03fa.png)

- Table name in downloaded report is different (Target achieved enrolment is missing in downloaded report) - **% against potential** 

![Image](https://user-images.githubusercontent.com/89445054/197465875-2b7edae6-0d2f-4de3-aa32-fe28bc4a1c09.png)

- **District wise status tab** downloaded report name is displaying as course wise status 

![Image](https://user-images.githubusercontent.com/89445054/197466896-466608a9-89dd-4612-9062-fb0fe17502e8.png)

**Diksha**

**ETB coverage status and content coverage on QR**

- Classes are not coming in order in downloaded report of **ETB coverage status and content coverage on QR**

![Image](https://user-images.githubusercontent.com/89445054/197467803-cd5f5183-a5eb-447c-a58a-e3c7430d21d8.png)

- Content coverage on QR tab downloaded report name is displaying as report data

![Image](https://user-images.githubusercontent.com/89445054/197468325-6b7bda1e-49c3-4104-b052-eb2504ecc368.png)

- Table name in downloaded report is different (In report it is  total number of learning session and in downloaded report it is total number of plays)**Learning session**

![Image](https://user-images.githubusercontent.com/89445054/197469989-5bd4131f-ef09-475b-998a-676e2568cf2e.png)

**Pm Poshan**
- Selected metric data is not displaying in downloaded report **Progress status**

**NAS**

District names are not dislaying in downloaded report - **District wise status**

**UDISE**
- District names are not dislaying in downloaded report- **District wise performance**
- PTR metric data is not displaying in downloaded report - **District wise performance**
![Image](https://user-images.githubusercontent.com/89445054/197471388-f32cafab-ec3c-46d1-8a1b-6e701ae03c30.png)

**PGI**

District names are not displaying in downloaded reports

**Comment by TanushreeSG** [comment]
retested not fixed

**Comment by TanushreeSG** [comment]
percentage symbol is not present in downloaded report - Correlation(udise+)
![Image](https://user-images.githubusercontent.com/114054046/200559945-9cbb1218-fa2c-434d-8c68-8186d203c15a.png)
