### ISSUE TITLE
No blocks are displaying in block dropdown

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#659]
Teacher Attendance exception

No blocks are displaying in block dropdown 

![Image](https://user-images.githubusercontent.com/89445054/197476268-839927a8-b2d2-4aa5-a83f-1a96d864b481.png)

**Comment by Inchara98** [comment]
Retested not fixed

**Comment by PavitraIR** [comment]
@devu1454  There is a issue in the static data some of block_id and block_name are missing.

**Comment by devu1454** [comment]
@PavitraIR Ok, We will re-check this issue once again
