### ISSUE TITLE
Map is not loading in PM Poshan (onpremise)

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#660]
Config file state name = UP
PM Poshan map report  is not loading

![Image](https://user-images.githubusercontent.com/89445054/197493741-b9bf3cde-42d7-4348-be4b-b941b47b4761.png)

**Comment by pandutibil** [comment]
Missing information of UP state in the data source. Handled it with No Data Message instead of showing it as an error.

**Comment by devu1454** [comment]
No data is displaying
