### ISSUE TITLE
State name is displaying as Uttarkhand

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#661]
In Config file state name = UP
In learning session on potential user map report state name is displaying as Uttarkhand in tooltip

![Image](https://user-images.githubusercontent.com/89445054/197494657-2cccfae7-d133-4e30-87b2-f8b273d7e688.png)

**Comment by pandutibil** [comment]
@devu1454 Please update the state code for Uttar Pradesh in the datasource according to the state master

**Comment by devu1454** [comment]
Working as expected
