### ISSUE TITLE
Regression Defect - Udise tooltip information having empty

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#662]
if any indices do not value then it should be shown as 0 instead of showing empty 
example:
Actual Value:-  ICT Lab: 
Expected Value:-  ICT Lab: 0 

![Image](https://user-images.githubusercontent.com/64146636/197496442-184ed38e-4f94-495c-b97e-3ba16495f45e.png)

**Comment by Inchara98** [comment]
Retested not fixed

**Comment by chetandg123** [comment]
@dhanush-2397 Re-tested not fixed , still some of indices are showing without 0 if value is not present 


![Image](https://user-images.githubusercontent.com/64146636/201051523-502dd1ca-3dc2-4df8-8cf6-117d2723c5fc.png)

**Comment by chetandg123** [comment]
Re-tested the defect now working as expected

**Comment by RNarmatha** [comment]
This issue is fixed and closed
