### ISSUE TITLE
Regression Defect - Student attendance Report

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#663]
- Select the option from choose year dropdown and Download Academic Year Data link text is displayed in blue color - should be displayed in black color or else same as the color given to click on trend link text
- Click on trends link text is not aligned properly

![Image](https://user-images.githubusercontent.com/64146636/197496339-3b04a380-f0c6-4cff-a86c-34a312f0cc43.png)

![Image](https://user-images.githubusercontent.com/64146636/197496164-5ea5abea-5abc-469b-a91c-de44f63e2554.png)

**Comment by chetandg123** [comment]
- [ ] Select the option from choose year dropdown and Download Academic Year Data link text is displayed in blue color - should be displayed in black color or else same as the color given to click on trend link text - not fixed 

- [ ] Click on trends link text is not aligned properly - Resolved



![Image](https://user-images.githubusercontent.com/64146636/200553344-bfc66ff5-4d71-4e6e-aed1-5790dee6efd6.png)

**Comment by dhanush-2397** [comment]
@chetandg123 Download Academic Year data link text color is changed. Please take a re-test.

**Comment by chetandg123** [comment]
Re-Tested the defect - **Resolved**


![Image](https://user-images.githubusercontent.com/64146636/200785193-6af04e68-3d55-43be-bca6-a9b618d49b80.png)
