### ISSUE TITLE
Regression Defect - usage by content course report

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#665]
Usage by content course:
------------------------

- [x] Download raw file link text is not aligned properly 

- [ ] Select district dropdown having others as district 

![Image](https://user-images.githubusercontent.com/64146636/197497566-9023c4b9-0430-46fa-81af-0576f81bab2d.png)

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and to be analyzed

**Comment by ananya-jain1** [comment]
@htvenkatesh @pandutibil - request you to address this bug with next steps.

**Comment by RNarmatha** [comment]
These issues are fixed in the current version and this program not taken for the current version
