### ISSUE TITLE
Regression Defect - Course Progress Report

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#666]
Course Progress:
----------------

- [ ] Choose course dropdown having more width 

- [ ] if select the last 30 days option from the time range, if does not have data then should be displayed as 'No data found' or 'No data available' instead of showing an empty screen

- [ ] if any heat chart cell does not tooltip (white empty cells) does not show any tooltip earlier cQube 

![Image](https://user-images.githubusercontent.com/64146636/197497990-1990b94d-bb2c-46cb-8bc7-be06612854ab.png)

![Image](https://user-images.githubusercontent.com/64146636/197498069-71031be0-0b24-4a8e-803b-10f75f856fc4.png)

![Image](https://user-images.githubusercontent.com/64146636/197498986-b674cff4-357c-45cf-bc2b-fd5c77fa01b1.png)

![Image](https://user-images.githubusercontent.com/64146636/197498994-6ca24b17-f4dd-44ef-86a3-64fe17828dfe.png)

**Comment by chetandg123** [comment]
- [ ]  Choose course dropdown having more width - **Not Fixed**

 

- [ ] if select the last 30 days option from the time range, if does not have data then should be displayed as 'No data found' or 'No data available' instead of showing an empty screen - Resolved

 

- [ ] if any heat chart cell does not tooltip (white empty cells) does not show any tool tip earlier cQube - Not Fixed

**Comment by chetandg123** [comment]
Retested defects 
 

- [ ] Choose course dropdown having more width - **Resolved**

- [ ]  if any heat chart cell does not tooltip (white empty cells) does not show any tool tip earlier cQube - **Resolved**

**Comment by RNarmatha** [comment]
This issue is fixed and closed
