### ISSUE TITLE
Regression Defect - User Progress Report

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#668]
User Progress:
--------------
- The download Report button is not aligned properly 
- Select any program ( Kalarava) - mouse hover on any bar tooltip -> %Enrolled showing more than 100. 
- Select time ranges except over -> others showing no data found so the error message is not aligned properly in the single line

![Image](https://user-images.githubusercontent.com/64146636/197499547-52844fc2-851f-4fe6-8459-6eda841dc09f.png)

![Image](https://user-images.githubusercontent.com/64146636/197499727-3ca3570a-834d-4e49-aaf1-5c472a155888.png)

**Comment by pandutibil** [comment]
Issue 1 - fixed the alignment
Issue 2 - More than 100%, I think it is as expected
Issue 3 - Only overall data is there, that's why only overall data is loading.

**Comment by RNarmatha** [comment]
@chetandg123 What is the update on this issue 3 ?

**Comment by chetandg123** [comment]
@RNarmatha please find the below update on this defect 

**Defect 1 :** For Download button alignment is **not fixed** for 100% of browser resolution 


![Image](https://user-images.githubusercontent.com/64146636/200739811-75d4407a-664e-408d-8d4a-a9132b7363ab.png)

**Defect 2** - More than 100%, I think it is as expected - Already discussed with @pandutibil and @htvenkatesh  enrolled may be more then 100% also 

**Defect 3 -** Only overall data is there, that's why only overall data is loading. - **Not fixed**

@padmanabha1234 In qa6 bucket - summary data file having data of 3rd Nov 2022 so when we select last 90 , 30 days it should the data on UI 



![Image](https://user-images.githubusercontent.com/64146636/200740428-c1ad92f1-e5cc-4961-8ea1-b63c7046fcb1.png)

**Comment by padmanabha1234** [comment]
@dhanush-2397 time_periods data is generated in the output bucket. Please look into this issue.

**Comment by dhanush-2397** [comment]
@padmanabha1234 Please add files to cqube-qa6-output bucket.

**Comment by padmanabha1234** [comment]
@chetandg123 Please emit the diksha_enrollment file with latest enrollment date, completion date and process it

**Comment by chetandg123** [comment]
@RNarmatha @padmanabha1234 QA machine we are providing to you only verify or find out the route cause of issue , please use your development server

**Comment by chetandg123** [comment]
@RNarmatha @htvenkatesh 

me and @murali003 Re-processed the latest data set for diksha tpd which is having date as enrollment and completion date as 1/11/2022 and 12/11/2022 now we are able to see all time periods data except last day because 12th is not occures in last day 

this defect is resolved and working as expected
