### ISSUE TITLE
Regression Defect - TPD GPS of learning Report

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#669]
Course - GPS Of Learning 
-----------------------------------
- Click on any leged cards map is not showing properly 
- Select Avg Time Spent option from the dropdown, map markers information having avg time spent value is not working with legend cards 
example - refer to screenshot showing 83mins 23 secs if click on the 0.43 - 149.002 legend button then the markers are not showing it comes between 0.43 to 149.002

![Image](https://user-images.githubusercontent.com/64146636/197500157-9ed4b31d-7720-460a-b44b-590429d37368.png)

![Image](https://user-images.githubusercontent.com/64146636/197500233-48f407ce-cb97-4110-8328-c10f2cacd184.png)

![Image](https://user-images.githubusercontent.com/64146636/197500503-bce37fd9-84a9-4ff6-a7f5-da32a7746f86.png)

**Comment by FaizanMohammed326** [comment]
in issue 1 , in the new implmentation of map reports, we are zooming the map automatically to the markers present in the map. so when there is only one marker the map will be zoomed in around it.

**Comment by chetandg123** [comment]
Re-tested this defect - **Resolved**
