### ISSUE TITLE
Regression Defect - User Engagement Report

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#670]
User Engagement
-------------------------
- Report showing no data available 

![Image](https://user-images.githubusercontent.com/64146636/197500893-e8383317-4cc9-46de-b246-f9a0ec9ca662.png)

**Comment by devu1454** [comment]
@padmanabha1234 below files are generated with null. Please check the issue.
diksha/hbar/course/district.json
diksha/hbar/course/state.json

**Comment by chetandg123** [comment]
Retested the defect - it is Resolved 

![Image](https://user-images.githubusercontent.com/64146636/200231003-deb5ee3b-8a2d-4b4e-9707-b039dceac65f.png)

**Comment by RNarmatha** [comment]
This issue is fixed and closed
