### ISSUE TITLE
Regression Defect - User Onboarding Report

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#671]
User onboarding
---------------
- select program, course, and select districts showing no data available then the dropdown is not showing complete options 
- Selection of district wise showing no data available 
scenario  - select program or course after that select districts 

![Image](https://user-images.githubusercontent.com/64146636/197501275-0ba8c523-cbf2-4184-8583-0ff2da50573e.png)

**Comment by chetandg123** [comment]
@FaizanMohammed326 @padmanabha1234 above defect is fixed ? have you done unit test ?

**Comment by padmanabha1234** [comment]
@chetandg123 The data is their in the output file.

**Comment by chetandg123** [comment]
@htvenkatesh re-tested this defect - working as expected

**Comment by RNarmatha** [comment]
The issue is fixed
