### ISSUE TITLE
Regression Defect - Usage by textbook Report

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#672]
usage by Textbook:
------------------
- Select any time range and click on the download report button - downloaded CSV file name is not proper according to a selection of period for example: 
Actual for last 30 days: usage_by_course_all_24-10-2022.csv
Expected for last 30 days: usage_by_course_last_30_days_24-10-2022.csv

- Total-Content Plays: 61,421 should be displayed in the right corner instead of center

![Image](https://user-images.githubusercontent.com/64146636/197501683-b96544b1-9bef-4169-9896-914303f197a3.png)

**Comment by chetandg123** [comment]
Re-Tested not fixed

**Comment by dhanush-2397** [comment]
@chetandg123 Please take a retest.

**Comment by chetandg123** [comment]
ReTested the above defects are **Resolved**
