### ISSUE TITLE
Regression Defect - gps of learning tpd and etb reports

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#673]
Dial Resouce - GPS Of learning 
------------------------------
- Click on any leged cards map is not showing properly 

![Image](https://user-images.githubusercontent.com/64146636/197502096-437449d2-8d63-46f0-aef5-3ccb4a75e712.png)

**Comment by chetandg123** [comment]
Usage outside state info is not showing  in both TPD and ETB usage of GPS 


![Image](https://user-images.githubusercontent.com/64146636/200566017-42ea9a04-159b-4140-8ac8-feb4c44872f7.png)

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and to be analyzed

**Comment by ananya-jain1** [comment]
@htvenkatesh @pandutibil - request you to address this bug with next steps.

**Comment by RNarmatha** [comment]
Dial Resource program is not consider in the current version
