### ISSUE TITLE
Regression Defect - Usage Per Capita Report

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#674]
Dial Resouce - Usage Per Capita
-------------------------------
- Click on any leged cards map is not showing properly
- Usage Outside State:-
Total-Content Plays: 
is not showing the value 

![Image](https://user-images.githubusercontent.com/64146636/197502410-8bd22227-0a9d-4f19-b289-3cd52f389be4.png)

**Comment by Inchara98** [comment]
Same issue in GPS of learning (Dail resource usage) 


![Image](https://user-images.githubusercontent.com/89445054/200565776-c710d41e-d3e0-47db-895e-092b86c6cdaf.png)

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and to be analyzed

**Comment by ananya-jain1** [comment]
@htvenkatesh @pandutibil - request you to address this bug with next steps.

**Comment by RNarmatha** [comment]
In the current version this report is not consider
