### ISSUE TITLE
Regression Defect - Content Preference Report

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#675]
Content Preference
-------------------
- Click on the Download Report button, file is not downloaded 
- Select the state with the district option and click on the download report button, file is not downloaded

**Comment by chetandg123** [comment]
@dhanush-2397 Re-tested above two defects are not working  ( After Clicking download report button - csv file is not downloaded )

**Comment by chetandg123** [comment]
@dhanush-2397 
i clicked on download report button (on load report) i am not able to download the csv file 


![Image](https://user-images.githubusercontent.com/64146636/200741352-f98782ce-e994-41bd-b968-d216ecaaeef4.png)

Select state with district option from dropdown and clicked on download report - csv file is not downloading 


![Image](https://user-images.githubusercontent.com/64146636/200741455-2b6d42bf-42ed-4476-aab8-e64e2fd672b9.png)

Select any 10 districts from dropdown and click on submit , then click the download report - csv file is not downloading 


![Image](https://user-images.githubusercontent.com/64146636/200741617-56321e93-8009-4a1f-9c62-846d0f56228d.png)

**Comment by dhanush-2397** [comment]
@chetandg123 Please take a re-test.

**Comment by chetandg123** [comment]
@RNarmatha @dhanush-2397 
Re-tested the defect - **Resolved** - now working as expected able to download csv file in all the levels.
