### ISSUE TITLE
Progress card issue

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#676]
Click on submit button
Progress reports are not displaying

![Image](https://user-images.githubusercontent.com/89445054/197503303-3e4ae717-a12d-4d5c-8ad8-8a26c0b5fb9c.png)

**Comment by FaizanMohammed326** [comment]
Test Cases: 
    1. Need to check when submit button is clicked without selecting any location details, whether home function is called again to display the on load details again, if not after alert message need to call the home function.

Outcome Expected: 
    On click of submit button without selecting any location details, after alert message, basic/home details should displayed again instead of empty screen.

**Comment by Inchara98** [comment]
working as expected
