### ISSUE TITLE
Regression textbook_distribution

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#677]
### Textbook_distribution lo report defects.

1.**If no data in the table report, Then the data display section becomes small.** 

2.year and month
  Choose Year(2022-23)
  Choose Month(September)
  Choose Week(5)
  Choose Date(2022-09-30)
  Change the grade from 3 to all grades
  **Issue : reset is happening and re-directing to overall**

3.Choose default week selection is not happening

4.year and month
  Choose Year(2022-23)
  Choose Month(September)
  Choose Week(5)
  **Issue : tooltip showing district name as undefined**

5.year and month
  Choose Year(2022-23)
  Choose Month(September)
  Choose Week(5)
  Choose Date(2022-09-30)
  Choose Grade(4)
  Choose Subject(english)
  Choose District(Agra)
  Choose Block(Acchnera)
  Choose Cluster(Arrua Khash)
  **Issue : grade is showing as 0, subject is showing as grade_4 and download filename is not proper(textbook_undefined_distribution_Grade_4_schools_of_cluster_915020008_September_2022-23_24-10-2022)** 

6.Blocks and cluster names are bold

7.Download filename is not proper
 ex: textbook_undefined_distribution_Grade_4_schools_of_cluster_915020008_September_2022-23_24-10-2022

8.Choose TimeRange(last 30 days)
Choose Grade(Grade_5)
Choose Subject(maths)
Choose District(Agra)
Choose Block(Acchnera)
Choose Cluster(Arrua Khash)
Change the time range from last_30_days to last_day
**issue : data is displaying but last_day we don't have data**

### Textbook_distribution map report defects.

1.Click on textbook-distribution map report 
   Click on legend
   **issue : gray color markers are showing** 
2.Choose TimeRange(last 30 days)
   Choose Grade(Grade_3)
   Choose a subject(english)
  **issue : Footer value is mis matching at subject level, district,block and cluster level** 

2.Choose TimeRange(last 30 days)
   Choose Grade(Grade_3)
   Choose a subject(english)
   Choose a district(agra)
   Choose a block( Acchnera)
   Choose a cluster
  **issue : Legend values are showing as 0 for district, block and cluster selection** 

3.Choose TimeRange(last 30 days)
   Choose Grade(Grade_3)
   Choose a subject(english)
   Choose a district(agra)
   Click on cluster, schools button
  **issue : disabling of buttons is not happening and footer value is not proper total schools showing 0**

4.Downlod report names are not proper
   ex: textbook_distribution_allDistrict_undefineds_25-10-2022.csv

5.Choose TimeRange(overall)
   Choose Grade(Grade_3)
   Choose a subject(english)
   Choose a district(agra)
   Choose  TimeRange(last_day)
   **Issue : No data found is not displaying**

6.Click on textbook_distribution map tab
   Click on textbook_distribution lotable
   Click on textbook_distribution map tab
   Issue : legend, about discription and footer values is not displaying

**Comment by Inchara98** [comment]
Textbook map report : 
Size of the block ,cluster ,school button is large when compared to other reports

**Comment by chetandg123** [comment]
@RNarmatha 
Re-tested the above defects are all - **Not Fixed** except 
6.Blocks and cluster names are bold - **Resolved**

**Comment by chetandg123** [comment]
**Defect 7:** when we select grade and subject - legend card showing 0 for all the buttons

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and to be analysed

**Comment by ananya-jain1** [comment]
@htvenkatesh @pandutibil - request you to address this bug.

**Comment by RNarmatha** [comment]
Text book distribution program not consider in the current version
