### ISSUE TITLE
NAS,UDISE & PGI  districtwise performance tooltip is not displaying

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#678]
1.Mouse over on the nas districtwise perforamce report.
Issue : tooltip is not showing
2.Mouse over on the udise districtwise perforamce report.
Issue : tooltip is not showing
3.Mouse over on the pgi districtwise perforamce report.
Issue : tooltip is not showing

**Comment by pandutibil** [comment]
Updated district ids in the UP state geojson according to the usecase(datasource).

**Comment by pandutibil** [comment]
@devu1454 Please retest the scenario

**Comment by devu1454** [comment]
Working as expected

**Comment by RNarmatha** [comment]
Completed
