### ISSUE TITLE
Knowledge Training for cQube

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#680]

**Comment by Shoaib15khan** [comment]
KT has been given to sharmashbee , Ramya R and Tinu NS.
We have completed
Architecture,
Each UI report wise data source explanation,
Configuration in cQube,
File emission process,
Validation process.

**Comment by satendrapalsingh** [comment]
Training completed, assessment tasks WIP.

**Comment by Shoaib15khan** [comment]
Need to complete below concepts in KT.

1. [Installation of cQube ].
2. [data track after processing in Nifi] 
3. [Understanding of Business Logic each datasource wise]

**Comment by RNarmatha** [comment]
Invalid moved to JIRA

**Comment by RNarmatha** [comment]
Training is completed
