### ISSUE TITLE
Exploring on open API to create API's for the configuration

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#681]
Exploring on 

- How open API works
- How to write the API specification using yaml

**Comment by satendrapalsingh** [comment]
Reference ticket as sub-task #684

**Comment by JalajaTR** [comment]
Writing the open  API specification for schema creation and Identifying the other API's required to enable  configurability.

**Comment by RNarmatha** [comment]
This is for Training ticket and it completed
