### ISSUE TITLE
KT on cQube processing part

### ISSUE THREAD

**Issue by JalajaTR** [Sunbird-cQube/community#685]
Topics to be covered under this KT are:
1. Overview of cQube application
2. Architecture of cQube
3. Role of PostgreSQL in cqube
4. Overview on all the Datasources in cQube
5. Processing of the datasources - validations and aggregations
6. Output files generations
7. Configurability in cQube

**Comment by JalajaTR** [comment]
27/10/2022 
Completed the KT on the overview of the cQube application all the existing dashboards which are coming as aggregated data and which are coming as raw data and the understanding on each reports.

**Comment by satendrapalsingh** [comment]
@nstinu Please create and share documentation (reverse-KT) for completed KT session.

**Comment by nstinu** [comment]
Documentation submitted to Jalaja for review.

**Comment by nstinu** [comment]
KT topics completed till 9/11/2022

31/10/2022- On cQube Architecture
07/11/2022- Static DataSources
08/11/2022- Postgresql Concepts:- Upsert, Percentile, Joins, Inner Queries.
09/11/2022- Postgresql Concepts:- Union-Intersection, Constraints, Views, MV's, Indexes

**Comment by RNarmatha** [comment]
Invalid

**Comment by RNarmatha** [comment]
Training Completed
