### ISSUE TITLE
cQube - s3 file is processing is not working for diksha tpd enrolment

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#686]
cQube s3 Installed in demo3 machine 

- Emitted the diksha tpd enrolment file to static data processor while processing it showing error please find the below error message attached below for the reference 

**Issue:** Machine is configured with s3 buckets , here azur related configuration error is showing 

![Image](https://user-images.githubusercontent.com/64146636/199388540-78ae8103-471e-4b35-8d08-588f200ea108.png)

**Comment by devu1454** [comment]
Re-tested working as expected
