### ISSUE TITLE
one step re installation is failed

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#687]
Deployment of latest code is failed please find the screen shot for reference 

![Image](https://user-images.githubusercontent.com/114054046/199393907-5ceba5aa-602c-436e-99bd-17bc7054ce96.png)

One step re installation-Fail

**Comment by ayesha-siddiq123** [comment]
@TanushreeSG modified the validation of config.yml, pull the latest code, and test

**Comment by TanushreeSG** [comment]
for this issue Ayesha asked us to terminate the machine and to do fresh installation @htvenkatesh @RNarmatha  FYI

**Comment by chetandg123** [comment]
@htvenkatesh @RNarmatha 
For all instances if do re-installation we are getting above error 

Solution suggested by @ayesha-siddiq123  - Re-create the machine machine and start fresh installation 

@htvenkatesh we need to discuss with this issue


![Image](https://user-images.githubusercontent.com/64146636/199435440-2cbe8f07-79a8-4abc-b9b2-5e944278c79b.png)

**Comment by chetandg123** [comment]
@RNarmatha defect is re-tested resolved , now working as expected

**Comment by RNarmatha** [comment]
Issue is Fixed
