### ISSUE TITLE
Azur - Re-Installation validation of config.yml task is missing

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#688]
While doing latest code re-installation in azur 

**Issue:** Missing Config.yml file successfully validated 

![Image](https://user-images.githubusercontent.com/64146636/199394399-be06e130-c9e1-46e2-a7b3-1be28df30b39.png)

**Comment by ayesha-siddiq123** [comment]
@chetandg123 modified code for validation of config.yml, unit test also done.
please pull the latest code and test.

**Comment by chetandg123** [comment]
@ayesha-siddiq123 sure

**Comment by chetandg123** [comment]
@ayesha-siddiq123 Re-tested the defect is working as expected
