### ISSUE TITLE
Re installation is paused

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#689]
Re installating is pausing at copying admin api script to base installation directory

![Image](https://user-images.githubusercontent.com/114054046/199647998-575427f9-9996-411b-b831-e32b2e6521d4.png)

**Comment by ayesha-siddiq123** [comment]
@TanushreeSG @chetandg123  checkout to cqube-v4.1-beta branch and pull the latest code and install ui again.
i tested in dev server its not pausing.

**Comment by TanushreeSG** [comment]
@ayesha-siddiq123   by switching cQube-v4.1-beta branch also getting same issue

**Comment by RNarmatha** [comment]
Retest

**Comment by devu1454** [comment]
Re-tested working as expected
