### ISSUE TITLE
Testing v3.7.1

### ISSUE THREAD

**Issue by krishnakr6** [Sunbird-cQube/community#69]
Below are the items covered in functional test
1. Average 
2. Percentage
3. cumulative 

**Note:** Back-end functionality is covered, not UI

**Comment by devu1454** [comment]
Functional testing of average is completed. Working as expected.

**Comment by devu1454** [comment]
Functional testing of percentage is completed. Working as expected.

**Comment by devu1454** [comment]
Functional testing of cumulative is completed. Working as expected.

**Comment by RNarmatha** [comment]
Completed
