### ISSUE TITLE
User engagement page is not loading

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#691]
courses-user engagement page is not loading

![Image](https://user-images.githubusercontent.com/114054046/199705920-bcec16c9-5c0c-4daa-9425-13c84a670783.png)

**Comment by TanushreeSG** [comment]
Data issue

**Comment by chetandg123** [comment]
@FaizanMohammed326  

**tooltip information missing total enrolled value**  - refer downloaded file having total enrolled value is present

![Image](https://user-images.githubusercontent.com/64146636/199886585-1a349941-f705-46c1-bd68-68eec807d756.png)

**Comment by FaizanMohammed326** [comment]
@chetandg123 added total erolled value in the tooltip. pls retest after pulling the latest code.

**Comment by chetandg123** [comment]
@FaizanMohammed326  Re-tested the defect is resolved , now working as expected

**Comment by RNarmatha** [comment]
Issue is Fixed
