### ISSUE TITLE
diksha_enrolment file processing is failed in s3

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#692]
1.Emitted the diksha_enrolment_tpd_up_10dis.zip to s3 emission bucket and tried to process the file through nifi.
 Issue : Error while processing the file

![Image](https://user-images.githubusercontent.com/57621682/199732393-532ce973-ca37-46c5-a7d6-a073f135a5f3.png)

**Comment by Shoaib15khan** [comment]
This issue is same as #656. That is solved

**Comment by devu1454** [comment]
Diksha_enrolment file is processing as expected
