### ISSUE TITLE
Dashboard menu button - tooltip info is not displaying some times

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#693]
Mouse hover on Hamburger menu buttons - tooltip information of about button name is not displaying 
refer screenshots 

![Image](https://user-images.githubusercontent.com/64146636/199907986-262c8f13-aee0-4056-9a30-558c72c31ebf.png)

**Comment by pandutibil** [comment]
@chetandg123 Please retest the issue

**Comment by RNarmatha** [comment]
Issue is fixed
