### ISSUE TITLE
Exception List - Teacher attendance showing no data found

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#694]
Processed the teacher attendance file , teacher attendance exception showing no data found 

![Image](https://user-images.githubusercontent.com/64146636/199909184-e10d24d7-e438-4b44-a917-f7df7d0d0462.png)

**Comment by chetandg123** [comment]
@FaizanMohammed326 @padmanabha1234 above defect is fixed ? have you done unit test ?

**Comment by chetandg123** [comment]
Re-tested the defect is **Resolved** 


![Image](https://user-images.githubusercontent.com/64146636/200747786-76652908-15bb-4ac1-999e-bd4d30900c09.png)

**Comment by RNarmatha** [comment]
The issue is fixed
