### ISSUE TITLE
Azur - PM Poshan - showing no data found

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#695]
PM Poshan Report is showing no data found 

processed the file - pm-poshan_access-across-india.zip
azur cqube-state-output -> pm-poshan_access-across-india.json file 

![Image](https://user-images.githubusercontent.com/64146636/199912823-da680849-40fd-4312-add5-a2eaf4e9393c.png)

**Comment by RNarmatha** [comment]
Issue is fixed
