### ISSUE TITLE
Regression Testing v4.1

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#698]
Regression Testing 

S3 
- [ ] Visualization(State)(Chetan, Inchara & Tanushree)

**Comment by chetandg123** [comment]
Completed Regression testing for below Dashboards 

- [ ] Student Performance 

- [ ] Attendance 

- [ ] Other Diksha Metrics 

- [ ] Exception List 

- [ ] Admin Console (Create user , change password , user list , summary statistics , Monitoring details , Download s3 files )

Found some defects which are already exists in **Regression Defect** tickets

**Comment by TanushreeSG** [comment]
Completed regression testing for below reports

- [ ] Nishtha

- [ ] Diksha-ETB

- [ ] PM Poshan

- [ ] NAS

- [ ] UDISE+

- [ ] PGI 

- [ ] Courses

**Comment by Inchara98** [comment]
Completed Regression testing for below Dashboards

- [ ] School Infrastructure
- [ ] Dial Resource access
- [ ] Education officials
Found few alignment issues

**Comment by chetandg123** [comment]
Completed the Progress card regression testing , found few defects - created ticket with descriptions - #707 and assigned to respective developers 

- [ ] Progress Card

**Comment by chetandg123** [comment]
Completed round of regression testing on cQube reports and admin console

**Comment by RNarmatha** [comment]
Completed
