### ISSUE TITLE
Data processing is not happening in nifi(s3)

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#699]
### Static files data processing  in nifi
Expected outcome 1: Nifi should pick the file from s3 emission bucket and raw copy must be stored in th input bucket. **(Fail)**
                               2: Nifi should process the static data files and records must be stored in the db.
                               3: Log details must be stored in the log_summary table and log_summary.json files must be generated.

**Comment by padmanabha1234** [comment]
@devu1454  Now it is processed! please check

**Comment by devu1454** [comment]
@padmanabha1234 ok. I will re-install and check the issue.
@htvenkatesh FYI

**Comment by devu1454** [comment]
Re-tested working as expected
