### ISSUE TITLE
Choose report dropdown issue

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#701]
**Education Officials (crc)**
One step installation - **Pass**
static file processing - **Pass**
CRC file processing - **Pass**

**Issue1 :** Choose report dropdown is displaying in grey colour 
**Issue2 :** values in the choose report dropdown is displaying in bold letters

**Expected :** Choose report dropdown should not display in grey colour , it should display like other dropdown
                  values in the choose report dropdown should not be in bold letters

![Image](https://user-images.githubusercontent.com/89445054/200557001-d6734192-4e79-4d9a-bdb0-8976c0473f56.png)

**Comment by chetandg123** [comment]
@Inchara98 just do ui deployment in demo3 or demo6 re test the defect

**Comment by Inchara98** [comment]
working as expected 


![Image](https://user-images.githubusercontent.com/89445054/200813039-193e059d-6b97-4c3f-ac13-15191c5b4dfe.png)
