### ISSUE TITLE
No data is displaying in courses

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#702]
Issue 1-Courses (Course progress)
One step installation - Pass
Static file processing - Pass
course report file processing - Pass
Issue : Data is not displaying for last 30 days, last 7 days and last day
Expected : Data should be display for all time ranges
![Image](https://user-images.githubusercontent.com/114054046/200568096-28822445-4647-4b1e-8072-37963a6089df.png)

Issue 2 - Courses(User progress)
One step installation - Pass
Static file processing - Pass
course report file processing - Pass
Issue : Data is not displaying for last 90 days ,last 30 days, last 7 days and last day
Expected : Data should be display for all time ranges

**Comment by FaizanMohammed326** [comment]
There are no files generated for last_30, last_7 and last day time periods. so the no data message is displayed.

**Comment by FaizanMohammed326** [comment]
@padmanabha1234 or @murali003  can u check if data is present for all the timeperiods.

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and needs to be analysed.

**Comment by ananya-jain1** [comment]
> @padmanabha1234 or @murali003 can u check if data is present for all the timeperiods.

@htvenkatesh - can you please address this issue?

**Comment by RNarmatha** [comment]
Course program we haven't consider in the current version . Needs to be analyzed for the upcoming version
