### ISSUE TITLE
PAT LO Table - Table header text should be displayed on center

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#704]
PAT LO Table - Table header text should be aligned to center when we select question id as choose view by word is breaking

**Comment by dhanush-2397** [comment]
@chetandg123  The table headers are aligned to center. If the word is too big then only the first 10 characters of the word will be displayed.
Please take a re-test

**Comment by chetandg123** [comment]
Re-tested the defect is **Resolved** , now working as expected 


![Image](https://user-images.githubusercontent.com/64146636/200784951-6bd7ddd9-9433-42bc-9041-64fb0f046aea.png)
