### ISSUE TITLE
Presigned url is not generating

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#705]
Input :
curl --location --request POST 'https://demo1cqube.tibilprojects.com/data/upload-url' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhRUhEa0FJZkhLbGphYjBUS29nRVdOWlA4WEhPajg5TCIsImlhdCI6MTY2NzkxNzU5Nn0.ailpHWt2IEU56-QAZpDpI0oONkj9sxKrkRcRIetAd1U' \
--header 'Content-Type: application/json' \
--data-raw '{"filename":"district_master/district_mst.zip"}'

Expected Output: presigned url must be generated.

Actual Ouput: An invalid response was received from the upstream server

**Comment by Shoaib15khan** [comment]
Ingestion API script is not executed at the time of installation. @asifbasha61  can you please check .

**Comment by asifbasha61** [comment]
There was a problem with gunicorn service in the machine which has been tested.
I have retested by changing gunicorn version and the current version which in implemented in cqube.
Everything working as expected.

**Comment by devu1454** [comment]
Tested in a new server. Working as expected

**Comment by Shoaib15khan** [comment]
Azure implementation have been removed. @devu1454 please take retest .

**Comment by devu1454** [comment]
Working as expected
