### ISSUE TITLE
Regression Defect - Progress Card Reports

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#707]
**Defect 1:** **Click to Access Report** link text should be shown in blue color instead of black (cQube-3.7 in blue color of link text)  - **Resolved**

**Defect 2:** For 100% Browser resolution - Click to access report link is not aligned properly for below 3 report across all levels of page - **Resolved**

![Image](https://user-images.githubusercontent.com/64146636/200744574-8059f438-7cf6-4f51-a8a7-b1dd6948cfc6.png)

**Defect 3:** When particular district/block/cluster/school level data is not available then UI displaying no data found error message is not aligned properly  - **Resolved**

![Image](https://user-images.githubusercontent.com/64146636/200744727-296e2f93-06f8-4446-87f4-87ea86ac14ca.png)

@padmanabha1234 @PavitraIR 
**Defect 4:** When we choose school from dropdown , school id/name input saying no schools name/id available 

![Image](https://user-images.githubusercontent.com/64146636/200744903-6773074b-bc7a-44c7-afcb-d2a3050b5635.png)

**Comment by chetandg123** [comment]
On CRC Card i-tag info missing **Data from Date and Data upto Date info** - **Minor**


![Image](https://user-images.githubusercontent.com/64146636/200745610-fc7ef515-02ca-4429-8e0b-7f76a317c47a.png)

**Comment by murali003** [comment]
@FaizanMohammed326 data is there in the output bucket please look into it.

**Comment by FaizanMohammed326** [comment]
@padmanabha1234 pls check defect 5 .
 progressCard/school_management_category/overall/overall_category/govt/stateData.json.
the value for data from date and data upto date are both  null.

**Comment by padmanabha1234** [comment]
@PavitraIR Query is returning the null values, please look into this.

**Comment by FaizanMohammed326** [comment]
Defect 1, 2 and 3 are fixed.

**Comment by chetandg123** [comment]
@FaizanMohammed326 Re-tested above defects 
Defect 1 - Resolution issue - **Resolved** 
Defect 2 - Access to Progress card - link color - **Resolved** 
Defect 3 - No data found error alignment issue - **Resolved**


![Image](https://user-images.githubusercontent.com/64146636/201279938-23411840-b604-4b7f-9dcc-a97f3d7f6164.png)



![Image](https://user-images.githubusercontent.com/64146636/201279952-4fc88ac1-4048-4fa2-97b0-85c977352331.png)

**Comment by PavitraIR** [comment]
@chetandg123  The year and month in crc_inspection_trans table and crc_location_trans table doesn't match and in a query we are joining these two tables checking for matching year and month columns.because of this reason,data from date and data upto date are displayed as null.

**Comment by chetandg123** [comment]
@PavitraIR so what is the solution now how do get those value ?

**Comment by PavitraIR** [comment]
@chetandg123 please emit appropriate data file into crc_inspection_trans table and crc_location_trans with proper year and month values along with proper visit_date in location_trans file.

**Comment by RNarmatha** [comment]
The issue is completed
