### ISSUE TITLE
Dropdown allignment issue

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#708]
Student performance
Choose a block and choose a cluster Dropdowns are not alligned properly
![Image](https://user-images.githubusercontent.com/114054046/200766203-a9a09d65-b55f-4491-abc7-393f4d90c06b.png)

Textbook distribution (Textbook distribution LO table and map)

Choose a block and choose a cluster Dropdowns are not alligned properly and font size is different compare to other dropdown
![Image](https://user-images.githubusercontent.com/114054046/201011863-36dd8031-5b14-4426-b054-739d1bfd2c0b.png)

midday meal (both tabs)

Choose a block and choose a cluster Dropdowns are not alligned properly and font size is different compare to other dropdown
![Image](https://user-images.githubusercontent.com/114054046/201015501-1dc85e05-9c6e-4537-aff3-204bfdc0772a.png)

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and needs to be analysed.

**Comment by ananya-jain1** [comment]
@htvenkatesh @pandutibil - request you to include this enhancement in v5.0 as part of February sprints

**Comment by RNarmatha** [comment]
PAT reports are not taken in this version needs to analyzed
