### ISSUE TITLE
Y axis is not displaying properly in Diksha report

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#710]
Y axis is not displaying properly 
Diksha (Learning sessions)

![Image](https://user-images.githubusercontent.com/114054046/201009585-71d97a88-33a6-4e9b-8cd4-1fcf30bcee23.png)

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and needs to be analysed.

**Comment by ananya-jain1** [comment]
@htvenkatesh @pandutibil - request you to include this enhancement in v5.0 as part of February sprints

**Comment by RNarmatha** [comment]
This was taken up in the latest version and UI chagnes are done accordingly
