### ISSUE TITLE
Lo table issue (midday meal )

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#711]
Values in the agra district lo table is not indicating by the colour displaying in the legend

![Image](https://user-images.githubusercontent.com/89445054/201016107-d76e7cff-a12e-4142-9dad-188c3fbdcc55.png)

**Issue 2 :** Choose time range - year and month
month - November 
issue : weeks are not displaying in the select week dropdown

Issue3 : Subject column is displaying in Lo table

**Issue 4:** Choose time range - year and month
month - November 
select 0 week
issue : date is not displaying

![Image](https://user-images.githubusercontent.com/89445054/201261986-034b0c74-929c-481f-9a5f-9a0a536570f8.png)

**Comment by padmanabha1234** [comment]
@dhanush-2397 meta data is updated in output. please look into this

**Comment by dhanush-2397** [comment]
Issues 1 , 2 and 4 are resolved.
Regarding issue 3 the subject column will be shown with no data text.
@htvenkatesh  Fyi this was the implementation discussed before for subject column for Mid day meals.

**Comment by Inchara98** [comment]
Issue 1 , 2 and 4 resolved 

Issue 5 : Selected grade is not displaying in the LO table
