### ISSUE TITLE
Regression Defect - TextBook Distribution Lo & Map

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#712]
TextBook Distribution:
------------------------------
**Defect 1** - Grade options should be not include under score special character between grade and number
Example : 
**Actual Options:** Grade_4 , Grade_5 , Grade_6 
**Expected Options:** Grade 4 , Grade 5 , Grade 6 

**Defect 2** - Subject names should be displayed as in Camel cases in dropdown as well as table and map report
**Actual Options:** hindi , english , mathematics
**Expected Options:** Hindi , English , Mathematics  

**Defect 3** - Time Range options should be display in order wise and in camel cases
Overall
Last 30 Days
Last 7 Days
Last Day
Year and Month

**Defect 4**: Select district and click on download report button 
In CSV file:
**Actual Records:**
Grade|Subject|Acchnera|Etmadpur
Grade_3|Hindi|4|4

**Expected Records:**
District|Block|Grade|Subject|Total_Count
Agra|Acchnera|Grade_3|Hindi|4
Agra|Etmadpur|Grade_3|Hindi|4

**Note:** For all levels - district/block/cluster levels 

**Defect 5 -** **LO Table Title:**
Actual Title : Report On Textbook Distribution Access By Lo For: Uttar Pradesh
Expected Title: Textbook Distribution Access by LO Table For: Uttar Pradesh

**TextBook Map Title:**
Actual Title - Report On Textbook Distribution Access By Location For: Uttar Pradesh
Expected Title - Textbook Distribution Access Report For: Uttar Pradesh

**Comment by FaizanMohammed326** [comment]
Defect 1,2,3 and 5 resolved.

**Comment by chetandg123** [comment]
@htvenkatesh @FaizanMohammed326 
Re-tested the defect please find the below updates 
Defect 1 : **Resolved**
Defect 2 : **Resolved**
Defect 5:  **Resolved** 

Defect 3: 
Time period drop down options for lo table having camel and sorted order but In map report - **Not Fixed**


![Image](https://user-images.githubusercontent.com/64146636/201602974-26f4a7e3-0d88-43a2-aeb1-f7cbc96c1343.png)

**Comment by chetandg123** [comment]
@dhanush-2397 could you please fix above issue (defect 3 - for map time period options should be in camel case and order wise )

**Comment by dhanush-2397** [comment]
@chetandg123 Please retest.

**Comment by chetandg123** [comment]
@htvenkatesh @dhanush-2397 
Re-tested the Defect 3 is **Resolved**

**Comment by RNarmatha** [comment]
Issue is fixed

**Comment by RNarmatha** [comment]
-[]
