### ISSUE TITLE
Regression Defect - When select other academic year option - default month selection is not selected

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#713]
Select year and month option from time period 
- Select another academic year -> month is not selected by default 
**For Periodic Map Report , Student Attendance , Teacher Attendance** , **Student attendance Exception and Teacher attendance Exception** 

![Image](https://user-images.githubusercontent.com/64146636/201076148-32184c9a-b3ac-4170-832a-7c494c675a75.png)

![Image](https://user-images.githubusercontent.com/64146636/201076165-824cdfb7-1ab6-40df-82ab-4fc9de855752.png)

![Image](https://user-images.githubusercontent.com/64146636/201076183-3e37ce79-5420-42cd-9c67-790eafa27d42.png)

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and to be analyzed

**Comment by ananya-jain1** [comment]
Hi @chetandg123 - can you please give an example of why a default month is required? A user can currently select any month from the dropdown.

**Comment by chetandg123** [comment]
@ananya-jain1 For Teacher Attendance reports we are sending month-wise data so suppose there are two months of data present in the application namely January (2021-22 ), June(2021-22), and March (2022-23), April (2022-23)
if the user selects the time period as year and month  as 2021-22 or 2022-23  by default any academic year should be chosen it is the behavior of the feature if by default month is not selected such situation month dropdown has 2 options we cant display two months of data on the screen if any one option selected then that month data should be displayed on the map markers 
for reference to above-attached screenshot - the map should by default any one-month data so the dropdown should display  month name which map is showing the data

**Comment by RNarmatha** [comment]
We introduced Calender option , in that we can choose which date , month and year
