### ISSUE TITLE
Regression Defect - Usage by Course - Course Dropdown width is small

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#714]
Course dropdown should be required more width because unable to see complete course name 

![Image](https://user-images.githubusercontent.com/64146636/201077299-b9baf9d1-1094-48e8-9f2a-9f4c2d232b77.png)

**Comment by chetandg123** [comment]
**Select any course option from user progress report - Download Report button is not aligned properly** 



![Image](https://user-images.githubusercontent.com/64146636/201083052-53a6c2a8-de40-4bf7-ba0c-fd00c2d7d3df.png)

**Comment by RNarmatha** [comment]
This issue is not covered in v5.0 and to be analyzed

**Comment by ananya-jain1** [comment]
@htvenkatesh @pandutibil - request you to include this enhancement in v5.0 as part of February sprints.

**Comment by RNarmatha** [comment]
This Course program not consider in the current Sprint will be taken in to analysis
