### ISSUE TITLE
Regression Defect - User Engegement Report showing no data available

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#715]
After processing yesterday summary data file to diksha , still we are not able to see data in user engegement 
machine - demo3
Bucket - qa10 

![Image](https://user-images.githubusercontent.com/64146636/201260099-63433f40-5c6c-490f-9079-57a6b7ab738e.png)

**Comment by padmanabha1234** [comment]
@PavitraIR The data is processed with latest date, query is not returning any data. please look into this

**Comment by PavitraIR** [comment]
@chetandg123 The collection name and district id in diksha_total_content table and diksha_tpd_agg table doesn't match and in the query we are joining these two tables using those columns.

So please emit appropriate data file into diksha_total_content and dikha_tpd_agg with matching data for collection_name, and district_id ,

**Comment by chetandg123** [comment]
@devu1454 can you check above update

**Comment by chetandg123** [comment]
@htvenkatesh 
@padmanabha1234 
Data present in the data base and in output files are generated with null

**Comment by devu1454** [comment]
Re-processsed the same data again. Data is displayed
