### ISSUE TITLE
National VSK enhancement | DiSanc Survey

### ISSUE THREAD

**Issue by RNarmatha** [Sunbird-cQube/community#717]
There is a request for a few urgent changes within the NCF program in National VSK. Attached are the CSV files with the data incorporated. 
A Separate tab by the name DiSanc survey should be incorporated within the NCF program. Two charts showing the countrywide heat map and the bar chart should be shown side by side.
Country-wide heat map showing state-wise Disanc survey done
Bar chart showing language-wise survey done - This shows how many people have been surveyed in language

![Image](https://user-images.githubusercontent.com/111988710/201658926-bbba489a-7a3f-4db3-a357-fefd69f2cfae.png)

At present, the configurations are provided by the cQube team. Request the team to share the modified configurations at the earliest.

NCERT is using cQube Edu v1.5 (July, 2022) at the moment. The plan is to update the same with modified configuration.

**Comment by pandutibil** [comment]
New reports has added in the national curriculum framework

**Comment by pandutibil** [comment]
@devu1454 Please test this

**Comment by Inchara98** [comment]
These are the few issues in NCF - Disanc Survey
**Issue 1 :** All Languages in the y-axis are in BLOCK letters 

![Image](https://user-images.githubusercontent.com/89445054/201670981-aafdd3a7-5e5b-4634-8c0e-2d7feddc66cc.png)

**Issue 2** :Values not separated by comma in tooltip


![Image](https://user-images.githubusercontent.com/89445054/201671670-a2d3797a-55aa-45e8-8d1a-e1fe85fce043.png)

**issue3**: Download button is not present 


![Image](https://user-images.githubusercontent.com/89445054/201671892-307ebb20-339d-4bd7-a8b6-6c55f75f8387.png)

**Comment by Inchara98** [comment]
@FaizanMohammed326 issue 1 not resolved

**Comment by RNarmatha** [comment]
Completed and It is up
