### ISSUE TITLE
Legend issues in NVSK

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#718]
PM Poshan(Implementation status)

![Image](https://user-images.githubusercontent.com/114054046/201669677-9d3804eb-2c7d-48c9-a880-a338abd5e35b.png)

Micro improvements (Improvement status)
![Image](https://user-images.githubusercontent.com/114054046/201669729-3b1a31a7-2afb-40d0-8fff-d69d16654b87.png)

Micro improvements (Implementation status)
![Image](https://user-images.githubusercontent.com/114054046/201669760-5f3f434c-67f6-45bb-9147-3ee58d757d5d.png)

Pm poshan (progress status)
![Image](https://user-images.githubusercontent.com/114054046/201670156-69f481c5-fd60-477c-9a87-765acad987e0.png)

**Comment by Inchara98** [comment]
Udise 
2 legends are displaying 


![Image](https://user-images.githubusercontent.com/89445054/201674490-dbefd86f-72df-426d-80ff-524d663cff27.png)

**Comment by RNarmatha** [comment]
Issue is Fixed
