### ISSUE TITLE
Issue in Disanc Survey (NCF-NVSK)

### ISSUE THREAD

**Issue by Inchara98** [Sunbird-cQube/community#719]
NCF - Disanc Survey
**Issue 1 :** All Languages in the y-axis are in BLOCK letters 

![Image](https://user-images.githubusercontent.com/89445054/201670981-aafdd3a7-5e5b-4634-8c0e-2d7feddc66cc.png)

**Issue 2** :Values not separated by comma in tooltip

![Image](https://user-images.githubusercontent.com/89445054/201671670-a2d3797a-55aa-45e8-8d1a-e1fe85fce043.png)

**issue3**: Download button is not present 

![Image](https://user-images.githubusercontent.com/89445054/201671892-307ebb20-339d-4bd7-a8b6-6c55f75f8387.png)

**Comment by RNarmatha** [comment]
Issue is Fixed
