### ISSUE TITLE
Analysing the SAT KPIs

### ISSUE THREAD

**Issue by Ramya-kmurthy** [Sunbird-cQube/community#721]
To identify the required : 
 Cubes
 List dimensions
 Events required for the KPIs

**Comment by JalajaTR** [comment]
Listed all the Cubes and dimensions for SAT KPI's and the document link is added below
[https://docs.google.com/spreadsheets/d/1y7-GR0SrIDHGA9Jj-A5FPqLdJ-SjgWUEU-xgVcKSNIo](Document)
