### ISSUE TITLE
Karate testing framework training

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#722]
1.**Contents**
1.1.**Overiew of Karate framework**   --------------------------------- 1 hr
1.2.**Environment setup -**-------------------------------------------- 2 hr
1.2.1.Installation Java 
1.2.2.Installation IDE
1.2.3.Maven Plugins (Karate core,Karate Apache & Karate JUnit5)
1.3.**Understanding of karate framework terminologies** --------------- 2 hr
1.3.1.Feature
1.3.2.Scenario
1.3.3.Given
1.3.4.When
1.3.5.Then
1.3.6.And
1.4.**Execution of simple program** ----------------------------------- 1 hr
1.5.**Understanding of HTTP methods** --------------------------------- 1 hr
1.5.1.GET
1.5.2.POST
1.5.3.PUT
1.5.5.DELETE
1.6.**Usage of HTTP methods in .feature file**------------------------- 2 hr
1.7.**Understanding of Assertions** ---------------------------------------- 2 hr
1.8.**Real-time practice of Assetions**------------------------------------2 hr

**Comment by chetandg123** [comment]
Need to go through this points:

- [ ] What is karate ? why it is used ?

- [ ] What are required dependencies using karate ? 

- [ ] How API logic can be written and how the response validations can be done ?

- [ ] How is the karate framework works and how the testing reports can be generated ? 

- [ ] Setup karate framework in the local system

**Comment by devu1454** [comment]
Completed the Karate framework training from 1.1 to 1.6 using eclipse ide

**Comment by chetandg123** [comment]
Completed the analysing the karate framework from 1.1 to 1.5 topics

**Comment by devu1454** [comment]
Completed the Below topics in APi_Automation using karate framework in udemy course
1.First get request
2.Url and path
3.Simple assertions
4.First post request
5.Runner configuration and tags
6.Delete request
7.Calling other features
8.Environment variables

**Comment by RNarmatha** [comment]
Invalid moved to JIRA
