### ISSUE TITLE
Jmeter tool training

### ISSUE THREAD

**Issue by TanushreeSG** [Sunbird-cQube/community#723]
Jmeter - Topics

- [x] How to do API testing using Jmeter tool
- [x] How to create 1st jmeter test
- [x] How to use assertion
- [x] How to use listners
- [ ] Config elements
- [ ] How to create database test plan
- [ ] How to run jmeter from command line
- [ ] Testing web services API
- [ ] How to create assertion for database testplan
- [ ] How to create HTML reports from command line
- [ ] How to use plugins manager
- [ ] How to run data from csv file
- [ ] Functions and variables
- [ ] How to setup realistic performance test-Pacing
- [ ] How to add Think time
- [ ] How to run scheduled + sequential execution
- [ ] Correlation
- [ ] How to use templates
- [ ] How to test file upload
- [ ] How to test file download
- [ ] How to debug
- [ ] How to add perform
- [ ] Remote testing master slave Distribution testing
- [ ] Jmeter selenium webdriver sampler
- [ ] JMX checker tool

**Comment by Inchara98** [comment]
Completed topics list - Nov16

- How to create 1st Jmeter test
- How to use assertions
- How to use listeners
- JSON extractor task given by vinay

**Comment by TanushreeSG** [comment]
Completed topics list - Nov16

How to create 1st Jmeter test
How to use assertions
How to use listeners
JSON extractor task given by vinay

**Comment by RNarmatha** [comment]
Invalid moved to JIRA
