### ISSUE TITLE
Grammar and types in JavaScript

### ISSUE THREAD

**Issue by pandutibil** [Sunbird-cQube/community#728]
Learn about Grammar and types in JavaScript and implement a sample programs based on your understanding.

**Comment by Ramya-kmurthy** [comment]
Explored Grammar and types in JavaScript and implemented the sample script.

**Comment by bommalla** [comment]
I gone through the Grammar and types in JavaScript and implemented the sample script.

**Comment by PavitraIR** [comment]
I gone through the Grammar and types in JavaScript and implemented the sample script
