### ISSUE TITLE
Control flow and error handling in JavaScript

### ISSUE THREAD

**Issue by pandutibil** [Sunbird-cQube/community#729]
Learn about control flow and error handling in JavaScript and implement a sample programs based on your understanding

**Comment by Ramya-kmurthy** [comment]
explored about control flow and error handling in JavaScript and implemented  sample programs

**Comment by bommalla** [comment]
I gone through the control flow and error handling in JavaScript and implemented sample programs

**Comment by PavitraIR** [comment]
gone through the control flow and error handling in JavaScript and implemented sample programs.
