### ISSUE TITLE
Error while parsing the configuration file

### ISSUE THREAD

**Issue by krishnakr6** [Sunbird-cQube/community#74]
Below are the Configuration Files used

1. book distribution.
2. student enrolment. 
3. textbook distribution.

**storage type:** on-premise

**Comment by JalajaTR** [comment]
Issue is fixed and code is pushed

**Comment by padmanabha1234** [comment]
Syntax error in the python code, issue is fixed and code is pushed.

**Comment by devu1454** [comment]
The above issue was re-tested and it's resolved now.
