### ISSUE TITLE
Nifi performance

### ISSUE THREAD

**Issue by htvenkatesh** [Sunbird-cQube/community#744]
Nifi performance - csv (event) + processor group → python transformer → output csv
  > I/O1:
     Input: csv (school_id, grade_id, count) - count of students by school, grade - 5k records
     Output: csv (school_id, count) - count of students by school 
  > I/O2:  
     Input: csv (Date,school_id, grade_id, total_sudents,students_attended) - percentage of students by grade, 
               5k records
     Output: csv (Date,school_id, grade_id,student_attendance_percentage) - attendance percentage by students present
  > I/O3:
     Input: csv (school_id, semister,grade_id,subject_d,student_id,obtained_marks) -  count of students who has 
               scored above 35, 5k records
     Output: csv ('school_id','semister','grade','subject_id','number_stud_scored_above_35') - count of students 
                by subject

3 distinct processor groups :
  >   read the input csv
  >   do group by operation
  >   upsert to output csv

**Comment by RNarmatha** [comment]
Invalid

**Comment by RNarmatha** [comment]
Moved to JIRA
