### ISSUE TITLE
Percentage metric is wrong in the output files showing 100 % for all the levels - districts,blocks,clusters and schools.

### ISSUE THREAD

**Issue by krishnakr6** [Sunbird-cQube/community#75]
**Data File used**
book_distribution_data.

**storage type:** on-premise
**Metrics configured:** percentage and sum

**Comment by JalajaTR** [comment]
The columns to calculate the percentage was taken wrongly through python and it is fixed.

**Comment by devu1454** [comment]
The above issue was re-tested and it's resolved now.
