### ISSUE TITLE
NiFi State Management

### ISSUE THREAD

**Issue by ChakshuGautam** [Sunbird-cQube/community#755]
Is NiFI always running? Yes, in Idle state. Once the daily job is run - why is NiFi kept running? We should implement auto On/Off for the cluster. => Define fixed clusters and variable clusters.

**Comment by ChakshuGautam** [comment]
@satendrapalsingh I think you have the following two concerns
1. Cold start timings of Nifi.
2. Idle state resources used by it.

Let me know if I am in the right direction and then we can discuss this in detail. Thanks.

**Comment by RNarmatha** [comment]
It is implemented in the current version as schedule API
