### ISSUE TITLE
Evaluate Airflow

### ISSUE THREAD

**Issue by ChakshuGautam** [Sunbird-cQube/community#757]
How are dependencies in processing jobs handled? Is there any scheduling along with dependencies? => Should use Airflow.

**Comment by ChakshuGautam** [comment]
@satendrapalsingh Nifi is very similar to Airflow - can you share a deeper comparative analysis on how a switch would help here?

**Comment by RNarmatha** [comment]
Currently we are using Nifi for Processing and Job Scheduling . Airflow process we haven't consider in the current development. 

If we to evaluate the Airflow we can take this to backlog
