### ISSUE TITLE
New Processors in Nifi

### ISSUE THREAD

**Issue by ChakshuGautam** [Sunbird-cQube/community#758]
How can we add a processor to NiFi? Show base processor group. Please add comments (e.g. JOLT processor code for NiFi) - Update: What is the expectation?

**Comment by ChakshuGautam** [comment]
Any new processors that need to be added to Nifi need to be preconfigured - those preconfigured processors can be _leveraged_ using the Nifi processor API. I am not aware of a way to add binaries to a Nifi installation.

@satendrapalsingh can you help me understand the use cases that we want to cover to be able to figure out the kind of processors that will be required here?

**Comment by RNarmatha** [comment]
Commented by Chakshu
