### ISSUE TITLE
Evaluate Spark as a processor

### ISSUE THREAD

**Issue by ChakshuGautam** [Sunbird-cQube/community#759]
Does Configuration change if Spark used instead of NiFi? - Update: Answer - Configuration file is not coupled with NiFi, Hence we can reuse the configuration file.

**Comment by ChakshuGautam** [comment]
@satendrapalsingh It would be great if this feature can be contributed by the community. We can abstract the config out to use any processor available. We are creating a generic processor API for this - which should support any processor.

**Comment by RNarmatha** [comment]
Currently we are using NIFI as a processor and SPARK is  not evaluated
