### ISSUE TITLE
OCI compatibility for cQube

### ISSUE THREAD

**Issue by manojsah13** [Sunbird-cQube/community#767]
### Discussed in https://github.com/orgs/Sunbird-cQube/discussions/766

<div type='discussions-op-text'>

<sup>Originally posted by **manojsah13** March 25, 2023</sup>
Hello Everyone,

Please suggest if cQube is compatible with Oracle cloud infrastructure.</div>

**Comment by RNarmatha** [comment]
Hi @manojsah13 - Yes ,  Latest cQube version  is compatible with Oracle cloud Infrastructure
