### ISSUE TITLE
Enable all existing "cQube 1" dashboards and reports using 'data source configuration'

### ISSUE THREAD

**Issue by surendrasinghs** [Sunbird-cQube/community#84]
cQube 1 (v3.7) has enabled data source configuration so that new data sources can be configured. This data source configuration should support all existing data sources as well so that we have a truly configurable generalised cQube.

cQube enables us to configure data sources to generate metrics with required dimensions so that these metrics can be used to create charts in a report inside a dashboard.

1. Please share a gap analysis of which data sources cannot be configured using cQube 1 (v3.7) and why? [Here's a list](https://docs.google.com/spreadsheets/d/17JLx-2syXIm_L_UXqU6oXNA08ERpHPjSp2p6f6U-fRM/edit#gid=466061995) of dashboards, reports and charts currently enabled in cQube 1
2. Propose a change in the configuration file, data ingestion logic, and other components if any.
3. Initiate development only after proposed changes are discussed and aligned.
4. Create configuration files for all existing data sources before changing a single line of code so that we can visualise it.

**Comment by RNarmatha** [comment]
Partially  completed

**Comment by RNarmatha** [comment]
Added into backlog
