### ISSUE TITLE
Enable all currently supported chart types in a configurable manner

### ISSUE THREAD

**Issue by surendrasinghs** [Sunbird-cQube/community#85]
cQube 2 has enabled highly configurable data visualisation using which we can configure Dashboards, Reports and Charts. It enables a reference app that has Dashboards, Dashboard contains Reports with different layouts, and Reports contain Charts and additional functionality.

We need to support all chart types already enabled in cQube so far in the same configurable manner. Here's a list 
1. Map-based visualization
2. Scatter plot visualization
3. Gauge Chart (additional in cQube 2 (cQube Edu))
4. Table format visualization
5. Bar chart visualization
6. Stacked bar report (To do)
7. Pie Chart visualization (To do)
8. Heat Chart visualization (To do)
9. Area Chart visualization (To do)
10. Line Chart visualization (To do)
11. Multi Bar Chart visualization (To do)
12. Trend Chart visualization (To do)
13. Composite Report visualization (Scatterplot) (To do)

Please share an implementation design and approach before initiating development.

**Comment by RNarmatha** [comment]
Partially completed

**Comment by RNarmatha** [comment]
These are implemented 
Map-based visualization
Scatter plot visualization
Table format visualization
Bar chart visualization
Stacked bar report 
Multi Bar Chart visualization 
Trend Chart visualization
Composite Report visualization (Scatterplot) )
