### ISSUE TITLE
cQube v3.7 backward compatibility: Support "cQube 1" input data sources, chart types, and reports as-is.

### ISSUE THREAD

**Issue by surendrasinghs** [Sunbird-cQube/community#87]
cQube v4.x should be backwards compatible with cQube v3.7. It should ensure that all currently supported 

- [ ] 1. data sources and the metrics generated from them continue to be generated as-is. 
- [ ] 2. chart types where the metrics are visualised continue to be supported as-is.
- [ ] 3. https://github.com/Sunbird-cQube/community/issues/84

This [sheet contains the details](https://docs.google.com/spreadsheets/d/17JLx-2syXIm_L_UXqU6oXNA08ERpHPjSp2p6f6U-fRM/edit#gid=466061995).

This should be done by implementing the Sunbird architectural principles of Generalisation, Configurability, Modularity, Interoperability, Evolvable, and Sustainability.

Please publish a gap analysis and detailed task list.

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
Added to backlog
