### ISSUE TITLE
cQube Edu v1.5 backward compatibility: Support "cQube 2" input data sources & dashboards, reports, charts as-is

### ISSUE THREAD

**Issue by surendrasinghs** [Sunbird-cQube/community#88]
cQube v4.x should be backwards compatible with cQube Edu v1.5. It should ensure that all currently supported

- [ ] 1. data sources, data processing, transformation and the metrics generated from them (if any) continue to be generated as-is.
- [ ] 2. dashboards, reports, and charts continue to be supported as-is.

This [sheet contains the details](https://docs.google.com/spreadsheets/d/1VNN8jCJT1Vom-1ByckmxTyfaCFrS3opAChL0y9XAqk4/edit#gid=0).

This should be done by implementing the Sunbird architectural principles of Generalisation, Configurability, Modularity, Interoperability, Evolvable, and Sustainability.

Please publish a gap analysis and detailed task list.

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
Added into the backlog
