### ISSUE TITLE
DIKSHA Connector

### ISSUE THREAD

**Issue by surendrasinghs** [Sunbird-cQube/community#89]
cQube is an emit-ready and emit-only system. Any external system will need to emit the data into cQube.
cQube will provide a reference connector and also implement it for DIKSHA (the national school education platform in India).

It should be fairly easy to connect any existing State/National system with cQube using the connector.

Please share a technical design and detailed task list.

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
This is not implemented in the current version. It can added to the RoadMap
