### ISSUE TITLE
Diksha TPD Report - Course name should not be reset after selection of District

### ISSUE THREAD

**Issue by SreenivasNimmagadda** [Sunbird-cQube/community#9]
**Feature requirement**
The Course drop down is resetting when the location is changed in Diksha TPD Report. If it is reset always the user has to select the course when the user is changed the location. 

It is difficult to to select the course on changing of the location as there is no search option to select the course.

**Describe the solution you'd like**
As the courses are same for all the districts, The selected course should not be reset once the district is changed.

Refer the below screenshots,

![image](https://user-images.githubusercontent.com/61133774/136218143-01c95d0a-afef-4459-83e0-95ff382a1ceb.png)
![image](https://user-images.githubusercontent.com/61133774/136218159-145584e1-ab67-4998-8b3b-c1257f436ab6.png)

**Proposed Solution**
Have to keep the selected course as constant for all the locations. 
If the location is not having the course content data, Display as "No data found"

**Comment by dheeraj8008tiwari** [comment]
This task has been completed.
