### ISSUE TITLE
cQube v4.0 reference visualisation app (new and improved look & feel)

### ISSUE THREAD

**Issue by surendrasinghs** [Sunbird-cQube/community#91]
The reference visualisation app should 
1. enable configuration of dashboard, reports, and charts. As of today, dashboard = menu and report = page (with multiple layouts).
2. ensure all existing features of cQube v3.7 and cQube Edu v1.5 are supported in a configurable manner. 
3. Features such as: 
    1. Configurable filters (dropdown)
    2. Granularity Level of data (e.g. District, Block, Cluster, School)
    3. Download
    4. Absolute/relative metrics
4. Preserving context of filters and granularity level when downloading or navigating to other reports
5. Interactive drill-down using the legend
6. Interactivity Charts e.g. Drill-down location on Map, Sort on Table, and so on
7. Breadcrumb to show the current location filter applied to the report
8. ... <add other features>

9. The reference visualisation app supports configuration for dashboards, reports, and charts. 
10. It uses exhaust API to get metrics generated from the data source.
11. ... <add more details>

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
These visualization are addressed in the current version
