### ISSUE TITLE
Number System Preference - For Reports

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#92]
For Indians Lakhs and Crores. See if you can have a config on UI itself (like a preferences page where display language, metrics, theme, etc can be changed). Simply store the preferences locally on the browser (since there is no login). That way we don’t have to hard code anything. Please ensure metrics are in expanded numbers (not stored as 5 lakhs, rather stored in DB as 500000). Rendering time it can be shown in Million/Billion or Lakh/Crore.

The preferences menu can be under the profile menu - even for guest/anonymous view.

The number system preference should

Support various locales starting with US and India
Various formats starting with short and long

**Comment by RNarmatha** [comment]
Completed
