### ISSUE TITLE
cQube Architectural Enhancements

### ISSUE THREAD

**Issue by surendrasinghs** [Sunbird-cQube/community#94]
### Overall

1. Generalise it for global usage. No Hard-coding. No actual data in the public repo. Use generic terms. Keep only mock data and sample reference configurations in the public repo.
2. Review current (cQube v3.7, cQube Edu v1.5) and proposed (cQube v4.0) architecture
3. Follow open-source community best practices. Leverage GitHub, GitBook, and other tools to the best.
4. Make cQube scale ready and easy to adopt. Simplify tech stack for wider adoption.

### Ingestion and Processing

1. Review data privacy, isolation, and archival policy
2. cQube should provide out-of-the-box metrics and metric templates for various sectors. For example, attendance, performance, etc in the Education sector. This is referred to as "Standard based ingestion" and "Standard Metrics"
3. Ensure modularity of ingestion, processing, and visualisation by separating their configuration files.
4. Ensure support for external analytics & dashboard tools such as Metabase

### Connector

1. Implement a connector for DIKSHA and provide a reference connector for wide-range of systems so that they can emit easily into cQube

### Reference Visualisation App

1. https://github.com/Sunbird-cQube/community/issues/90
2. Rolling out a new dashboard in cQube Edu requires an HTML file + a configuration file. Should simplify this by implementing data-driven pages as done in Sunbird Obsrv and Sunbird ED.

### User Management

1. Ensure interoperability with any auth provider. Implement a well-defined SSO interface. No hard coupling with Keycloak.

### DevOps

1. Review Branching and Versioning Strategy, DevOps Automation, SecOps for Security against threats, 
2. Define new repository structure and code organisation

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
This will be moved to the Road map
