### ISSUE TITLE
Refactor the python code which  parses the  Configuration file [ Data Processing ].

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#95]
Following are the Functionalities included in Python code:

1. Multiple table creations is not handled and the table creation part is repeated for different table creations like staging, temp, 
   duplicate and null tables.
2. The same configuration file is read in two different functions which are responsible for creating nifi parameters and the table 
    creation queries.
3. Need to update the metrics creation part which is repeated for aggregation part and the report queries part.

**Comment by RNarmatha** [comment]
This problem will be addressed in cQube v5.0.

**Comment by RNarmatha** [comment]
This is invalid
